design : manager/home/03
mobi-projects/nail-case-client pull request #100
Opened 2024-06-25 14:30 UTC by keeprok

## 🔥 Issues

* issue:[NAILCASE-137](https://nailcase.atlassian.net/browse/NAILCASE-137)
* sub-issues:
- [NAILCASE-166](https://nailcase.atlassian.net/browse/NAILCASE-166)
<br/>
<br/>

## 🎯 작업 내용

[🎨 manager/home/03](https://github.com/mobi-projects/nail-case-client/commit/f8c9b0d01af984f0d97dca19e9c09c76f7e02f80)
- 03-01,03-02 생성했습니다 
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/6160f72c-6c69-4481-90cd-019020e4d351)
# Home/03 작업 CardListForm완료
![스크린샷 2024-06-25 오후 2 27 31](https://github.com/mobi-projects/nail-case-client/assets/140785214/d624018f-dabf-4189-942a-294454d6f17f)

## Home/03-01 작업 CardList완료
## Home/03-01-01 작업 MainCard
<img width="404" alt="스크린샷 2024-06-25 오후 11 10 32" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/7a9f8f83-8527-433b-b50e-30b94f2aebc0">

## Home/03-01-02 작업 SubCard
 
<img width="289" alt="스크린샷 2024-06-25 오후 11 10 35" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/d9268dae-e507-4b62-8fa9-8eb050f33fb9">
# 해결해야될사항
<img width="217" alt="스크린샷 2024-06-25 오후 11 29 14" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/cf6e490d-885e-48a3-a54f-6c776d3fcf3a">
- 이슈에 올렸듯 오른쪽으로 사진을띄울때 전체적화면 이 커지는 현상이 발생해 해결 도중입니다 

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-25 21:45 UTC, TransparentDeveloper requested changes
음,, 스크롤이 제대로 동작하는 확인하는 걸 보고 싶은데,,
이미지보단 동영상 자료를 업로드해주시는 게 더 좋을 거 같습니다.

리뷰 반영하면서 같이 부탁드립니다 :)

2024-06-25 21:45 UTC, TransparentDeveloper commented on src/component/custom/manager/base/home/03/index.tsx
> +	}, [])
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"


# Description
무슨 의도죠?? 제 관심 한번 끌어보겠다는 건가요?? 
성공하셨습니다. 👍

2024-06-26 14:18 UTC, keeprok commented on src/component/custom/manager/base/home/03/index.tsx
> +	}, [])
image 가 div 안에있다고 사이드 렌더링 (SSR)과 클라이언트 사이드 렌더링 (CSR) 간의 불일치로 인해 발생해서 해결하기 위해 넣었고 저희 데이터를 패치하면서 수정및 삭제를 해야될것같습니다

2024-06-26 15:32 UTC, snkchan commented on src/component/custom/manager/base/home/03/index.tsx
> +	}, [])
@keeprok 에러메세지도 함께보여주시겠어요???? issue가생겼는데 해결안하고 merge하는것은 아닌거같은데

2024-06-27 06:09 UTC, keeprok commented on src/component/custom/manager/base/home/03/index.tsx
> +	}, [])
저 함수를 통해 에러 메세지를 해결해서 따로 올리진않았는데 일단 에러는
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

Did not expect server HTML to contain a <img> in <div> 이거 였습니다

2024-06-27 09:42 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"

2024-06-27 09:42 UTC, TransparentDeveloper commented on src/component/custom/manager/base/home/03/index.tsx
> +	}, [])
음,, 클라이언트 단에서 랜더링된 후에 상태를 업데이트 하는거군요..
알겠습니다.! 
고생하셨습니다 :)

2024-06-27 13:54 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-27 15:26 UTC, snkchan approved these changes
- LGTM..!

2024-06-27 15:35 UTC, merged