refactor : NTOption refactor & css 수정
mobi-projects/nail-case-client pull request #112
Opened 2024-06-29 09:34 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-213](https://nailcase.atlassian.net/browse/NAILCASE-213)
sub-issues:
  - [NAILCASE-216](https://nailcase.atlassian.net/browse/NAILCASE-216)
<br/>
<br/>

## 🎯 작업 내용

# 👇NTOption 수정사항
- [⚡️ NTOption refactor](https://github.com/mobi-projects/nail-case-client/commit/fe4eb4893b13cfcc86a97d272706b25a51515a79)
## 🛠삭제 & 추가된 props
### [삭제] itemsPerRow
> itemsPerRow 속성은 한줄에 몇개의 option을 보여줄지 정하는 option 이었습니다 
### [추가] gap
> 새로 추가된 gap 속성은 각 option 사이의 간격을 설정하는 역할을 합니다.
```tsx
ex)
<NTOption  gap = "gap-x-2 "/>   // option사이의 간격을 gap-x-(원하는간격) 형식으로 전달해서 사용합니다.
```
**추가된 이유**
- figma상에서 option들의 간격이 일정하지 않아서 각 페이지에 맞게 간격을 설정해서 사용하기 위해 추가했습니다.
<br/><br/>
## ☝[Case 1] click 불가능한 Option
**클릭이 불가능한 경우에는 useOption을 사용하지 않고 optionArr 속성만 사용합니다**
```tsx
ex)
<NTOption optionArr={["이달의 아트", "연장 필요"]} /> // option을 배열형태로 전달
```
> optionArr만 전달할경우 click불가 & cursor-default로 적용됩니다.

## ☝[Case 2] click 가능한 Option
**클릭이 가능한 경우에는 useOption을 사용합니다**
```tsx
//step 1 useOption을 호출
const { checkedOption, onClickOption, optionArr } = useOption()

//step 2 useOption을 호출시 option배열을 전달
const { checkedOption, onClickOption, optionArr } = 
useOption( [ [ "오후 1시"  ,  "오후2시"] ,   [   "아침" ,  "점심"   ]   ]) 

//setp 3 컴포넌트에 return값을 전달
<NTOption
	optionArr={optionArr[0]}      // [ "오후 1시"  ,  "오후2시"] 을 전달
        checkedOption={checkedOption}
	onClickOption={onClickOption}
/>
<NTOption
	optionArr={optionArr[0]}     //  [   "아침" ,  "점심"   ]   을 전달
        checkedOption={checkedOption}
	onClickOption={onClickOption}
/>

```
<br/><br/>
 ## checkedOption
 > checkedOption은 클릭된 option들을 배열형태로 저장합니다. ==> 외부컴포넌트에서 선택된 옵션을 파악하기위해 사용
 <br/>
 
# 👇css 수정 
- [🎨 NTOption 수정사항 적용](https://github.com/mobi-projects/nail-case-client/commit/99fe927928ef2edc282749298b3ea98e9d60fae0)
- [🎨 css 수정 & Image 속성 수정](https://github.com/mobi-projects/nail-case-client/commit/8767e8336e705b29fbd197fb3cbb0f699b192500)
## 요약
```tsx
// 사용법 최종
<NTOption
	optionArr={optionArr[0]}     
        checkedOption={checkedOption}
	onClickOption={onClickOption}
        gap = "gap-x-2 "  // option사이의 간격 조절할때 사용
        disabled   // disabled 인 option일때만 사용
        size = "medium" // medium 사이즈일때만 사용 default일땐 large 적용 된 상태
/>
```
> 변경점이 많이잡혀서 죄송합니다...
> 수정하다보니 drop-shadow 미적용된 css와 Image컴포넌트 오류 코드를 발견해서 함께 수정했습니다.
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-29 16:10 UTC, HeesikK approved these changes
클릭이 불가능한 옵션이랑 클릭이 가능한 옵션을 나눈 부분은 되게 좋은거 같은데요?😲 
이전에 onClickOption의 전달 유무에 따라 나눈거 보다 훨씬 좋은거 같습니다.
NTOption 사용하는 부분이 많아서 수정할때 힘드셨을텐데 고생하셨습니다..!

2024-06-30 03:38 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-06-30 03:38 UTC, TransparentDeveloper commented on src/component/common/nt-option/index.tsx
> +	gap?: string
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
- tailwind 유틸리티 클래스를 받는다면, className 으로 하는게 좋지 않을까요? 사용할 때 혼란이 있을 것 같아서요.

2024-06-30 03:38 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/02/index.tsx
> +			<div className="flex h-full w-full items-center justify-center rounded-[26px] bg-White drop-shadow-[2.99px_2.99px_14.34px_rgba(224,224,224,0.6)]">
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- box-shadow 에서 drop-shadow 바꾸면 어떤 차이가 있는 건가요?
- svg 가 아니라서, 큰 차이가 없을거라고 생각했습니다.

2024-06-30 03:38 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/02/index.tsx
>  					{paddedFocusedYear} 년 {paddedFocusedMonth} 월
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 이 설정은 필요합니다.
- 너비를 미리 지정해두지 않으면, 날짜(연도, 월) 이 변경될 때마다 텍스트 전체가 좌우로 흔들립니다.

2024-06-30 04:39 UTC, TransparentDeveloper requested changes
컴포넌트 수정한 PR 과 다른 ui 의 css 수정한 PR 을 따로 올리는 편이 좋았을 것 같습니다.

변경점을 보고 리뷰하는데, 작업이 뒤섞여있어서 집중하는게 힘들어요..

2024-06-30 04:39 UTC, TransparentDeveloper commented on src/hook/use-component.ts
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
한 행에 출력할 옵션의 갯수 를 지정하기 위해, 이중 배열이 필요한건가요??
flex-wrap 설정을 미리 해두고, width 와  gap 을 className 으로 하나의 컴포넌트로 해결할 수 있지 않을까요?

추가로, "클릭 옵션" 에 대해 인덱스로 관리하는 편이 좋지 않을까 합니다.
onClickOption 구현이 조금 더 간단해질 것 같아서요.

2024-06-30 08:34 UTC, keeprok approved these changes
수고하셨스빈다

2024-06-30 13:42 UTC, snkchan commented on src/component/common/nt-option/index.tsx
> +	gap?: string
제성합니다... 제가 잘못 설계했네여 <br/>
[🎨 gap? : string => gap?:number로 변경](https://github.com/mobi-projects/nail-case-client/pull/112/commits/86a8a9a10f8028e6628450c509abc81f8e2484cd)<br/>
> gap : string => gap : number 를 받도록 수정했습니다.

2024-06-30 14:10 UTC, snkchan commented on src/component/custom/customer/shop/02/index.tsx
> +			<div className="flex h-full w-full items-center justify-center rounded-[26px] bg-White drop-shadow-[2.99px_2.99px_14.34px_rgba(224,224,224,0.6)]">
[🎨 drop-shadow => shadow custom class로 적용](https://github.com/mobi-projects/nail-case-client/pull/112/commits/d62f6760782aaaf117a86310a90da39ce8d4d583)<br/>
drop-shadow와 shadow의 차이를 몰랐습니다.....<br/>
Riel님이 생성해둔 customClassName shadow를 사용해서 모두 적용했습니다.

2024-06-30 14:10 UTC, snkchan commented on src/component/custom/customer/shop/02/index.tsx
>  					{paddedFocusedYear} 년 {paddedFocusedMonth} 월
- 
[🎨 달력 text layout shift오류 수정](https://github.com/mobi-projects/nail-case-client/pull/112/commits/4df07c4f8c4603438f44d0ed7aad33b22aed1b02)
<br/>완료!

2024-06-30 14:32 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"


# Description
고생하셨습니다.

2024-06-30 14:32 UTC, merged