design : NTToast 작성
mobi-projects/nail-case-client pull request #113
Opened 2024-06-29 12:59 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-209](https://nailcase.atlassian.net/browse/NAILCASE-209)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 NTToast 작성](https://github.com/mobi-projects/nail-case-client/commit/07065dd337eb389cd8aad7a9151077b1d0eeac86)

### 📌 동작 사진
  ![토스트](https://github.com/mobi-projects/nail-case-client/assets/127207625/9f6ec02c-de19-44b8-aded-e69fd0db5323)

### 📌 사용 방법
  
  ```javascritpt
import { Toaster, toast } from "sonner"

<Toaster
	gap={60}
	toastOptions={{
		style: {
			width: "485px",
			right: "20px",
			bottom: "40px",
		},
	}}
/>
<button onClick={() => toast.custom(() => <ToastMessage />)}>
	예약하기
</button>
```
Toast Message를 트리거 할 수 있는 버튼에 `onClick` 이벤트를 적용하여 ToastMessage를 화면에 표시할 수 있습니다.
**반드시 사용할 때 `Toaster`도 같이 사용해야 합니다.**

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-29 20:54 UTC, keeprok reviewed
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->


  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description

2024-06-29 20:54 UTC, keeprok commented on src/component/common/nt-toast/index.tsx
> +				<div className=" ">
삭제 해주세요 className=" "

2024-06-29 20:54 UTC, keeprok commented on src/component/common/nt-toast/index.tsx
> +			className="h-fit w-[450px] rounded-[14px] bg-White px-[20px] py-[20px] drop-shadow-[2.48px_2.48px_12.41px_rgba(224,224,224,1)]"
drop-shadow-[2.48px_2.48px_12.41px_rgba(224,224,224,1)] 이부분 제가 styled 토큰으로 shadow-custom으로 만들엇는데 혹시 없다면 style부분에 추가해주실수있나요

2024-06-30 00:59 UTC, HeesikK commented on src/component/common/nt-toast/index.tsx
> +			className="h-fit w-[450px] rounded-[14px] bg-White px-[20px] py-[20px] drop-shadow-[2.48px_2.48px_12.41px_rgba(224,224,224,1)]"
- [🎨 drop shadow 수정](https://github.com/mobi-projects/nail-case-client/commit/50163a3f334575c85d66890ddb4c58036bf9226a) drop shadow 수정 완료했습니다😁

2024-06-30 01:00 UTC, HeesikK commented on src/component/common/nt-toast/index.tsx
> +				<div className=" ">
넵 삭제 완료했습니다..!

2024-06-30 03:19 UTC, TransparentDeveloper requested changes
# Request Level
  - [x] "✅ LGTM"
  
# Description
제가 전에 리뷰남겼던 부분이 전혀 반영되지 않은 것 같습니다. 
공용컴포넌트라면 조금 더 범용성 있게 사용돼야 한다고 말씀드렸어요.!

toast 를 어떻게 활용할지보다, 피그마 디자인과 똑같이 만드는 거에만 집중을 하신게 아닌가 싶어요.
아래 내용을 진지하게 고민해주셨으면 좋겠습니다..

제가 `24.07.02 오후 2시 30분`,  `24.07.10 오후 4시 30분`에 각각 다른 시술로 예약을 생성했다고 가정해볼께요. 이걸 숍 관리자에게 toast message 로 전달해야합니다. 

지금 코드로 그게 가능할지 고민해주시고, 가능하도록 수정 부탁드립니다.!!

2024-06-30 10:55 UTC, HeesikK commented
> # Request Level
> * [x]  "🚨 꼭 수정해주세요.!"
> 
> # Description
> 제가 전에 리뷰남겼던 부분이 전혀 반영되지 않은 것 같습니다. 공용컴포넌트라면 조금 더 범용성 있게 사용돼야 한다고 말씀드렸어요.!
> 
> toast 를 어떻게 활용할지보다, 피그마 디자인과 똑같이 만드는 거에만 집중을 하신게 아닌가 싶어요. 아래 내용을 진지하게 고민해주셨으면 좋겠습니다..
> 
> 제가 `24.07.02 오후 2시 30분`, `24.07.10 오후 4시 30분`에 각각 다른 시술로 예약을 생성했다고 가정해볼께요. 이걸 숍 관리자에게 toast message 로 전달해야합니다.
> 
> 지금 코드로 그게 가능할지 고민해주시고, 가능하도록 수정 부탁드립니다.!!

- [⚡ ️ToastMessage Props 추가](https://github.com/mobi-projects/nail-case-client/commit/1cc0a3cf2c469a1454812d8053f5148939129f01) 해당 사항 반영해서 수정했습니다..! 예약 시간 관련된 부분은 데이터 fetching이 된다면 propsType값 수정하겠습니다🙂

2024-06-30 16:27 UTC, snkchan approved these changes
- LGTM..! 고생하셧습니다

2024-07-01 07:04 UTC, TransparentDeveloper requested changes
위치 수정만 하고, 말씀해주세요 :)

2024-07-01 07:04 UTC, TransparentDeveloper commented on src/component/custom/manager/base/layout/01/index.tsx
layout 에 둔다고 하지 않았나요? header 컴포넌트에 포함하면, 나중에 찾기 어려워질 것 같습니다.

2024-07-01 10:13 UTC, HeesikK commented on src/component/custom/manager/base/layout/01/index.tsx
- [🚚 NTToast 파일 위치 변경](https://github.com/mobi-projects/nail-case-client/commit/3f866cacab5688656be6aeef616a7434ec892ac3) 수정 완료했습니다!

2024-07-01 10:22 UTC, TransparentDeveloper requested changes
추가 요청 사항입니다.!!

2024-07-01 10:22 UTC, TransparentDeveloper commented on src/component/custom/manager/toast/index.tsx
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
출력할 toast ui 가 앞으로 많이 생길 수 있어요.
toast > index.ts 파일로 만들면, 앞으로 추가되는 건 어떻게 관리해야 하죠?
수정 부탁드립니다.

2024-07-01 14:58 UTC, keeprok approved these changes
Tv

2024-07-02 03:00 UTC, HeesikK commented on src/component/custom/manager/toast/index.tsx
- [🚚 toast/index.tsx > toast/reservation/index.tsx로 변경](https://github.com/mobi-projects/nail-case-client/commit/a9c073c70638471fe354ae1eeba09c7831070c09)
제프님 말씀대로 출력할 toast ui가 많다면 문제가 발생할거 같다고 생각해서 아래와 같이 폴더 구조를 잡아봤습니다.

  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/8a19d8d8-b9cb-4c47-a651-69073521cb4f)

  해당 항목에 해당하는 토스트 ui를 각 폴더에서 관리하면 좋을거 같아요..! 
추가적인 의견 있으시면 말씀해주세요🔥

2024-07-02 10:09 UTC, TransparentDeveloper approved these changes

2024-07-02 15:18 UTC, merged