refactor : this-week 페이지 버튼 클릭시 시간별 예약 내역 출력
mobi-projects/nail-case-client pull request #117
Opened 2024-06-30 07:05 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-162](https://nailcase.atlassian.net/browse/NAILCASE-162) 
* sub-issues:
  - [NAILCASE-172](https://nailcase.atlassian.net/browse/NAILCASE-172)

<br/>
<br/>

## 🎯 작업 내용

- [⚡️this-week 페이지 버튼 클릭시 시간별 예약 내역 출력](https://github.com/mobi-projects/nail-case-client/commit/a53b382ad531c2dcbc06daf5911bd3ce7d8c464d)
  - 디자이너분 의견 반영해서 schedule/this-week 페이지 refactor 진행했습니다. 
  - schedule/this-week 페이지에서 주별 예약 내역에 `>` 버튼을 클릭 시 상단 시간이 바뀌도록 코드를 수정하였습니다.
  - 작업 시간이 **오전 11시 ~ 오후 6시** 일때는 `>` 버튼이 나오고 **오후 1시 ~ 오후 8시** 인 경우 `<` 버튼이 나오도록 작업하였습니다.

## 🎬 동작 영상

### `>` 버튼 클릭 시  **오후 1시 ~ 오후 8시** `<` 버튼 클릭 시  **오전 11시 ~ 오후 6시**
### 시간대가 변경되면 예약 내역도 시간에 맞게 변경하는거 확인했습니다.

![시간변경](https://github.com/mobi-projects/nail-case-client/assets/127207625/6770b8cd-f885-4158-b5e5-174837592462)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-30 14:35 UTC, keeprok reviewed
idx부분만 수정해주세요 저번에 놓쳤네요

2024-06-30 14:35 UTC, keeprok commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
>  	[
개인적인 이야기지만 이런부분은 몫데이터인데 길어지면 보기 힘들어서 따로 파일을 만들어서 관리하는게 좋지않았을까요 ???제안이라 수정해주실필요는 없습니당

2024-06-30 14:35 UTC, keeprok commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +function ManagerScheduleTask({ index, startHour }: ManagerScheduleTaskPT) {
저희 index는 Idx를사용하자고 컨벤션으로;;

2024-06-30 14:35 UTC, keeprok commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +function ManagerScheduleTask({ index, startHour }: ManagerScheduleTaskPT) {
놓쳤엇네요 저번에

2024-06-30 15:46 UTC, snkchan requested changes
- 배경 투명도만 수정해주세요~

2024-06-30 16:22 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"


# Description
고생하셨습니다

2024-06-30 16:22 UTC, snkchan approved these changes
-LGTM..!

2024-06-30 17:10 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +function ManagerScheduleTask({ index, startHour }: ManagerScheduleTaskPT) {
- [⚡컨벤션에 맞게 코드 수정 ](https://github.com/mobi-projects/nail-case-client/commit/32d832c1ace11a8795d5331ae28ad7781e49179a) 수정 완료입니다..!

2024-07-01 14:57 UTC, keeprok approved these changes
lG 전자!

2024-07-01 15:11 UTC, merged