design  : root layout width
mobi-projects/nail-case-client pull request #12
Opened 2024-06-04 15:49 UTC by keeprok

## 🔥 Issues

* issue: [NAILCASE-51](https://nailcase.atlassian.net/browse/NAILCASE-51)

<br/>
<br/>

## 🎯 작업 내용

[🔥 global.body width 삭제](https://github.com/mobi-projects/nail-case-client/commit/d8adc1eb769a39e9f6fdf2f434ef29d6f38a5609)
- global.css 에서 관리하던 my-auto , with부분 삭제 하였습니다  
    - global부분은 body 부분에서 고정하기 도 하고 layout을 통해 사이즈를 관리 하기 쉽게 만들기위해 삭제 했습니다  

[🎨 layot 변경](https://github.com/mobi-projects/nail-case-client/pull/12/commits/fb3271c30f8046cb8d9c3e99d5ca339a102728d8)
- page부분에서 가운데 정렬을 고정해두었던것을 start로 변경함에 따라 시작점을 유동적으로 사용가능하게 하였습니다

[⚡️ layout 부분 css변경](https://github.com/mobi-projects/nail-case-client/pull/12/commits/37f0a40bffb5c03c6f9daec28e4d22130e20a85d)
- 전체적인 body에 최대사이즈 를 1500px을 주던것을 최대사이즈를 조절할필요가 없다 판단 삭제 하였습니다
- main 부분을 1200px을 주면서 가운데 정렬을 하였습니다

[🔥 불필요 코드 삭제](https://github.com/mobi-projects/nail-case-client/pull/12/commits/22ab43d4eb9274952baa451a387bd84055199105)
- 전체적으로  확인을위해있던 배경색 삭제 조치하였습니다 

[🔥 불 필요 코드 삭제](https://github.com/mobi-projects/nail-case-client/pull/12/commits/fcca7cbde66e8a08c73fee889ff7db6b9b6a7bd1)

[🔥 불 필요 코드 삭제](https://github.com/mobi-projects/nail-case-client/pull/12/commits/fcca7cbde66e8a08c73fee889ff7db6b9b6a7bd1)
- prettier 때문에 생기는 빈칸 변경 커밋입니다 
- 앞으로 코드 확실히 확인해서 커밋 수 줄이겠습니다

https://github.com/mobi-projects/nail-case-client/assets/140785214/36b39f32-e395-48db-89d5-d39bd73dfd68

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

[NAILCASE-51]: https://nailcase.atlassian.net/browse/NAILCASE-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-04 17:39 UTC, snkchan commented
- @keeprok
[🎨 layot 변경](https://github.com/mobi-projects/nail-case-client/pull/12/commits/fb3271c30f8046cb8d9c3e99d5ca339a102728d8)
- 이커밋에서 어떤작업했는지도 남겨주시겠어요?

2024-06-04 18:12 UTC, TransparentDeveloper requested changes
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 똑같은 코드로 테스트해봤는데, 범위가 이탈하는 문제가 있었습니다.

```tsx
// 📍 src > app > page.tsx

export default function Home() {
	return (
		<main>
			⛳️
			asdfklasuhdflkjdsahjfklahsdljkfhkadsjhfkjldashlkfhadskjlhflkdashklfdahskjlhxfjklasdhfjkldhaskljfhkljsadhxflkjasdhlfkjadshkljxfhalksjdfkljashlkafhsadfds;alkjf;kldaslk;fadls;jflkjdsal;jf;ladsjkfjasd;ljfaldskjf;ladsjf;lkjas;ldfj;kladsjf;lasd;lfkjasdl;fjads;lfjlk;asdjf;lkasjdfjasjf;ajsd;
		</main>
	)
}

```

<img width="1469" alt="text-overflow" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/8accdaab-a951-4505-9edb-6e8d523d091c">

2024-06-05 11:03 UTC, keeprok commented
[⚡️ layout 부분 css변경](https://github.com/mobi-projects/nail-case-client/pull/12/commits/37f0a40bffb5c03c6f9daec28e4d22130e20a85d)
범위 이탈하는 문제 수정조치 하였습니다

2024-06-05 15:35 UTC, snkchan approved these changes
- 고생하셧습니다 다음작업 가즈아ㅏㅏㅏ
- 커밋전에 항상 주의해주세요 수정커밋은 사실 하나면 충분했을거같은데 4개나올라와서 만약 불필요한 커밋이였다면 커밋되돌리기로 하셧으면될거같은데 
- 불필요한 커밋3개를 더확인하기위해 다들 타고들어가서 봐야합니다.

2024-06-05 16:38 UTC, TransparentDeveloper approved these changes
고생하셨습니다:)

2024-06-06 01:29 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-06 10:42 UTC, merged