fetch : NTHoverCard 생성
mobi-projects/nail-case-client pull request #124
Opened 2024-07-02 15:22 UTC by keeprok

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

[📚 reservationDetailList type 추가](https://github.com/mobi-projects/nail-case-client/commit/93fc59a1b2869682a04b4015d89803ab765ca3a3)
- reservationData의 DetailList  type을 추가했습니다 

[🎨 wating-card 데이터 패칭](https://github.com/mobi-projects/nail-case-client/commit/44e2990a5f63419c9edc7102b6bee2620c2bbd70)
- fetchShopName 의 shopId는 1번으로 고정하였습니다 (manager의 layout 에서 받아와서 넣는과정으로 해야될것같습니다)
- witingCard - pending으로 confirmCard - confirm으로 정리 하였습니다
- WaitingDetailCard 이부분에서 [0]으로 고정하였는데 swipe 기능들어갈때 넣어주시면 될것같습니다 
<br/>

# 작업물
<img width="1157" alt="스크린샷 2024-07-02 오후 11 28 31" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/be3f7694-3187-4d5a-9cc0-8b7f789e2600">

<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-02 18:22 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-07-02 18:22 UTC, TransparentDeveloper commented on src/type/reservation.ts
> +}
# Request Level
  - [x] "🚧 재고해주시길.."


# Description
타입선언 컨벤션에 안맞습니다..

2024-07-02 18:22 UTC, TransparentDeveloper commented on src/util/common/tagList.ts
> +}
# Request Level
  - [x] "🚧 재고해주시길.."
  
  
# Description
`/src/type/union-option` 에 관련 타입이 있습니다.
그리고, option 끼리 묶어서 관리하는게 어떨까요??

```tsx
const TREATMENT_MAP: { [key in TNailTreatment]: string } = {
	AOM: "이달의 아트",
	CARE: "케어",
	ONE: "원 컬러",
	MEMBER_IMAGE: "사진등록",
}
const REMOVE_MAP: { [key in TRemoveOption]: string } = {
	"IN-SHOP": "자샵 제거 필요",
	"ELSE-WHERE": "타샵 제거 필요",
	"NO-NEED": "제거 필요 없음",
}
```

2024-07-02 19:13 UTC, keeprok commented on src/util/common/tagList.ts
> +}
/src/type/union-option 에있는건 알고잇는데 type으로만 선언되는곳이라 
따로 util 로 관리 하는게 맞다 판단하여 만들엇습니다 ption 끼리 묶어서 관리하는게 어떨까요 이거는 좋은 생각같네요

2024-07-02 19:14 UTC, keeprok commented on src/type/reservation.ts
> +}
이부분위 에있는거 바로 사용한건데 어떤부분이 안맞을까요?

2024-07-02 19:15 UTC, TransparentDeveloper commented on src/type/reservation.ts
> +}
컨벤션이 맞지 않습니다.

2024-07-02 19:24 UTC, snkchan commented on src/util/common/tagList.ts
> +}
ㄷㄷㄷ 역시 선장님;;; 좋은데요

2024-07-02 19:29 UTC, snkchan reviewed
- 리뷰남겼습니다.!

2024-07-02 19:29 UTC, snkchan commented on src/component/custom/manager/base/home/01/index.tsx
> +	)
- util > common > time.ts에 시간관련함수로 사용하면 관리하기 더편할것 같아요 
- time을사용하지않더라도 Math.floor( 시간 / 1000) 으로 하셔야 밀리sec => sec로 받기안전할것 같은데

2024-07-02 19:29 UTC, snkchan commented on src/component/custom/manager/base/home/01/index.tsx
> +	}, [pendingReservations])
- useEffect는 무엇을위해 존재하는건가요,,?

2024-07-02 22:09 UTC, keeprok commented on src/component/custom/manager/base/home/01/index.tsx
> +	)
전체적으로 시간관련해서는 reservation과 함께 수정 조치 하겠습니다

2024-07-02 22:09 UTC, keeprok commented on src/component/custom/manager/base/home/01/index.tsx
> +	}, [pendingReservations])
이부분은 전달해서 답변 달진 않겠습니다

2024-07-03 12:48 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-07-03 12:48 UTC, TransparentDeveloper commented on src/component/custom/manager/base/home/01/index.tsx
> +	}, [pendingReservations])
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


# Description
상태로 관리할 필요가 없을 것 같습니다.
부모에서 전달된 props가 변경되면 해당 컴포넌트는 자동으로 리랜더링되기 때문입니다.

2024-07-03 15:28 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-07-03 16:49 UTC, keeprok commented on src/component/custom/manager/base/home/01/index.tsx
> +	}, [pendingReservations])
@keeprok
[⚡️ useEffect 삭제](https://github.com/mobi-projects/nail-case-client/pull/124/commits/7253336fc4a97e79b3a91ba6f7fb121714fe22e4) 알려주셔서 감사합니다

2024-07-03 16:49 UTC, keeprok commented on src/util/common/tagList.ts
> +}
@keeprok
[⚡️tagList 목록화수정](https://github.com/mobi-projects/nail-case-client/pull/124/commits/c2019f9f50f4d404a9fe931f7970e4927ccccb1c) 수정하였습니다

2024-07-03 16:52 UTC, keeprok commented
# 수정하사항
flat() 이 사용자가 체감이될정도로 느리게 만든다고하여서 삭제하고 reduce로 변경하였습니다

2024-07-03 16:59 UTC, TransparentDeveloper requested changes

2024-07-03 16:59 UTC, TransparentDeveloper commented on src/util/common/tagList.ts
> +}
# Request Level
- [x] "🚨 꼭 수정해주세요.!"

# Description
`src > util > common` 은 유틸리티 함수 선언하는 폴더입니다...

2024-07-03 16:59 UTC, TransparentDeveloper commented on src/type/reservation.ts
> +}
# Request Level

  - [x] "🚧 재고해주시길.."


# Description
main branch 에 적용된 타입인데 왜 변경점이 잡힐까요??
pull 받았는지 다시 한번 더 확인해주세요!

2024-07-03 17:32 UTC, keeprok commented on src/util/common/tagList.ts
> +}
[⚡️tagList 위치 수정](https://github.com/mobi-projects/nail-case-client/pull/124/commits/1d29e3fbdbcd09a55b12e94d76c73e7a8b45dd04) 수정했습니다

2024-07-03 23:10 UTC, TransparentDeveloper requested changes

2024-07-03 23:10 UTC, TransparentDeveloper commented on src/constant/tagList.ts
tagList 는 왜 안데려오셨나요??

추가로 변경되지 않을 값이니, `as const` 사용해주셨으면 좋겠습니다.
`/src/type/union-option` 에 있는 타입을 사용하면, 조금 더 type-safety 해질 것 같아요.
타입 값이 변경되었을 때, 이 상수들도 변경되어야 한다고 경고로써 알려줄테니까요.

ex)
```tsx
export const conditionList: { [key: TNailCondition]: string } = {  // key 의 type 을 'string' -> `TNailCondition` 로 변경
	REPAIR: "손톱 보수 필요",
	AS: "A/S 필요",
	WOUND_CARE: "상처 있음",
	CORRECTION: "교정 필요",
}
```

2024-07-04 12:22 UTC, keeprok commented on src/constant/tagList.ts
[⚡️tagListtype 수정내용 맞춰서 수정](https://github.com/mobi-projects/nail-case-client/pull/124/commits/dd56a69d6cfd879e56409cef6ef09919a79ac82b)
- 수정!

2024-07-06 14:18 UTC, TransparentDeveloper approved these changes

2024-07-06 14:21 UTC, merged