design : schedule/this-week 데이터 fetch
mobi-projects/nail-case-client pull request #134
Opened 2024-07-03 18:33 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-162](https://nailcase.atlassian.net/browse/NAILCASE-162) 
* sub-issues:
  - [NAILCASE-225](https://nailcase.atlassian.net/browse/NAILCASE-225)

## 🎯 작업 내용

- [🎨 schedule/this-week 데이터 fetch](https://github.com/mobi-projects/nail-case-client/commit/e85d2504cb6d0b8bc5a50bbc9bc616f21fee1f34)
  - this-week 데이터 fetch 완료했습니다.
  - 현재 시간에 맞는 해당 주를 보여질 수 있도록 코드 수정했습니다.
  - 하루에 예약된 건수 추가 완료했습니다.
  - artist 정보가 현재는 없어서 `미지정`으로 처리했습니다.

## 📢 작업물
![녹음-2024-07-04-032838](https://github.com/mobi-projects/nail-case-client/assets/127207625/6bc81a05-93c5-4a31-949a-c1b58cd3b7a2)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-03 23:02 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-07-03 23:02 UTC, TransparentDeveloper commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +	return response.data
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
`/src/config/axios/instance.ts` 에 instance 만들어 두었습니다.
지금 access-token 도 따로 싣지 않은 거처럼 보여요. 
헤더에 토큰 싣거나 갱신하기 위해서라도 instance 사용해주세요.

2024-07-04 03:28 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +	return response.data
- [⚡️axios > axiosInstance 변경](https://github.com/mobi-projects/nail-case-client/commit/890ee6d4e1d104984396cb7715b2d42b716a4bfe)
넵..! 확인하고 수정 완료했습니다😄

2024-07-04 19:42 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"

2024-07-05 20:18 UTC, snkchan commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +			convertSecondTimestamp(thisWeekTimeRange.endTime.getTime()),
- 여기사용된 시간함수들은 모두 unix타임으로 반환하는 함수들이 존재하는데 그걸로 바꿔서적용하는것이 프로젝트를 전반적으로 유지하는데 더편하지 않을까요?

2024-07-06 14:54 UTC, keeprok approved these changes
lgtv

2024-07-06 14:54 UTC, keeprok commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
>  			{Array.from({ length: endHour - startHour }).map((_, i) => (
i ->idx 로 바꿔 주세요

2024-07-08 01:56 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
>  			{Array.from({ length: endHour - startHour }).map((_, i) => (
![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/80b76306-87fa-469a-9b68-b12b20a8c167)

해당 부분은 idx로 바꾸면 이중 `map` 때문에 아래 사진과 같이 랜더링되서 우선 `i`로 처리했습니다..!

![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/5df7762c-96c1-449b-86c2-144f2e8bb6fc)

2024-07-08 02:11 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +			convertSecondTimestamp(thisWeekTimeRange.endTime.getTime()),
- [⚡️불필요한 time 관련 코드 수정](https://github.com/mobi-projects/nail-case-client/commit/ace84f1f962587d887685c0582a5f1deb137a27e)
확인하고 수정 완료했습니다..!

2024-07-10 05:39 UTC, snkchan commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +	if (!data || !data.dataList) {
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->
  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description
- utils에 가보시면 type-guard.ts함수가 있습니다.
```ts
if(isUndefiend(data)) return <h1>아직 데이터가없네용...<h1>
```
이런식으로 사용하시면됩니다.

2024-07-10 05:39 UTC, snkchan commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
>  			)
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->


  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description
> schedule > layout > 01 > index.tsx가보시면 함수만들어두었습니다.

```ts

/**
 * @param data listReservation 예약정보
 * @param status 예약상태 5가지중 선택"CONFIRMED" | "REJECTED" | "CANCELED" | "PENDING" | "COMPLETED"
 * @returns 전체 예약정보중 status와 일치하는 예약정보 반환
 */
export const sortReservation = (
	data: TResponseData<TResGetListReservation[], "dataList"> | undefined,
	status: "CONFIRMED" | "REJECTED" | "CANCELED" | "PENDING" | "COMPLETED",
) => {
	if (isUndefined(data)) return []
	return data.dataList.reduce<TReservationDetailList[]>(
		(data, reservation) => {
			data.push(
				...reservation.reservationDetailList.filter(
					(detail) => detail.status === status,
				),
			)
			return data
		},

		[],
	)
}
```
사용방법도 pr에적어두었는데,,[참고](https://github.com/mobi-projects/nail-case-client/pull/140)

2024-07-10 08:58 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
> +	if (!data || !data.dataList) {
- [⚡️ 데이터가 undefined일때 코드 수정](https://github.com/mobi-projects/nail-case-client/commit/cd0dbed43d7910e29f8b9fe0d06d7a464c9af634)
수정 완료했습니다..!

2024-07-10 08:58 UTC, HeesikK commented on src/component/custom/manager/base/schedule/this-week/01/index.tsx
>  			)
- [⚡️ sortReservation으로 예약 데이터 필터링](https://github.com/mobi-projects/nail-case-client/commit/2a9d6d0191127d4692aaf3e22f6d12f9a776d884)
수정 완료했습니다..!

2024-07-11 15:29 UTC, snkchan approved these changes
- LGTM,,!

2024-07-11 15:30 UTC, merged