design : reservation confirm 페이지 퍼블리싱 & 데이터 fetch
mobi-projects/nail-case-client pull request #136
Opened 2024-07-04 05:24 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-225](https://nailcase.atlassian.net/browse/NAILCASE-225)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 reservation-confirm 페이지 퍼블리싱](https://github.com/mobi-projects/nail-case-client/commit/9fd852b37297d3e589abdf9d13f3498a51575922)
  - reservation-confirm 페이지 퍼블리싱 완료했습니다.

- [🎨 reservation-confirm 페이지 데이터 fetch](https://github.com/mobi-projects/nail-case-client/commit/675559077f1685c8e79e2028ecff5566724b74e1)
  - reservation-confirm 페이지 데이터 fetch 완료했습니다.
  - 데이터 fetch는 현재 날짜 기준 데이터를 전달 받아 status가 `confirm` 상태인 데이터의 첫 번째 값으로 fetch 했습니다.

## 📢 작업물

  ### figma 디자인
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/119a6b4d-5376-4740-b4cd-3a5347e77a1b)

  ### 작업 결과
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/2af5577d-3e8d-4403-a85e-4c251715ea79)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-04 15:22 UTC, keeprok requested changes
데이터 불러오는과정에서 다르게 생각해봐야할것같아요

2024-07-04 15:22 UTC, keeprok commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +		.filter((detail: TReservationDetailList) => detail.status === "CONFIRMED")
pending을 가져와야 하는거 아닐까요?

2024-07-04 15:22 UTC, keeprok commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +		.filter((detail: TReservationDetailList) => detail.status === "CONFIRMED")
또한 궁금한건 왜 이 코드가 필요한지 모르겠습니다 현재 이컴포넌튼에서필요한건 백엔드에서 viewReservation 이부분인거같은데당일 시작 시간과 끝시간 이 필요한것이아닌것같습니다 예약을 당일 만할수있는건 아닌것같은데 상점 id와 등록자의 id이 아닌가요?

2024-07-04 19:44 UTC, TransparentDeveloper requested changes

2024-07-04 19:44 UTC, TransparentDeveloper commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +				</div>
# Request Level
  - [x] "🚧 재고해주시길.."
# Description
이건 왜 필요한건가요??

2024-07-05 20:19 UTC, snkchan commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +	const response = await axiosInstance().get(``, {
get("") 이부분에 어떤  endpoint에서 호출하는지 적어주지않아도 data를 받아와지나요지금?

2024-07-07 06:15 UTC, HeesikK commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +	const response = await axiosInstance().get(``, {
넵..! 받아와지는거 확인했습니다

2024-07-07 10:16 UTC, HeesikK commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +				</div>
![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/3baea7da-4bd0-41bc-b47c-19eada2d4d63)

figma 상에서 사진이 등록된 부분이 있지만 당장 기능 구현은 못해서 우선적으로 퍼블리싱 단계에서 넣어놨습니다..!

2024-07-08 01:43 UTC, HeesikK commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +		.filter((detail: TReservationDetailList) => detail.status === "CONFIRMED")
제가 받은 백엔드 url에서는 해당 샵의 예약 내역을 받아올 수 있어서 우선적으로 샵의 id를 1로 고정하고 나온 예약 데이터로 fetch 진행하였습니다.

2024-07-09 06:43 UTC, keeprok requested changes

2024-07-09 06:43 UTC, keeprok commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +		.filter((detail: TReservationDetailList) => detail.status === "CONFIRMED")
해당 샵의 예약 목록 전부분을 다받아오지않나요?? 샵 id랑 startTime, endTime  을 보내면?? 지금 부분은 목록을 가져오는거라 불필요 할껏같네요 아마 예약관리 버튼에서 의 reservationID를 받아와서와viewReservation 을 통해 받아온 하나의 데이터가  필요할것같네요

2024-07-10 04:12 UTC, TransparentDeveloper requested changes

2024-07-10 04:12 UTC, TransparentDeveloper commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +}
`utils > api > reservation.ts` 폴더에, getListReservation() 함수 만들어뒀는데, 그거 활용해도 좋을 것 같습니다.

2024-07-10 04:12 UTC, TransparentDeveloper commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +					]}
# Request Level

  - [x] "🚧 재고해주시길.."


# Description

`type > union-option` 폴더에 보면 "네일 제거" 옵션에 대한 타입 정의되어 있습니다. 
그걸로 수정해주겠어요?

2024-07-10 04:12 UTC, TransparentDeveloper commented on src/app/(manager)/manager/sub/reservation-confirm/page.tsx
> +	}
# Request Level

  - [x] "🚧 재고해주시길.."


# Description
컴포넌트 안에 타입을 정의하셨는데, 특별한 이유가 있나요?

<br/>

\+ 추가로 null 타입을 부여한 속성이 있는데, 일단 사용하지 않는 속성은 굳이 정의하지 않아도 됩니다. 
받아봤자 null 일 게 예상이 된다면, 사용하지 않겠다고 전제한 게 아닐까요?

그리고 `option` 속성에 대한 타입이,,,, `TREATMENT_LIST` 객체의 key 중 하나인거죠? 
`type > union-option` 폴더 아래를 보시면 이미 정의된 타입이 있어요.
확인 후 수정해주시겠어요?

2024-07-11 15:53 UTC, closed without merging