feat :  '<' '>' 버튼 클릭시 기능 구현
mobi-projects/nail-case-client pull request #139
Opened 2024-07-05 23:11 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-231](https://nailcase.atlassian.net/browse/NAILCASE-231)
 sub-issues:
  - [NAILCASE-232](https://nailcase.atlassian.net/browse/NAILCASE-232)
<br/>
<br/>

## 🎯 작업 내용

- [✨ '<' '>' 버튼 클릭시 기능 구현](https://github.com/mobi-projects/nail-case-client/commit/16b71ebc428b02cb40e791e00a5777e9302876b0)
# [onClickDateTimeBtn]
> 우측상단의 "월별", "주별", "일별" 버튼 클릭시 event에대해 정의했습니다.
> 동작1 : 각 버튼 클릭시 context인 timeInfo를 현재시간으로 초기화 합니다.
> 동작2 : 해당 페이지로 이동합니다.

# [onClickPrev,Next Btn]

## 페이지별로 보여줘야할 text정보가 달라집니다.
> case 월별 : 2024 년 3월  ==> 클릭시 월별정보가 수정되면서 그에 따라서 연별 정도보 변합니다.
> case 주별 : 3월 1주차    ===> 주차수가 변하면서 그에 따라서 월별 정보도 변합니다.
> case 일별 : 3월 17일 (수요일) ==> 일자가 변하며 그에 따라서 월별, 요일 정보도 변합니다.

## 동작원리
> case 월별 : timeInfo의 day를 월 단위로 증감
> case 주별 : timeInfo의 day를 주 단위로 증감
> case 일별 : timeInfo의 day를 일 단위로 증감

![bandicam-2024-07-06-06-51-47-919](https://github.com/mobi-projects/nail-case-client/assets/144839872/1884378d-3da3-4f5c-a8c1-3841dc12d8a9)

# 배포오류
> pr을 분리하기위해 TimeInfoProvider가 적용안되채로 올려서 배포오류가 있습니다.
> pr을 받고 후에 충돌해결해서 merge하겠습니다.

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-06 14:13 UTC, TransparentDeveloper requested changes

2024-07-06 14:13 UTC, TransparentDeveloper commented on src/util/common/time.ts
> +}
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"


# Description
- 함수에 약간 오류가 있는 것 같습니다.
- [typescript-playground](https://www.typescriptlang.org/ko/play/?target=7#code/MYewdgzgLgBA5gUygdQQg1gOQK4FsBGCATjALwwAUAUAJACeCAhkQFwxh6FEA0tu4UABZsOBYrxoATRnRGdiZGAEZeASjliSpAHwwA3rVCRY0qAkVgEAdxgARRmYoNm3GPzBCYAWmWvpdVUNwaBgAMwBLImh7OgB5UIBZAUELazsHBCcmHjdk719lQJojEP941AxFCKioGPikj0EAOkRamQoikthq6Aay0NCIJEV+ivQyUnIABhgAfhgANhg2UbRxnyUg4zDI3vB+hs9ySxt7R1p6bIkad08N66UYAGpKAHZ8nqg+mXjBpFUJJ1giYZBBbOEBsQEGBgOZSBcKKYEC0kAAVcK4TKqD67L77H6JZIoqDozEdbEAekoSimtJgACpFjNGQtmTAAEwAFiB2ysaxwmkUCQczVh4QANojQeDIURobCYFTXtiXo8qLQ5VBsEQwDA+RgBVwqABfdVdGBmaCPcitMaG4gUdlTLncV7cBaBEogcXI8UgOAUABEXKaryaS0ABYuAFLHAD7jge4lqgSkCVHNifZilt-PkREdzs5rtd2NTwW9vv9QZDYfeMdj8fTKbTCGgAGZM0g7Tm8y63QAOYten1NP0B4Oc0NNXswQArY3WE82oC3G8CLQvOe2UNnNN2C26AJwD0tDkeV8dhvcwQAqa3PE9ygA) 여기서 테스트를 해보시면, 화요일에 주차가 변경됩니다.

<br/>
<br/>

--------

<br/>
<br/>

# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- 코드에 적힌 주석을 보고 글을 남깁니다. 
- `월요일`을 한 주의 시작으로 설정한 게 맞을까요? 
- figma 에서의 달력은 `일요일` 이 가장 앞에 등장하는데, 혼란을 줄이려면 `일요일` 을 한주의 시작으로 설정해야 하지 않을까 싶습니다.

<div align="center">

![calendar](https://github.com/mobi-projects/nail-case-client/assets/50646145/980af076-8b78-43ac-acc5-01997c50a6e1)

</div>

2024-07-06 14:45 UTC, keeprok requested changes
이기능이 되면 일정이 좀더 풍성해 질것같아요

2024-07-06 14:45 UTC, keeprok commented on src/component/custom/manager/base/schedule/layout/01/index.tsx
> +	const { setTimeInfo, timeInfo } = useTimeInfo()
그 vercel x되있길레 브랜치 들어가봤는데 이부분이 오류 나는것같습니다

2024-07-06 14:49 UTC, keeprok approved these changes

2024-07-07 02:40 UTC, snkchan commented on src/util/common/time.ts
> +}
- 헉 오류케이스가 존재하는군요... 빠르게 수정중입니다,!

2024-07-07 09:08 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-07-07 19:55 UTC, snkchan commented
# [N월 M주차 구하기] 코드 수정했습니다.!
- [getDateInfoInWeekPage](https://github.com/mobi-projects/nail-case-client/pull/139/commits/ee01b04601f6614607ebfa0e3525d8e2c24f114e)
## M주차의 정의는 ?
**검색을 통해 살펴보니 M주차라는 것의 정의는 다음과 같습니다.**
> 1주일은 (일~토)를 1주로 정의합니다.
> 해당일이 포함된 주차의 일수가 4일 이상인 경우에만 1주차로 계산합니다.
> ex) 6월1일 ==> 6월 1일이 포함된 주차에는 5월 26일 ~ 6월 1일입니다.  따라서 6월1일은 5월 5주차입니다.

## [getWeekNumber]설계
**앞에서 본것처럼 주차수를 계산하는 과정에는 예외 case가 두가지 존재합니다.** 
> 해당일이 월 초라면 => 4일 이상이 포함된 주차인지 확인 후 N-1월 M주차 출력
> 해당일이 월 말이라면 => 4일 이상이 포함된 주차인지 확인 후 N+1월 M주차 출력
> 따라서 월 초인경우 0반환, 월 말인 경우 -1반환, 그 외 정상적인 case는 1~5 반환

## [getDateInfoInWeekPage]설계
**예외 case발생시 월정보도 N-1 or N+1 을 해줘야합니다.**
>  getWeekNumber === 0  ==>   { weeklyMonth: month - 1, weekNumber: weekNumber } // month1감소 , 주차수 재계산
>  getWeekNumber === -1  ==> { weeklyMonth: month + 1, weekNumber: weekNumber } // month1증가 , 주차수 재계산
>  그 외  ==> return { weeklyMonth: month, weekNumber: weekNumber }

# 참고영상
![bandicam-2024-07-08-04-42-50-823](https://github.com/mobi-projects/nail-case-client/assets/144839872/b22f455c-c07c-47b5-a023-5fc6cd4ac656)

2024-07-07 20:42 UTC, TransparentDeveloper approved these changes

2024-07-07 20:45 UTC, merged