feat : useShopInfo 작성
mobi-projects/nail-case-client pull request #14
Opened 2024-06-05 18:17 UTC by TransparentDeveloper

## 🔥 Issues

- [➕ tanstack query](https://github.com/mobi-projects/nail-case-client/commit/aa84f5422f42ed82c6d1bf572374f83c2cbf6438)
  - tanstack-query, dev-tools  의존성 추가했습니다.
  
<br/>
<br/>

- [🏷️ 비지니스 로직 관련 타입 정의](https://github.com/mobi-projects/nail-case-client/commit/b4d67f96c0b9554b87be90bea7c70025de2bcd78)
  - `useShopInfo()` 는 매장 정보를 관리하는 훅입니다.
  - 매장 정보의 타입을 정의했습니다.

<br/>
<br/>

- [🔧 query client 설정](https://github.com/mobi-projects/nail-case-client/commit/07a50ba761fa9c95c121d449df870acef3642412)
  - tanstack query 는 ssr 이기 때문에 하나의 QueryClient 로 요청을 처리할 경우, 다른 사용자 간에 같은 QueryClient 를 공유하는 일이 있을 수 있다고 합니다.
  - 위의 이유로 server component 의 경우, 각 요청마다 다른 QueryClient를 생성해야 한다고 합니다.
  - client component 의 경우, 각 브라우저마다 js 번들을 다운받기 때문에 고유의 QueryClient를 갖을 수 있습니다. 
    - 모든 요청에  QueryClient 를 공유할 수 있습니다.
  - 해당 코드가 바로 이것입니다.
  
```tsx
// 📍src > config > tanstack-query > tanstack-query-provider.tsx

let browserQueryClient: QueryClient | undefined = undefined
const getQueryClient = () => {
	if (typeof window === "undefined") return createNewQueryClient() // 👈 호출한 환경이 브라우저가 아니라면 새로운 QueryClient 를 생성 후 반환
	else {
		if (!browserQueryClient) browserQueryClient = createNewQueryClient() // 👈 브라우저 환경인데, 최초 호출이라면, 새로 등록.!
		return browserQueryClient // 👈 브라우저 환경인데, 이미 등록된 개체가 있다면 재사용.!
	}
}

export default function TanstackQueryProvider({ children }: PropsWithChildren) {
	const queryClient = getQueryClient()
	return (
		<QueryClientProvider client={queryClient}>
			{children}
			<ReactQueryDevtools initialIsOpen={false} />
		</QueryClientProvider>
	)
}
```

<br/>
<br/>

- [✨ faker-js 패키지 추가](https://github.com/mobi-projects/nail-case-client/commit/682a0f17a7eb93d416a6fc57abef3367a72d719b)
  - mock 데이터 생성을 위해,   faker-js  패키지를 추가했습니다. (`npm i -D @faker-js/faker`)
  - `src > mock > create.ts` 파일에 mock 데이터 생성 코드를 작성해두었습니다.

<br/>
<br/>

- [✨ 네일숍 정보를 관리하는 hook 로직 구현](https://github.com/mobi-projects/nail-case-client/commit/d43685ce3daeedb91517aec424213163bf2e75a0)
  - backend 팀에서 실제 api 를 제공주기 전이라, 매장 정보와 관련하여 mock 데이터를 패칭받아 관리하는 hook 함수를 만들었습니다.

#### ⭐️중요!
- `useShopInfo` 를 포함&사용하는 컴포넌트는 client component 입니다. 
- 해당 hook 를 사용하더라도 server component 로 관리하는 방법을 알고 있지만, 일단은 위의 사항을 숙지해주시고 꼭 코드 상단에 "use client" 작성 바랍니다.!

<br/>
<br/>

## 🎯 작업 내용

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-06 15:57 UTC, snkchan approved these changes
- 엄청나네요;;;역시.... 공식문서도 확인했습니다. 몇가지 질문이있어서 리뷰남겼습니다.👍

2024-06-06 15:57 UTC, snkchan commented on src/config/tanstack-query/tanstack-query-provider.tsx
> +				refetchOnMount: true,
둘다 true로 설정하신 이유가있나요??
```ts
 refetchOnWindowFocus: true // window 창이 foucs될때마다 refatch
 refetchOnMount: true, // 마운트시마다 refatch
 // 두설정모두 데이터가 stale인 상태일때만 해당함
```
이렇게 이해했는데 질문입니다 ㅎㅎ

2024-06-06 15:57 UTC, snkchan commented on src/mook/create.ts
> +		endTime: createNTTime(),
- startTime, endTime 둘다 createNTTime()의 객체를 받고있는데 어떤목적으로 사용될예정인가요?

2024-06-06 15:57 UTC, snkchan commented on src/mook/fetch.ts
> +		}, 1000),
- 가상데이터라서 1초의 timeout을 설정하신건가요??

2024-06-06 18:50 UTC, TransparentDeveloper commented on src/config/tanstack-query/tanstack-query-provider.tsx
> +				refetchOnMount: true,
판단과 방법이 적절할지는 모르겠지만,, 저는 이렇게 생각했습니다.

비지니스 관점에서, 
예약 요청이 서버에 저장되었을 때 매장 측에서 이를 최대한 빠르게 인지할 수 있도록 refetch 를 자주 발생시키기 위함입니다.

2024-06-06 18:58 UTC, TransparentDeveloper commented on src/mook/create.ts
> +		endTime: createNTTime(),
말 그대로 운영 시간 중, 오픈&마감 시각입니다.
front 에서 관리하는 모든 시간은 TNTTime 형식으로 이뤄집니다.

2024-06-06 18:58 UTC, TransparentDeveloper commented on src/mook/fetch.ts
> +		}, 1000),
가상 데이터이긴 하지만 네트워크 딜레이가 있을 수 있음을 반영하려고 했습니다.

fallback ui 준비에 대한 것과 상기시킬 수 있고, 1초정도면 테스트 목적으로 불쾌하지 않은 수준이라고 생각했습니다.

2024-06-07 04:24 UTC, keeprok requested changes
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
faker까지... 수고하셨습니다

2024-06-07 04:24 UTC, keeprok commented on src/api/index.ts
> +export * from "./get"
폴더 util - api 아닌가요???

2024-06-07 04:26 UTC, keeprok commented on src/config/tanstack-query/tanstack-query-provider.tsx
> +				refetchOnMount: true,
refetch 를 자주 하는것이 예약이라는 경우에는 빠르게 인지 되어야 시간 이 안겹칠수있을 것같으니  맞는것같습니다

2024-06-07 11:32 UTC, TransparentDeveloper commented on src/api/index.ts
> +export * from "./get"
감사합니다.  👍👍
실수했습니다. 
노션 참고해서, util > api 폴더 아래로 함수파일 옮겼습니다.

- [🚚 fetching func 관리파일, 컨벤션에 맞춰 파일 이동](https://github.com/mobi-projects/nail-case-client/pull/14/commits/532f8ae5f856310f1c69e7945d31b7b27668501d)

2024-06-07 13:35 UTC, keeprok approved these changes

2024-06-07 16:55 UTC, HeesikK approved these changes
tanstack query를 왜 사용하는지 의아했는데 알 거 같네요..! 너무 고생하셨습니다.

2024-06-08 13:31 UTC, merged