feat : 뒤로가기 및 홈 버튼 클릭 시 라우팅 구현
mobi-projects/nail-case-client pull request #161
Opened 2024-07-13 01:14 UTC by HeesikK

## 🔥 Issues
* issue: [NAILCASE-248](https://nailcase.atlassian.net/browse/NAILCASE-248) 
* sub-issues:
  - [NAILCASE-312](https://nailcase.atlassian.net/browse/NAILCASE-312)

<br/>
<br/>

## 🎯 작업 내용

- [✨ 뒤로가기 및 홈 버튼 클릭 시 라우팅 구현](https://github.com/mobi-projects/nail-case-client/commit/37d52ae2e703ebac5abd34832db0fc39f9d6d08c)
  - shop 페이지에서 캐러셀에 홈 버튼 및 뒤로가기 버튼 시 라우팅을 구현하였습니다.
  - 뒤로가기 버튼은 검색 리스트 페이지가 없어 우선 홈 버튼으로 라우팅 될 수 있도록 구현 했습니다.

<br/>
<br/>

## 📢 작업물

![녹음-2024-07-13-101044](https://github.com/user-attachments/assets/0c26c59b-5a94-4b24-931b-1497fd1ea640)

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-13 10:09 UTC, keeprok approved these changes
- [x] "✅ LGTM"

2024-07-13 12:31 UTC, snkchan reviewed
- 고생하셧습니다 하나만 수정해주세요~

2024-07-13 12:31 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +		router.push("/")
"/" 말고 저희 constanst의 경로 상수화해둔걸로 적용부탁드립니다.

2024-07-13 13:13 UTC, TransparentDeveloper requested changes

2024-07-13 13:13 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/01/index.tsx
>  			/>
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
하나는 "뒤로가기" 아이콘이고 하나는 "홈" 아이콘인데, 둘 다 그냥 홈으로 보내도록 되어있네요.

지금은 이렇게 해도 문제 없겠지만 나중에 페이지가 늘어나서 매장 상세페이지로 유입될 경로가 많아졌을 때, 
"뒤로가기" 버튼 클릭 시, 기대치 못한 동작이 발생하지 않을까 싶어요.

수정 부탁드립니다.

2024-07-15 00:34 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
>  			/>
- [⚡️뒤로가기 버튼 클릭 시 라우팅 변경](https://github.com/mobi-projects/nail-case-client/commit/338e44dc98c6580d9c37cc51467568f5e292ddf0)
수정 완료했습니다..!

2024-07-15 00:34 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +		router.push("/")
수정 완료했습니다..!

2024-07-15 04:46 UTC, TransparentDeveloper approved these changes

2024-07-15 15:29 UTC, snkchan approved these changes
- LGTM....!

2024-07-15 17:03 UTC, merged