feat : scroll context 추가 및 캐러셀 리뷰 이동 구현
mobi-projects/nail-case-client pull request #162
Opened 2024-07-13 02:02 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-248](https://nailcase.atlassian.net/browse/NAILCASE-248) 
* sub-issues:
  - [NAILCASE-317](https://nailcase.atlassian.net/browse/NAILCASE-317)

<br/>
<br/>

## 🎯 작업 내용

- [✨ scroll context 추가 및 캐러셀 리뷰 이동 구현](https://github.com/mobi-projects/nail-case-client/commit/826b27ee3a2e25c0e2c88f67821fde53da7e6407)
  - 요구 사항에 맞게 캐러셀에 **리뷰 보러가기**를 클릭했을 때 `customNaviBar` 와 동일하게 리뷰로 스크롤이 이동할 수 있도록 구현하였습니다..
  - 사용자 샵 페이지 및 캐러셀에서 스크롤 이벤트가 동일하게 사용되어 `scroll context`를 추가하고 layout에 적용하였습니다.

<br/>
<br/>

## 📢 작업물

![녹음-2024-07-13-105656](https://github.com/user-attachments/assets/bbf2ce70-c24f-4fec-b4fb-f0fb5641834a)

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-13 10:17 UTC, keeprok requested changes
- [x] "🚧 재고해주시길.."

2024-07-13 10:17 UTC, keeprok commented on src/app/layout.tsx
> +					</ScrollProvider>
흠 ... 이렇게 하면 ScrollProvider가 manager page나 mainPage 를 사용할때도 사용된다는건데 불필요하지않을까요? 나중에 추가적으로 scroll부분이 생기면 성능 저하가 생길것같네요

2024-07-13 12:35 UTC, snkchan reviewed
- scroll provider가 최상단 layout에 있어야하나요혹시???
- 그렇지않다면 shop폴더아래 layout을생성하시고 provider적용하시는 편이좋을것 같은데요

2024-07-13 13:22 UTC, TransparentDeveloper requested changes
# Request Level
  - [x] "🚧 재고해주시길.."

# Description


리엘님 말씀에 동의합니다..

추가로 올려주신 영상을 보면 상단에서 'n 개 리뷰 >' 클릭한 직후, 
자동으로 리뷰섹션으로 스크롤 되는 건 좋지만
toolbar 는 "리뷰"를 가리키지 않는 것 같습니다.

수정해줄 수 있을까요?

2024-07-15 16:48 UTC, HeesikK commented
## 🎯 추가 작업 내용

- [⚡️ CustomerShopBanner 리뷰 클릭 시 focus 추가](https://github.com/mobi-projects/nail-case-client/commit/bb7fcdfbfa6a6485d26a7e8991f0c79efed4faf0)
  - CustomerShopBanner에서 리뷰 클릭 시 focus가 되도록 추가하였습니다.

![녹음-2024-07-16-014732](https://github.com/user-attachments/assets/f5799a11-3394-4c85-b902-d1fe741aed14)

2024-07-15 17:02 UTC, HeesikK commented on src/app/layout.tsx
> +					</ScrollProvider>
해당 부분 shop 하위 폴더에 layout.tsx 생성 후 ScrollContext 적용 완료했습니다.
기존 layout.tsx에 있던 ScrollContext는 제거 하였습니다.
- [⚡️ shop 폴더 layout 생성 및 ScrollContext 적용](https://github.com/mobi-projects/nail-case-client/commit/277a2e69dbb1485a5c180552502025a54b04e7ec)

2024-07-15 18:55 UTC, snkchan commented
- <img width="518" alt="image" src="https://github.com/user-attachments/assets/98cd8abc-e864-4767-b742-999efdf97450">

- 지라에서 확인했을때는 모든 task진행중 or 완료로 확인되는데 
- 현재 작업하신 페이지에서 달력과 , 예약시간 삭제하기로 했는데 어떤 pr에서 작업하실건가요,,,?
- 달력과 예약시간 삭제후 대체될 컴포넌트나 구조는 준비된게 있나요...?
- 저희 task마감기한이 지났는데 공유좀 부탁드립니다.

2024-07-16 09:59 UTC, keeprok approved these changes

2024-07-16 16:33 UTC, HeesikK commented
> * <img alt="image" width="518" src="https://private-user-images.githubusercontent.com/144839872/348822419-98cd8abc-e864-4767-b742-999efdf97450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDczNDAsIm5iZiI6MTcyMTE0NzA0MCwicGF0aCI6Ii8xNDQ4Mzk4NzIvMzQ4ODIyNDE5LTk4Y2Q4YWJjLWU4NjQtNDc2Ny1iNzQyLTk5OWVmZGY5NzQ1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNjI0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQzM2NiZmZlYjVlNTA5NGY5NmFiNGZhODdhYzQ2MzYxZmE5NGIxOTU3NWI5NGQ0MDI2OTAzZmQwZmQ5OGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1UE-cEXnp5uE3by2dg3xnZcqHnjWQFok5QFWmvafyMM">
> * 지라에서 확인했을때는 모든 task진행중 or 완료로 확인되는데
> * 현재 작업하신 페이지에서 달력과 , 예약시간 삭제하기로 했는데 어떤 pr에서 작업하실건가요,,,?
> * 달력과 예약시간 삭제후 대체될 컴포넌트나 구조는 준비된게 있나요...?
> * 저희 task마감기한이 지났는데 공유좀 부탁드립니다.

**달력 및 예약 시간 삭제는 [design : customer-shop-reservation ui 재설계](https://github.com/mobi-projects/nail-case-client/pull/176) pr에 수정하여 올렸습니다.**

월요일 회의에서 해당 ui 설계 관련해서 모카님과 상의하여 아래와 같이 결정하였습니다. 
- 달력 및 예약 시간 삭제
- 채팅하기 삭제 -> 채팅하기 페이지가 준비되어 있지 않아 이 부분은 우선 삭제 처리하였습니다.
- 예약하기 버튼의 사이즈를 w-full로 화면 전체에 나타날 수 있도록 수정
- 예약하기 버튼 ui를 toolBar 밑에 위치하도록 ui 변경

**수정된 ui**

![image](https://github.com/user-attachments/assets/86b625eb-304f-4bc3-a404-2830fd384fbc)

회의 내용 관련해서 끝나고 바로 공유 후 적용을 했어야 했는데 정말 죄송합니다.

2024-07-17 12:48 UTC, TransparentDeveloper approved these changes

2024-07-17 12:48 UTC, merged