feat : invalid shop 라우팅 구현
mobi-projects/nail-case-client pull request #163
Opened 2024-07-13 04:46 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-248](https://nailcase.atlassian.net/browse/NAILCASE-248) 
* sub-issues:
  - [NAILCASE-311](https://nailcase.atlassian.net/browse/NAILCASE-311)

<br/>
<br/>

## 🎯 작업 내용

- [✨ invalid shop 라우팅 구현](https://github.com/mobi-projects/nail-case-client/commit/826b27feb962aa555be125d51882428c2f9ddb1d5baf4e)
  - 유효하지 않은 shop 페이지에 라우팅 할 수 있는 문제를 해결했습니다.

<br/>
<br/>

## 📢 작업물

- 기존

  ![녹음-2024-07-13-133531](https://github.com/user-attachments/assets/7966eb5d-0939-4373-922f-d937766ccb03)

- 수정

  ![녹음-2024-07-13-134436](https://github.com/user-attachments/assets/c576b917-b188-4e9a-ab8f-4477378d8a4a)

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-13 10:20 UTC, keeprok approved these changes
- [x] "✅ LGTM"

2024-07-13 12:37 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
> +
- useState여야하는 이유가 있나요??? params가 dynamic router에서 넘어온 파라미터 아닌가요???

2024-07-13 13:39 UTC, TransparentDeveloper requested changes

2024-07-13 13:39 UTC, TransparentDeveloper commented on src/app/(customer)/shop/[shopId]/page.tsx
> +
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
이거는 ㅎㅎ 말이 안됩니다..

테스트 상황에서 1번 매장만 유효하다는 것을 알고 있기 때문에 지금처럼 해도 "잘 되는구나" 하겠지만,,,,
pr 제목에 맞는 기능을 구현했다고 하려면, 실제 서비스 상황에서도 동작하도록 코드를 작성해야 합니다.

실제 서비스 상황에서, 어떤 shop-id 가 유효한지 FE 는 절대 알 수가 없어요.
server 로 요청을 보내서 상태코드를 받아야, `등록된 매장`인지 `등록되지 않는 매장`인지를 알 수 있죠.
BE 팀과 얘기를 해서 해결해야할 문제입니다.


+ 추가로, 지금은 딱! `매장 페이지`의 접근만 막고 있어요..
`매장 페이지` 하위의 페이지 (예를들어 `/shop/3/reservation`..) 의 접근은 다 허용되지 않나요?
그 문제도 같이 고민을 해주셨으면 좋겠습니다.

2024-07-15 15:31 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
> +
> 추가로, 지금은 딱! 매장 페이지의 접근만 막고 있어요..
> 매장 페이지 하위의 페이지 (예를들어 /shop/3/reservation..) 의 접근은 다 허용되지 않나요?
> 그 문제도 같이 고민을 해주셨으면 좋겠습니다.

이 내용은 middeware설정으로 해결 됬으니 다른거 해결해주시기 바랍니다..1
@HeesikK

2024-07-17 02:40 UTC, HeesikK commented
## 🎯 추가 작업 내용

- [⚡️ 백엔드에 등록되지 않은 매장 접근 제한 추가](https://github.com/mobi-projects/nail-case-client/commit/380beb77ad3fb430d08bb145d6ec31f9ac97204f)
  - 현재 백엔드에 등록되어 있지 않은 매장에 대해 접근을 제한시켜 404 페이지로 **리다이렉트** 될 수 있도록 수정하였습니다.
  - 페이지를 불러올 때 로드중인 것을 사용자에게 알릴 수 있게 **Loading Spinner UI**를 추가하였습니다.

```javascript
const {data: shopInfo, error, isLoading,} = useShopInfo(convertStringToInteger(params.shopId)!)
```
위 코드를 통해서 **shopInfo**를 불러올 수 있습니다. 이때 데이터가 있으면 `SUCCESS`와 `샵 정보`를 반환하고 데이터가 없다면 `400`번 에러가 나오는 것을 확인할 수 있습니다.

위 코드를 사용하여 데이터를 받아오는데 성공했을 때는 **해당 샵**에 대한 페이지를 사용자에게 보여주고, 데이터를 받아오지 못했다면 **에러 페이지**를 보여주도록 설계하였습니다.

### 존재하는 샵 페이지에 접근(1번부터 6번까지)
![녹음-2024-07-17-112557](https://github.com/user-attachments/assets/9802c223-a5d3-4414-a292-8fd9c16bdc18)

### 존재하지 않는 샵 페이지에 접근(6번 이상부터)
![녹음-2024-07-17-112402](https://github.com/user-attachments/assets/d6e13f05-6c13-4892-a758-dd3da61e07ac)

2024-07-17 02:42 UTC, HeesikK commented on src/app/(customer)/shop/[shopId]/page.tsx
> +
- [⚡️ 백엔드에 등록되지 않은 매장 접근 제한 추가](https://github.com/mobi-projects/nail-case-client/commit/380beb77ad3fb430d08bb145d6ec31f9ac97204f)
해당 부분 삭제 처리하고 로직 다시 작성하여 추가하였습니다.

2024-07-17 02:44 UTC, HeesikK commented on src/app/(customer)/shop/[shopId]/page.tsx
> +
- [⚡️ 백엔드에 등록되지 않은 매장 접근 제한 추가](https://github.com/mobi-projects/nail-case-client/commit/380beb77ad3fb430d08bb145d6ec31f9ac97204f)
  - 해당 부분 수정 완료하였습니다..!
  - 현재 백엔드에 등록된 샵이면 정상적으로 샵 페이지를 보여주고, 등록되지 않은 샵이면 404 페이지를 보여주도록 추가 완료했습니다.
  - 자세한 설명은 아래 추가 작업 내용에 작성하였습니다..!

2024-07-17 12:48 UTC, TransparentDeveloper approved these changes

2024-07-17 12:48 UTC, merged