fetch : customer home
mobi-projects/nail-case-client pull request #164
Opened 2024-07-13 11:17 UTC by keeprok

## 🔥 Issues

* issue: [NAILCASE-247](https://nailcase.atlassian.net/browse/NAILCASE-247)
* sub-issues:
- [NAILCASE-251](https://nailcase.atlassian.net/browse/NAILCASE-251)
- [NAILCASE-250](https://nailcase.atlassian.net/browse/NAILCASE-250)
<br/>
<br/>

## 🎯 작업 내용

[📚 Image mock 데이터 추가](https://github.com/mobi-projects/nail-case-client/commit/cbb4a01adfae1f891055456afcc11abf64d11202)
- next.config.json형식에 맞는 데이터 사용했습니다
[🔧 MainPageData 및 useQuery 설정](https://github.com/mobi-projects/nail-case-client/commit/a99593c8896201fe620ab2d823728a934d9770ea)
- 현재 타입부분은 BE 팀에서 데이터 추가시 바로 수정될예정입니다
[✨ MainPageData fetching](https://github.com/mobi-projects/nail-case-client/commit/b755e6594243bcd4c88eb93e06280bc555396820)
- content  가 현재 패치 데이터에 없어서 몫데이터로 대채 하였습니다 (수정예정)
- image 또한 현재 픽스된게 없어서 몫데이터로 대체 하였습니다 
<br/>

# 작업물
<img width="1309" alt="스크린샷 2024-07-13 오후 8 05 23" src="https://github.com/user-attachments/assets/ac8d82aa-719b-43f7-a68b-edf2c673dd97">

<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-13 12:42 UTC, snkchan requested changes
- 리뷰달았습니다,!

2024-07-13 12:42 UTC, snkchan commented on src/util/api/get.ts
> +}
- 데이터 패칭에 실패했을때 case가 필요할것 같은데요??

2024-07-13 12:42 UTC, snkchan commented on src/type/mainPage.ts
-  mainPage (X)
- main-page (ㅇ)

> 컨밴션 확인좀요

2024-07-13 12:42 UTC, snkchan commented on src/component/custom/customer/home/03/index.tsx
> +					className={`absolute inset-0 rounded-[26px] bg-gradient-to-tr from-Black to-White opacity-0 transition-opacity duration-300 ${mockData.liked ? "group-hover:opacity-30" : "group-hover:opacity-60"
- cn funtion으로 처리하셔야할것 같은데요?? 후에 api요청에 의해 변환되어야하는데

2024-07-13 13:16 UTC, keeprok commented on src/type/mainPage.ts
[🔥 컨벤션 맞춰서 수정](https://github.com/mobi-projects/nail-case-client/pull/164/commits/f3a6a4f1ae895653b9382db24cc90b45c585042c)
- 수정했습니다

2024-07-13 13:17 UTC, keeprok commented on src/component/custom/customer/home/03/index.tsx
> +					className={`absolute inset-0 rounded-[26px] bg-gradient-to-tr from-Black to-White opacity-0 transition-opacity duration-300 ${mockData.liked ? "group-hover:opacity-30" : "group-hover:opacity-60"
api 요청 생기면 바꿀려고 합니다 바뀌는게 너무많아서

2024-07-13 13:17 UTC, keeprok commented on src/util/api/get.ts
> +}
[🎨 패칭 Error 시 디자인 추가](https://github.com/mobi-projects/nail-case-client/pull/164/commits/671dd8b39664756763f136eb69501a33f96d022a)
- 추가 하였습니다 
<img width="1191" alt="스크린샷 2024-07-13 오후 10 03 46" src="https://github.com/user-attachments/assets/cab455dc-907f-4dd9-bde6-6622e0b37889">

2024-07-13 14:05 UTC, TransparentDeveloper requested changes
리엘님,, 큰일났습니다.

pr 내용을 이해할 수가 없습니다..!
풀어서(?) 얘기해줄 수 있을까요???

<div align="center">

<img width="772" alt="no-idea" src="https://github.com/user-attachments/assets/33cfac64-8c9a-414a-95fe-d3156017cd11">

</div>

2024-07-13 14:05 UTC, TransparentDeveloper commented on src/app/(customer)/(home)/page.tsx
> +import { NTButton } from "@/component/common/atom/nt-button"
# Request Level
  - [x] "🚧 재고해주시길.."

# Description

솔직히 저도 그동안 신경안썼던 부분이긴 한데,, (저는 앞으로 꼭 주의할 겁니다.🔥)
같이 공유되었으면 좋겠어서 글 남겨요.!

클라이언트 컴포넌트는 최대한 하위에 둘 수록 좋다고해요..
`page.tsx` 에 (그것도 home 에) "use client" 붙이고 시작하는 건 재고를 해야할 것 같습니다.

우리가 일전에 정한 cci 구조에 안맞는 일있어도, 상태나 이벤트 관리가 (호출 구조 상) 최대한 아래 컴포넌트에서 이뤄질 수 있도록 수정해주실 수 있나요?

2024-07-13 20:32 UTC, keeprok commented
# 수정사항

2024-07-15 15:32 UTC, snkchan approved these changes
- LGTM..! 고생하셧습니다

2024-07-15 17:11 UTC, HeesikK approved these changes
# Request Level

  - [x] "✅ LGTM"

2024-07-15 18:05 UTC, closed without merging