fetch : toolBar 하위 섹션 디자인 수정 및 데이터 fetch
mobi-projects/nail-case-client pull request #167
Opened 2024-07-14 00:54 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-248](https://nailcase.atlassian.net/browse/NAILCASE-248) 
* sub-issues:
  - [NAILCASE-253](https://nailcase.atlassian.net/browse/NAILCASE-253)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 toolBar 하위 섹션 디자인 수정 및 데이터 fetch](https://github.com/mobi-projects/nail-case-client/commit/f8a75d4b6fe7dadba55db094a0d1753b80debfd0)
  - toolBar 하위 섹션 `공지`, `디자인`, `소식`, `리뷰` 데이터 fetch 완료했습니다.

<br/>
<br/>

## 📢 작업물
![녹음-2024-07-14-093653](https://github.com/user-attachments/assets/eb689943-416b-4099-81fc-c285a6e0c68e)

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-15 05:02 UTC, TransparentDeveloper requested changes

2024-07-15 05:02 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/05/03/index.tsx
> +}
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"


# Description
선언된 타입 이름이 컨벤션에 맞지 않습니다.
수정부탁드립니다.

2024-07-15 05:02 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/05/03/index.tsx
> +								{item.commentCount === null ? 0 : item.commentCount}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
선언하신 타입을 보니까, `commentCount` 는 number 형식만 받도록 되어있는데,
null 타입도 허용해야되는거 아닌가 싶습니다.

2024-07-15 06:42 UTC, HeesikK commented on src/component/custom/customer/shop/05/03/index.tsx
> +}
- [⚡️ 컨벤션에 맞게 타입 수정](https://github.com/mobi-projects/nail-case-client/commit/250d8f331141f388ce0bc8a52d30b5a50f0cd836)
수정했습니다..!

2024-07-15 07:34 UTC, HeesikK commented on src/component/custom/customer/shop/05/03/index.tsx
> +								{item.commentCount === null ? 0 : item.commentCount}
- [⚡️ commentCount null값 받을 수 있도록 수정](https://github.com/mobi-projects/nail-case-client/commit/26d806d3a9743211a97066f6da4a9fdbbbd465b3)
수정 완료했습니다..!

2024-07-15 15:35 UTC, snkchan requested changes
@HeesikK 
- pr본문 아래쪽에 내용을 확인해보니 **데이터가 없을때** 보여질 ui를 올려주신걸로 확인했습니다.

> 데이터가 없다 ===> 저장된 정보가 없다인데.
> 화면에 만들어주신 ui는 **데이터를 불러오는 중 오류가 발생했습니다**. 메세지를 보여주네요???
> 이건 맞지않는것 같은데.. 불러올 데이터가 없을 경우와 데이터 패칭과정중 오류가 생겼을때 ui를 분리해주셔야 할것 같은데요..
> 추가로 text색상을 red로하셧는데 저희 프로젝트에 red색상이 사용된 곳이 없어서 모카님께 질문해 보시는 것이 어떨까요???

2024-07-15 15:54 UTC, snkchan requested changes
- 고생하셧습니다..!  모달작업해주신 부분은 좋은데요???? 
> 디자인이 조금 아쉬운것 같아서 모카님께 한번 의견 받아보는것도 좋을것 같아요,,!

- 수정 요청사항이 조금 있는데 특히 axios파일을 건드신부분은 절대 올리시면 안되는 내용입니다,,! 주의해주세요. 대부분으 ㅣ컴포넌트에서 axios호출을 하는데 실제작업한 내용이아닌데 변경점을 만드셔서 올리시면 큰일납니다,,

2024-07-15 15:54 UTC, snkchan commented on src/component/custom/customer/shop/05/02/index.tsx
> +		queryFn: () => fetchMonthlyArt(shopId),
- useQuery로 데이터를 호출하는데 isError, isLoading or isPending인 경우에는 어떻게 처리할지 코드가 작성안되것 같은데 이부분도 같이 작성해 주셔야할것 같습니다.
```tsx
if(isError ) return </ErrorComponent> 이런식으로 성공실패 case를 모두 다뤄주셔야 할것 같아요
 
```

2024-07-15 15:54 UTC, snkchan commented on src/config/axios/instance.ts
> +				"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyMTAyMTg2OSwiZW1haWwiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsInNlcXVlbmNlSWQiOjEsImp0aSI6Ij
- 이런내용은 pr에서 빼주셔야합니다,,, 다른분들모두에게 변경점이 생겨요

2024-07-15 15:54 UTC, snkchan commented on src/component/custom/customer/shop/05/01/index.tsx
> +	}
- api호출 함수를 작성해주신것 같은데 저희  api요청에대해서 utill > api 폴더에서 관리하기로 했는데 위치를 옮겨주셔야 할것 같아요. 지금은 해당 컴포넌트에서만 함수가 쓰이지만 api호출 같은경우 어디서든 전역적으로 사용될 여지가 있지 않을까요???
- 그걸 위해서 한파일에서 관리하는데 api 폴더아래 관리할 파일 이름도 저희 정했었는데 맞춰서 만들어주시면 감사하겠습니다.

2024-07-15 15:54 UTC, snkchan commented on src/component/custom/customer/shop/05/01/index.tsx
> +		queryKey: ["shopNews", shopId],
- queryKey도 쿼리키를 따로 작성하는 폴더가 존재하는데.. 거기서 사용해주시겠어요?

2024-07-15 15:54 UTC, TransparentDeveloper requested changes
# Request Level
- [x] "🚨 꼭 수정해주세요.!"

# Description
공용컴포넌트로 모달 만들어 두었는데, 해당 페이지 관련해서 3개 모달을 각각 만들었네요.? 이유가 있을까요??

공용컴포넌트를 만드는 이유로, 이런 상황을 방지하려는 목적도 있을 것 같아요.
수정해주시길 바랍니다.

2024-07-15 16:02 UTC, keeprok reviewed
확인 햇주세요

2024-07-15 16:02 UTC, keeprok commented on src/component/custom/customer/shop/05/04/index.tsx
> +		options: string[] | undefined,
undefined 가 아니라 null 아닐까요?

2024-07-15 17:42 UTC, HeesikK commented on src/config/axios/instance.ts
> +				"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyMTAyMTg2OSwiZW1haWwiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsInNlcXVlbmNlSWQiOjEsImp0aSI6Ij
- 앞으로 주의하겠습니다..! 죄송합니다.

2024-07-15 17:43 UTC, HeesikK commented on src/component/custom/customer/shop/05/02/index.tsx
> +		queryFn: () => fetchMonthlyArt(shopId),
- [⚡️ 데이터가 없을때 및 isError일때 케이스 구분](https://github.com/mobi-projects/nail-case-client/commit/8a07fb444214f8d92e8de776eca13c84694c5d0e)
케이스 구분해서 작업 완료했습니다..!

2024-07-15 17:44 UTC, HeesikK commented on src/component/custom/customer/shop/05/01/index.tsx
> +		queryKey: ["shopNews", shopId],
- [⚡️ 쿼리키 추가 및 적용](https://github.com/mobi-projects/nail-case-client/commit/cdbe08a6f799b136c7ee33d31802b0ca251aee3d)
쿼리키 추가하고 수정 완료했습니다..!

2024-07-15 18:04 UTC, snkchan commented on src/config/axios/instance.ts
> +				"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyMTAyMTg2OSwiZW1haWwiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsInNlcXVlbmNlSWQiOjEsImp0aSI6Ij
- @HeesikK 
> 이 pr에서 변경점잡힌거 제거해주셔야해요 .. 제가올린 pr에서 instance작업을해서

2024-07-15 18:08 UTC, snkchan commented on src/component/custom/customer/shop/05/02/index.tsx
> +		queryFn: () => fetchMonthlyArt(shopId),
- @HeesikK  
- lodaing중일때도 추가해주셔야할것 같습니다. error케이스말고 현재 패칭중에 loding상태일때 사용자는 빈화면을 봐야합니다.
```tsx
if(isError) return <ErrorComp>
if(isPending) return <PendingComp>
```
이렇게 early return하면 더 가독성이 좋겟죠?

2024-07-15 18:41 UTC, HeesikK commented on src/config/axios/instance.ts
> +				"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyMTAyMTg2OSwiZW1haWwiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsInNlcXVlbmNlSWQiOjEsImp0aSI6Ij
변경점 잡힌 부분 제거 완료했습니다. 앞으로 주의하겠습니다..!

2024-07-15 18:56 UTC, HeesikK commented on src/component/custom/customer/shop/05/01/index.tsx
> +	}
- [🚚 fetch 함수 api 하위 폴더로 이동](https://github.com/mobi-projects/nail-case-client/commit/e189d2ed862e7f891d625caf68c548b031544964)
수정 완료했습니다..!

2024-07-15 18:57 UTC, HeesikK commented on src/component/custom/customer/shop/05/01/index.tsx
> +		queryKey: ["shopNews", shopId],
- [⚡️ 쿼리키 추가 및 적용](https://github.com/mobi-projects/nail-case-client/commit/50315d6c782d1323e0f2c8e50403655396145fe5)
수정 완료했습니다..!

2024-07-16 03:29 UTC, HeesikK commented on src/component/custom/customer/shop/05/02/index.tsx
> +		queryFn: () => fetchMonthlyArt(shopId),
- [⚡️ Not Found, isError, isPending 케이스 추가](https://github.com/mobi-projects/nail-case-client/commit/9f6ff92b20f00afeb6966a20f7ae9a9c9b6ac658)
  - 해당 케이스 추가하고 얼리 리턴 처리하였습니다..!

2024-07-16 03:33 UTC, HeesikK commented on src/component/custom/customer/shop/05/04/index.tsx
> +		options: string[] | undefined,
- [🏷️ option props로 넘겨받는 타입 수정](https://github.com/mobi-projects/nail-case-client/commit/c1b47f42d25f327a8aae158a00393e0773990899)
수정 완료했습니다..!

2024-07-16 04:17 UTC, HeesikK commented
> # Request Level
> * [x]  "🚨 꼭 수정해주세요.!"
> 
> # Description
> 공용컴포넌트로 모달 만들어 두었는데, 해당 페이지 관련해서 3개 모달을 각각 만들었네요.? 이유가 있을까요??
> 
> 공용컴포넌트를 만드는 이유로, 이런 상황을 방지하려는 목적도 있을 것 같아요. 수정해주시길 바랍니다.

- [⚡️ NTModal 적용하여 toolBar 하위 섹션 모달 수정](https://github.com/mobi-projects/nail-case-client/commit/91db4e49b929b3d585c161fecd13e03561f431ab)
작업해주신 NTModal 사용하여 코드 수정 완료했습니다👍
기존에 각 파일에 있던 Modal 코드는 삭제하였습니다..!

2024-07-16 10:00 UTC, keeprok approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"

# Description

2024-07-17 12:48 UTC, TransparentDeveloper approved these changes

2024-07-17 12:54 UTC, merged