design: NTButton 작성
mobi-projects/nail-case-client pull request #17
Opened 2024-06-07 16:29 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-42](https://nailcase.atlassian.net/browse/NAILCASE-42)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 NTButton 컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/65cc0477f721e3b925e3fbc38004f4b6da1b2cd5)
- button 공용 컴포넌트를 제작하였습니다.

- [🐛 EsLint 규칙에 따라 오류 수정](https://github.com/mobi-projects/nail-case-client/commit/2a09db059eabf26effc7cf19521246c0ef756c3f)
- github push 과정에서 EsLint 오류가 있어서 수정했습니다.

- [🎨 NTButton 스토리 작성](https://github.com/mobi-projects/nail-case-client/commit/6a3264007550fbdc24ff5955022a3a8634c89edf)
- button 스토리 작성 및 배포 완료했습니다.

- [⚡️ cn 함수 수정](https://github.com/mobi-projects/nail-case-client/commit/ae94ef38c2c428b628725115e5a616300653b3c4)
- cn 함수가 적용 안되는 문제 해결했습니다.
- 기존 cn 함수는 함수는 ClassValue 타입의 입력값을 받아 clsx로 결합하고, 그 결과를 twMerge를 통해 병합했습니다.
- 수정된 cn 함수는 extendTailwindMerge를 사용하여 twMerge를 확장하였습니다. customTwMerge는 기본 twMerge에 추가적인 클래스 그룹을 포함하도록 설정을 추가했습니다.

### [스토리북 배포링크](https://66588595839cce76dee2be9d-ihxcteqpcc.chromatic.com/)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-07 19:25 UTC, snkchan commented
- 병장님! 스토리북 링크에들어가보니 toggle-button이보이는데 혹시 잘못올라간걸까요?! button확인이안됩니다!

2024-06-08 13:35 UTC, TransparentDeveloper commented
병장님, Assignees 님 작업한 사람을 명시하는 곳이에요. 
병장님 본인만 설정해주시겠어요?? 🙂

<div align="center">

<img width="315" alt="스크린샷 2024-06-08 오후 10 32 58" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/10cb38a7-60fd-4811-a3d3-e804b9949bec">

</div>

2024-06-08 14:58 UTC, keeprok reviewed
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
 수고하셨습니다 스토리북 설정 이 어렵긴한거같아요

2024-06-08 14:58 UTC, keeprok commented on src/component/common/atom/nt-button/nt-button.stories.tsx
> +	title: "component/common/nt-button",
이부분에서 atom빠져서  잘못된부분이 story 로 보여지고 있는것같습니다

2024-06-08 14:59 UTC, keeprok requested changes
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
- 수고하셧습니다 스토리북 설정이어려운것같아여

2024-06-08 15:12 UTC, TransparentDeveloper commented
> # Request Level
> * [x]  "🚨 꼭 수정해주세요.!"
> 
> # Description
> 수고하셨습니다 스토리북 설정 이 어렵긴한거같아요

알겠습니다

2024-06-08 15:37 UTC, snkchan commented
- 연애말고 작업,,,!!!스토리북을 봐야 다음리뷰를 달수있을것 같아요,,!

2024-06-09 03:27 UTC, HeesikK commented on src/component/common/atom/nt-button/nt-button.stories.tsx
> +	title: "component/common/nt-button",
해당 부분 스토리북 배포링크를 잘못 붙여넣어서 발생한 오류 같습니다...

링크 수정해서 올렸으니 확인 부탁드릴게용😁

2024-06-09 03:28 UTC, HeesikK commented
> * 병장님! 스토리북 링크에들어가보니 toggle-button이보이는데 혹시 잘못올라간걸까요?! button확인이안됩니다!

스토리북 링크를 잘못 붙여넣어서 발생한 문제 같습니다. 수정해서 올렸으니 확인 부탁드려요..!

2024-06-09 05:40 UTC, TransparentDeveloper requested changes
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


# Description
- 아이콘이 없는 경우에 대해서도 작성을 해야할 것 같습니다. 🙃
- 지금 잡고 가지 않으면, 나중에 퍼블리싱할 때 지체될 것 같아요.

<div align="center">

<img width="174" alt="스크린샷 2024-06-09 오후 2 37 50" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/1154d46c-7137-4e87-8f21-f64ebfed43b3">

</div>

2024-06-09 07:07 UTC, HeesikK commented
> # Request Level
> * [x]  "🚨 꼭 수정해주세요.!"
> 
> # Description
> * 아이콘이 없는 경우에 대해서도 작성을 해야할 것 같습니다. 🙃
> * 지금 잡고 가지 않으면, 나중에 퍼블리싱할 때 지체될 것 같아요.
> 
> <img alt="스크린샷 2024-06-09 오후 2 37 50" width="174" src="https://private-user-images.githubusercontent.com/50646145/337950554-1154d46c-7137-4e87-8f21-f64ebfed43b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTYzMTIsIm5iZiI6MTcxNzkxNjAxMiwicGF0aCI6Ii81MDY0NjE0NS8zMzc5NTA1NTQtMTE1NGQ0NmMtNzEzNy00ZTg3LThmMjEtZjY0ZWJmZWQ0M2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA2NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MGU5MDEwZjE4ZDRhMWYyZjMxOTRhOGMzNjA5NDA0ODliMjZiZWQ1OTU4YWYzMGQyMzA4ZTBlNmUyZTc5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oKDrF9hY-2eELqeB1gVGuTadLsSDvkF8mIircA6ffzQ">

# 수정사항

- [⚡️ 아이콘이 없는 NTButton 스토리 추가](https://github.com/mobi-projects/nail-case-client/commit/c69db68ed85fc7d84def5bef7ab5dde647b39ecd)

  - NTButton에서 icon값을 optional로 받고 있어서 NTButton을 사용할때 icon값을 넘겨주지 않으면 아이콘이 없는 버튼을 사용할 수 있습니다. 
  - 아이콘이 없는 버튼도 스토리북에 추가 완료했습니다. 아래 사진처럼 icon에 있는 undefined를 선택하면 아이콘이 없는 NTButton 컴포넌트를 스토리북에서 확인할 수 있게 수정했습니다.
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/29540c06-db96-4091-bcc2-d43f82e0da86)

2024-06-09 11:10 UTC, TransparentDeveloper approved these changes

2024-06-09 14:45 UTC, snkchan reviewed
- 고생하셧습니다..!굉장한데요??? review확인해주세요~~

2024-06-09 14:45 UTC, snkchan commented on src/component/common/atom/nt-button/index.tsx
> +export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> &
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description
- Riel님이 다른곳에 남겨주신것처럼 컨밴션에 맞춰서 Props => PT로 수정부탁드립니다!

2024-06-09 14:45 UTC, snkchan commented on src/config/tailwind/util.ts
> +	},
굉장한데요?? tailwind 마스터인가요?👍👍

2024-06-09 14:45 UTC, snkchan commented on src/component/common/atom/nt-button/index.tsx
> +	disabled = true,
- 기본값을 disabled로 설정하신 이유가 궁굼합니다.!

2024-06-09 14:57 UTC, HeesikK commented on src/component/common/atom/nt-button/index.tsx
> +export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> &
수정 완료했습니다..! 확인 부탁드릴게용~

- [🏷️ 컨벤션에 맞게 타입 수정](https://github.com/mobi-projects/nail-case-client/commit/946a518b0e777b70719224a2e4510806d2610f50)

2024-06-09 14:57 UTC, HeesikK commented on src/config/tailwind/util.ts
> +	},
젶님 최고👍👍

2024-06-09 14:58 UTC, HeesikK commented on src/component/common/atom/nt-button/index.tsx
> +	disabled = true,
초기에는 false 상태였는데 작업하다 disabled를 true로 상태로 놓고 커밋한거 같습니다..! 
추후에 작업할 때 수정해서 진행하면 될 거 같습니당..!

2024-06-09 15:45 UTC, snkchan commented on src/component/common/atom/nt-button/index.tsx
> +	disabled = true,
- 해당 내용은 위에 컨밴션맞춰서 수정 ! 한부분에같이 포함시켜서 작업해주셧으면 더 좋을것 같아요.
- 해당컴포넌트를 사용하는 팀원이 이유를 모르고 왜 disabled지? 하는 의문이 남을수도있어서... 팀원들과 공유가안된내용이라면 반영해주셧으면 좋았을탠데 앞으로는 그렇게 작업하는 방향으로 해주셧으면 좋겠습니다.!

2024-06-10 07:15 UTC, keeprok approved these changes

2024-06-10 11:06 UTC, snkchan approved these changes
LGTM...!!

2024-06-10 13:01 UTC, merged