fetch : CustomerShopBanner 데이터 fetch
mobi-projects/nail-case-client pull request #172
Opened 2024-07-15 14:48 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-248](https://nailcase.atlassian.net/browse/NAILCASE-248) 
* sub-issues:
  - [NAILCASE-253](https://nailcase.atlassian.net/browse/NAILCASE-253)

<br/>
<br/>

## 🎯 작업 내용

- [✨ CustomerShopBanner 데이터 fetch](https://github.com/mobi-projects/nail-case-client/commit/68db75d9c5d484822cc8d97b207bffd7b9de366f)
  - CustomerShopBanner 데이터 fetch 완료했습니다.

<br/>
<br/>

## 📢 작업물
![녹음-2024-07-15-233528](https://github.com/user-attachments/assets/c51ee592-9492-46b6-b1f6-689f85e09995)

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-15 16:22 UTC, keeprok reviewed
수고 하셨습니다

2024-07-15 16:22 UTC, keeprok commented on src/component/custom/customer/shop/01/index.tsx
> +				✨ {nailShopInfo.overview}
✨ 이거는 고정 되는건가요?? 저부분도 삭제 해주세요

2024-07-15 16:22 UTC, keeprok commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
이부분은 api 요청을 받아서 넣는게 좋아보이네요

2024-07-15 18:50 UTC, snkchan requested changes
- 고생하셧습니다...
- 저희 team rule이 정해진것들이 있는데 적용이안됬습니다..

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +	if (isUndefined(shopReviews)) return <h1>데이터 없음</h1>
- 해당 부분은 isUndefiend일때 return을 하는것이아니라 isError or isPending일때 ui를 보여줘라 ! 라고 작성하는것이 맞지않을까요?

- 또한 지금 데이터가 없다면 테이터 없음 이라고 보여지는데 데이터가없을 경우 ui도 작업해주셔야합니다..
- `데이터 없음` text가보여지면서 기존 데이터가 있을때와는 다르게 layout이 변경되는데요 이부분도 해결해주셔야합니다.

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +		enabled: shopId !== null,
endabled옵션은 어떤것인가요??

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +	}
- 앞선 리뷰와 마찬가지로 api호출 함수의 이름을 어떻게하자, 어디서관리하자도 저의 정하고 시작했던것 같습니다만,,

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +	}, [pathname])
- 이건 pathname에서 받아오는게 맞나요? 
- 저희 폴더구조를 보시면 shop > [shopId]입니다. dynamic router를 사용해서 shopId 넘버를 받아오는데 
- 해당 shopId넘버는 컴포넌트에 파라미터로 전달됩니다. 거기서 받아서 사용하시는게 맞을것 같아요
```tsx
 CustomerShopBanner({params}:{params:{shopId:number}} )
 prarams.shopId // console.log(params.shop) === 1 이런식으로 사용하셔야합니다
 ```

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
- 태그에 관해서도 백엔드에서 mock데이터를 넘겨받지 않나요?

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +		enabled: shopId !== null,
- query함수들도 모두 hook에서 관리하고있는데 여기서 작성할 필요가 있을까요?

2024-07-15 18:50 UTC, snkchan commented on src/component/custom/customer/shop/01/index.tsx
> +}
- type도 타입폴터가 존재합니다.

2024-07-16 04:50 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +	}
- [🚚 fetch 관련 함수 api 하위 폴더로 이동](https://github.com/mobi-projects/nail-case-client/commit/1d2907208bc08939f3114aed2818c78ade3b2633)
수정 완료했습니다..!

2024-07-16 05:10 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +		enabled: shopId !== null,
- [⚡️ query 함수 훅으로 분리](https://github.com/mobi-projects/nail-case-client/commit/ebc3d21c629ecc39e7066bc3ccee65c3e121bdcb)
query 관련된 함수 hooks로 분리해서 적용하였습니다..!

2024-07-16 05:11 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +		enabled: shopId !== null,
해당 옵션 처음에 작업할 때 오류가 나서 추가했는데, 코드 수정후에 오류가 발생 안해서 제거 했습니다..!

2024-07-16 05:30 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +	}, [pathname])
- [⚡️shopId 받아오는 방법 수정](https://github.com/mobi-projects/nail-case-client/commit/a54bf346c3c6f5dbb64436ebce1f9eb19994bdf7)
 dynamic router를 사용해서 shopId를 받아올 수 있도록 코드 수정 완료했습니다..!

2024-07-16 05:36 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +				✨ {nailShopInfo.overview}
- [🔥 불필요한 코드 삭제](https://github.com/mobi-projects/nail-case-client/commit/1c362c1745930686b6c2a34b5d1666ec449ccc81)
삭제 완료했습니다..!

2024-07-16 05:36 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
해당 부분 백엔드에 데이터 요청했습니다. 수정 후 다시  commit 하겠습니다..!

2024-07-16 05:36 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
해당 부분 백엔드에 데이터 요청했습니다. 수정 후 다시  commit 하겠습니다..!

2024-07-16 05:42 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +}
- [🚚 컴포넌트에 정의된 타입 type 폴더로 이동](https://github.com/mobi-projects/nail-case-client/commit/ade895d14eef1cd97db7b9d8313db96b7c5a04cc)
type 폴더로 옮겨서 적용했습니다..!

2024-07-16 06:33 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
> +	if (isUndefined(shopReviews)) return <h1>데이터 없음</h1>
- [⚡️ Not Found, isError, isPending 케이스 추가](https://github.com/mobi-projects/nail-case-client/commit/9e51debf64aa4be833c33fef6c52500c196b6de7)
  - 우선 각각 컴포넌트 생성해서 추가 하였습니다.
  - Not Found와 isError는 `text`로 사용자에게 알려주고 isPending은 `로딩 스피너`를 추가하려고 하는데 어떤지 의견 여쭙고 싶습니다..!

2024-07-16 14:06 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
- [⚡️starRating 및 tags 데이터 fetch 추가](https://github.com/mobi-projects/nail-case-client/commit/ac70aca1c43d854a33a2e698e32f6f9aef633167)
해당 부분 데이터 요청 받아 fetch 완료했습니다.

2024-07-16 14:06 UTC, HeesikK commented on src/component/custom/customer/shop/01/index.tsx
>  					#네일맛집 #주차가능 #오마카세아트
- [⚡️starRating 및 tags 데이터 fetch 추가](https://github.com/mobi-projects/nail-case-client/commit/ac70aca1c43d854a33a2e698e32f6f9aef633167)
해당 부분 데이터 요청 받아 fetch 완료했습니다.

2024-07-17 12:50 UTC, snkchan approved these changes

2024-07-17 12:54 UTC, TransparentDeveloper approved these changes

2024-07-17 13:43 UTC, merged