fetch : customer home page
mobi-projects/nail-case-client pull request #174
Opened 2024-07-15 20:42 UTC by keeprok

## 🔥 Issues
* issue: [NAILCASE-251](https://nailcase.atlassian.net/browse/NAILCASE-251)
* sub-issues:
- [NAILCASE-347](https://nailcase.atlassian.net/browse/NAILCASE-347)
- [NAILCASE-260](https://nailcase.atlassian.net/browse/NAILCASE-260)

<br/>
<br/>

## 🎯 작업 내용

#  시작에 앞서
- 일단 pr은 앞으로 분기를 조금더 자세히 나눠서 올리도록 하겠습니다 한꺼번에 commit을 올리려고 하니 저또한 정리 하기 힘들고 보기 힘드실것같네요 이전 closed했던 부분은 제외하고 작성하도록 하겠습니다 
# [이전 closed된 pr 작업 입니다 ](https://github.com/mobi-projects/nail-case-client/pull/164)

<img width="1430" alt="스크린샷 2024-07-14 오전 5 33 15" src="https://github.com/user-attachments/assets/31e6930e-e695-4583-b902-deaab2a3b58f"> 
 
[⚡️api 변경된 데이터 적용](https://github.com/mobi-projects/nail-case-client/commit/bd4e9c42e0ea7213800f0f7fc7bc074f851e4d16)

-  하트 삭제 하였습니다 
-  페이지 이동 추가 하였습니다 

https://github.com/user-attachments/assets/fff90376-2ec6-4e8d-8784-730f78c377db

### api 관련
-  memberId 가 삭제 되었습니다 
- shopName => name으로 변경되었습니다 
- image 가 준비 되지않아 몫데이터 준비하였습니다

[🎨 usageForm 패칭](https://github.com/mobi-projects/nail-case-client/pull/164/commits/02b1f5118bb803bb87866af0d695ac7523a45a84)
-  만약 지난 예약 또는 현재 예약이  없을경우 ui는 현재는 글자로 보여지도록 하였습니다 (PR다시올릴예정)
- 시간은  endTime이 없을시 시작 시간만 보여지도록  있을경우 ~endTime 이 나오게 설정하였습니다

###   최대 개수
- 진행중 네일의 사진은  최대 5개 보여지도록 설정하였습니다
- 지난 네일의 최대 3개의 이미지가 보여지도록 하였습니다 
- 예약정보중 태그의 경우 최대 4개 까지만 오도록 설정하였습니다 
 

<img width="1452" alt="스크린샷 2024-07-16 오전 5 11 25" src="https://github.com/user-attachments/assets/9cd0fd29-ddc6-4da7-ae3b-b041cd025fd4">

[⚡️ 예약 취소 기능](https://github.com/mobi-projects/nail-case-client/pull/164/commits/55f2fb767f8c0a8850a0ee795a02e17933afd767)
-  예약 취소 클릭시 재확인 받는 toast를 설정하였습니다
- toast를 통해 예약 취소시  실패또는 성공을  toast를 통해 확인 이 가능하게 만들었습니다
-  예약 실패 성공 시 2초 후에 페이지 새로고침이 되게하였습니다  
<img width="350" alt="스크린샷 2024-07-16 오전 5 22 37" src="https://github.com/user-attachments/assets/7e2c9e14-6b17-4c4b-a65c-bf36bb7b3402">

https://github.com/user-attachments/assets/fc8d4a1a-15c5-439e-86b6-1a8748f20a21

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-16 11:00 UTC, snkchan reviewed
- 고생하셧습니다,,,!

2024-07-16 11:00 UTC, snkchan commented on src/app/(customer)/(home)/page.tsx
> +	const { data: responseData, isError } = useGetMainPageDataQuery()
- isLoading일때는...? 로딩중에 어떻게보여지나요?

2024-07-16 11:00 UTC, snkchan commented on src/component/custom/customer/home/02/index.tsx
> +		return image.flatMap((detail) => detail)
- 오잉 flatMap은 왜사용되는건가요?

2024-07-16 11:00 UTC, snkchan commented on src/component/custom/customer/home/02/index.tsx
> +	console.log(recentReservation)
콘솔은어째서??

2024-07-16 15:04 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +	console.log(recentReservation)
아 죄송합니다 삭제 하였습니다

2024-07-16 15:05 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +		return image.flatMap((detail) => detail)
이부분은 몫데이터를 제가 저렇게 쓰게 만들어서 ㅋㅋㅋㅋ

2024-07-16 15:05 UTC, keeprok commented on src/app/(customer)/(home)/page.tsx
> +	const { data: responseData, isError } = useGetMainPageDataQuery()
로딩중일때는 reservation 같은 경우는 대채 이미지를 사용해서 불필요 하다 생각 햇는데 추 가 하겠습니다

2024-07-16 16:52 UTC, TransparentDeveloper requested changes

2024-07-16 16:52 UTC, TransparentDeveloper commented on src/component/custom/customer/home/02/index.tsx
> +import { toast, Toaster } from "sonner"
# Request Level
  - [x] "🚧 재고해주시길.."


# Description

이전에 만들었던 공용컴포넌트, nt-toast  는 왜 사용하지 않으셨나요?
영상보니까 우리가 설정해놨던 디자인 시스템 적용이 아예 안된 것 같은데, 통일성이 떨어지지 않을까요?

모카님한테도 공유가 되었을까요??

2024-07-16 16:52 UTC, TransparentDeveloper commented on src/component/custom/customer/home/02/index.tsx
> +		}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
> 예약 실패 성공 시 2초 후에 페이지 새로고침이 되게하였습니다

예약 실패 시에는 새로고침이 적용되지 않는 것 같습니다.

추가로 페이지를 완전히 새로고침 하는 것보다, 해당 ui 만 수정하도록 할 수 있지 않을까요?

2024-07-16 17:23 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +		}
실패 시에는 새로고침이 필요없지않나요??
또한 현재 api 가 main전체 데이터를 한번에 주기때문에 해당ui만 수정하게 하는건 어렵습니다

2024-07-16 17:26 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +import { toast, Toaster } from "sonner"
해당 nt-toast를 사용하게 되면 위치 를 고정을 해두어서 위치 조정을 못하게 하였습니다 또한 공용 컴포넌트 인지라 조정을 못하엿네요 
모카님에게는 전달 을 못한 부분인것같습니다  바로 전달 하도록 하겠습니다

2024-07-16 18:14 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +	console.log(recentReservation)
[🔥 불필요한 부분 삭제](https://github.com/mobi-projects/nail-case-client/pull/174/commits/963226acae3e284fc67afb2624f9616ee23804a5)

2024-07-16 18:15 UTC, keeprok commented on src/component/custom/customer/home/02/index.tsx
> +		return image.flatMap((detail) => detail)
[🔥 불필요한 부분 삭제](https://github.com/mobi-projects/nail-case-client/pull/174/commits/963226acae3e284fc67afb2624f9616ee23804a5)

2024-07-16 18:16 UTC, keeprok commented on src/app/(customer)/(home)/page.tsx
> +	const { data: responseData, isError } = useGetMainPageDataQuery()
로딩중일때는 현재 각 부분 마다 데이터 가없을때가 준비 되잇어서 따로 loading은 만들지 않았습니다

2024-07-16 21:25 UTC, keeprok commented
# 수정사항 
[🎨 ReservationForm 디자인 변경하였습니다](https://github.com/mobi-projects/nail-case-client/pull/174/commits/c70c8847de65d0704680f8a42d59afafd6898a6d)
- 지난 예약 및 현재 예약 현황 의 데이터 가 없을때를 대비 해서 ui 및 기능을 작성하엿습니다 
<img width="1319" alt="스크린샷 2024-07-17 오전 5 19 00" src="https://github.com/user-attachments/assets/a5b09bcf-34a8-4a07-adc4-0e5ef775592d">
<img width="1260" alt="스크린샷 2024-07-17 오전 6 24 25" src="https://github.com/user-attachments/assets/d9fdb9ef-352c-4a83-a2d5-eff3e88a4990">

2024-07-17 13:15 UTC, TransparentDeveloper approved these changes

2024-07-17 13:16 UTC, merged