feat : 카카오 profile image 불러오기
mobi-projects/nail-case-client pull request #181
Opened 2024-07-17 16:36 UTC by snkchan

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

# [profileImgUrl]
- [🏷️ 로그인 요청시 type추가 & 외부 이미지 경로 추가](https://github.com/mobi-projects/nail-case-client/commit/c3b12ae6b190db04be4b9b4653a488a198bdcae9)

> 카카오 디벨로퍼스에서 로그인시 카카오프로필 데이터를 불러오도록 설정변경했습니다.
> 로그인후 백엔드에서 profileImgUrl을 넘겨받습니다.

# [카카오 프로필 불러오기]
- [✨ 로그인후 카카오 profile image 불러오기](https://github.com/mobi-projects/nail-case-client/commit/8e3fd687b719b0374fa4511885209367f05ea5db)

## [확인사항]

> 현재 백엔드에서  userInfo를 받아오는 endpoint가 없습니다..
> 그래서 임시로 로그인후 cookie에 url을저장해서 프로필 이미지를 보여주도록 했습니다.
> 데모후에 유저정보를 받아오는 api가 생성되면 코드를 수정해야 할 것 같습니다 

##  [결과물]
<div align="center">

![bandicam-2024-07-18-01-26-17-035](https://github.com/user-attachments/assets/bb22ff6b-5c10-4c40-9f18-26c1e367bb42)

</div>

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-17 16:47 UTC, keeprok approved these changes
수고하셨습니다

2024-07-18 02:18 UTC, HeesikK approved these changes
# Request Level
  - [x] "✅ LGTM"

2024-07-20 07:02 UTC, TransparentDeveloper requested changes
고생하셨습니다.!

2024-07-20 07:02 UTC, TransparentDeveloper commented on src/hook/use-auth-controller.ts
> +			})
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
질문이 있습니다.
프로필 이미지 url 도 쿠키로 저장해야 하는 이유가 있을까요?

2024-07-20 07:02 UTC, TransparentDeveloper commented on src/component/custom/customer/home/00/index.tsx
> +
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
등록된 프로필 이미지 가 없을 경우 "대체 이미지 출력" 에 대한 내용도,
해당 pr 에서 다루면 좋을 것 같습니다.

2024-07-20 16:28 UTC, snkchan commented on src/hook/use-auth-controller.ts
> +			})
- 좋은 질문입니다,,,!

> 우선 해당pr이 올라온 시점을 생각해봐야하는데요.... 데모데이에 보여지기 위해서 빠르게 기능을 구현해서 올리게되었습니다.
> profile image 작업을 하면서 한가지 문제점이 발생했습니다...  놀랍게도 저희 api중에 사용자정보를 받아오는 api요청이 없더라구요... 그래서 급하게 쿠키에 저장해서 구현을 해버렸습니다...
> 이부분은 woody님께 말씀드려놨는데 저희 사용자정보를 받아오는 api endpoint가 필요할것 같습니다.
> 사용자 정보 이름,나이,번호, 프로필이미지, 사장님이라면 shopId등을 한번에 받아올 요청이 있어야할것 같습니다.

2024-07-20 16:39 UTC, snkchan commented on src/component/custom/customer/home/00/index.tsx
> +
- 후딱 작업해서 올리겠습니다

2024-07-20 17:46 UTC, snkchan commented on src/component/custom/customer/home/00/index.tsx
> +
### [kakao default profile image 사용]

- [⚡️ 정규식을 사용해서 외부 이미지 경로 수정](https://github.com/mobi-projects/nail-case-client/pull/181/commits/8508d52e2bfe47fe15d17f03ad1d8888db310491)


<div align="center">

![image](https://github.com/user-attachments/assets/d6dc9aa3-ed7f-4f90-8272-116f26990ff8)

> 카카오에서 profile image를 등록하지 않은사용자가 로그인했을때.

</div>

> 카카오 profile을 등록하지 않은 사용자의 경우 카카오 default image가 넘어오는것을 확인했습니다.

> 사진을 등록한 user의 profileUrl = k1.kakaocdn.net ~~~ 으로 넘어옵니다.
> 사진을 등록안한 user의 profileUrl = t1.kakaocdn.net ~~ 으로 넘어옵니다.

> 외부이미지 경로를 사용하기 위해 next config의 설정을 변경했습니다.

```ts
// nextconfig.js
{
 protocol: "http",
 hostname: "k1.kakaocdn.net",  // 변경전 설정
 port: "",
 pathname: "/**",
},

//-----   변경후 --- //
{
 protocol: "http",
 hostname: "**.kakaocdn.net",  // ** 을사용해서 두경우 모두 사용가능하도록 설정 변경
 port: "",
 pathname: "/**",
},

```

2024-07-20 17:50 UTC, TransparentDeveloper commented on src/hook/use-auth-controller.ts
> +			})
넵 알겠습니다.
backlog 에 추후 변경해야할 사항에 대해 기록해두면 좋을 것 같습니다.

2024-07-20 17:51 UTC, TransparentDeveloper commented on src/component/custom/customer/home/00/index.tsx
> +
넵 고생하셨습니다.!

2024-07-20 17:51 UTC, TransparentDeveloper approved these changes

2024-07-20 18:03 UTC, merged