refactor : NTPulldown 재설계 & 판매자 header에 적용
mobi-projects/nail-case-client pull request #186
Opened 2024-07-22 07:17 UTC by snkchan

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

## [toolbar 경로 주석처리]
- [🔥 사용하지 않는 toolbar경로 주석처리](https://github.com/mobi-projects/nail-case-client/commit/ae0497c88575f7435c12007ec3031a0a11b391b8)

> MVP에 포함안되는 toolbar항목은 주석처리 했습니다.

## [scrollbar-none]
- [🎨 scroll-bar-none class 추가](https://github.com/mobi-projects/nail-case-client/commit/f907563adbf0430760b7fed049e944e7e44c66e1)

> scrollbar-none class추가했습니다.

```tsx
// 사용방법

const ScrollNone =()=> <div className="scrollbar-none">스크롤바 없음</div>
// className에 scrollbar-none 추가하면 스크롤바 없이 스크롤 가능합니다.
```

## [NTPulldown 재설계]
- [⚡️ NTPulldown refactor](https://github.com/mobi-projects/nail-case-client/commit/7df43c1659cc37b6d798823131f44b181018bece)

### [바뀐 설계]
> [shadcn ui](https://ui.shadcn.com/docs/components/dropdown-menu)의 사용법과 동일하게 사용하도록 했습니다.

### [사용 방법]

**1. NTPulldown을 사용하기 위해서 `<NTPulldown Provider>`의 자식으로 포함된 컴포넌트여야 합니다.**
```tsx
<div className="w-full pb-[42px]">
   <NTPulldownProvider>    ---------------------
        <ManagerBaseHeader />          ---------------> Manager header에서 사용하도록 provider 적용
             <NTToast />
    </NTPulldownProvider>  ----------------------
    {children}
</div>
```

**2. provider아래에서 trigger, content , label, item 컴포넌트를 사용해서 pulldown을 만들 수 있습니다.**
- 각 컴포넌트의 역할, 사용방법에 대해서는 주석 작성했습니다.
- pulldown의 구성 컴포넌트 들은 provider의 하위에 있기때문에 useNTPulldown의 return값들을 사용 할 수 있습니다.
```tsx
const { isOpen, clickedIdx, selectIdx, boxRef, toggleOpen, triggerRef } = useNTPulldown()
// provider 하위의 컴포넌트가 모두 공유해서 사용할 수 있는 context
```

**3. NTPulldown컴포넌트는 기본적인 css만 적용해둔 상태입니다.**
- 컴포넌트의 디자인에 맞게 사용할때 className을 추가해서 디자인하면 됩니다.

## [판매자 header에 NTPulldown 적용]
- [🎨 판매자 header에 NTPulldown 적용](https://github.com/mobi-projects/nail-case-client/commit/3b822e690c6f3adbc6a5a3e9ae4f719f7354d433)

<div align="center">

![bandicam-2024-07-22-16-02-12-163](https://github.com/user-attachments/assets/47c8cb33-8fb4-4023-81ef-a5b6d01c2dea)

</div>

### [pulldown의 항목중 text가 7자가 넘어가면 어떻게 처리하면 좋을까요..?]
<div align="center">

#### 띄어쓰기 포함 7자가 넘어갈때

![bandicam-2024-07-22-15-58-37-574](https://github.com/user-attachments/assets/47702938-d104-471a-8b10-f769176b650f)

> 우선은 truncate를 적용해서 ... 으로 처리했는데 의견좀 부탁드립니다.

</div>

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-24 18:41 UTC, TransparentDeveloper requested changes

2024-07-24 18:41 UTC, TransparentDeveloper commented on src/component/custom/manager/base/layout/01/index.tsx
> +			</NTPulldownContent>
# Request Level
  - [x] "🚧 재고해주시길.."


# Description

엥? pulldown 컴포넌트를 사용하는 쪽에서 이렇게 만들어 써야하나요?
이렇게 되면 일단 pulldown 컴포넌트가 통일된 형식으로 출력되지 않을 것 같고, 편의성도 많이 떨어지지 않을까요?

위의 형식을 공용컴포넌트 선언부에 넣고, 어떤 문자열 배열을 props 로 전달했을 때 통일된 형식으로 출력되게 함이 좋지 않을까요?

2024-07-25 05:20 UTC, snkchan commented on src/component/custom/manager/base/layout/01/index.tsx
> +			</NTPulldownContent>
- 해당 pulldown은 헤더에만 적용되는 pulldown이라 별도로 사용하는 컴포넌트에서 스타일을 바꿔서 적용한 상태입니다.

- 저희 프로젝트에 사용될 스타일 & text 를기본으로 가진 pulldown으로 정의해두어서 추가적인 스타일이 필요하다면 위에서 작성된 코드처럼 className을 추가하는 방식으로 사용하도록 만들었습니다.

- pulldown컴포넌트의 사용간편성, 통일성을 위해서 기존 pulldown처럼 작업을 했었는데요 문제가 있습니다...

<div align="center">

<img width="188" alt="image" src="https://github.com/user-attachments/assets/0ab05404-3464-42c6-ad1d-07a040b457c5">

> 노란색부분처럼 trigger에 아이콘만 들어가는 pulldown이 생길경우 기존 pulldown을또 수정해야합니다.

</div>

위의 case처럼 pulldown의 디자인, 구성요소 많은것들이 계속해서 바뀔여지가 있는데요.. 그때마다 하나씩 추가를 하자고 하니 너무 복잡해지더라구요... 

## [Q & A]

> Q :위의 형식을 공용컴포넌트 선언부에 넣고, 어떤 문자열 배열을 props 로 전달했을 때 통일된 형식으로 출력되게 함이 좋지 않을까요?

>  A: 의견주신대로 작업한다면 당장은 원하는대로 구현할 수 있습니다.. 하지만 위에 case처럼 아이콘만 trigger에 생긴다면? 혹은 item에 아이콘이 존재할때 text만존재할때 둘다존재할때,, 이런 경우의수가 생길때마다 분기처리를 해줘야합니다.

> 그렇다면 분기처리가 일어날때마다 props가 하나씩늘어나게 되는데 이전에 의견주신대로 사용하기 너무 복잡하지않을까요???

2024-07-25 05:23 UTC, snkchan commented on src/component/custom/manager/base/layout/01/index.tsx
> +			</NTPulldownContent>
- 흠,, 지금 제가 작업해서 올린 pulldown은 헤더에만 적용되는 특별한 pulldown인데 
의견주신대로 저희 프로젝트에 공용으로 사용되는 pulldown은 공용컴포넌트에서 관리하는게 좋을것 같긴하네요.

우선 MVP에 맞는 task들을 진행하고 모카님께서 디자인해주신 공용pulldown이 필요한 시점에 공용 컴포넌트에 작업해서 올려두는 편이 좋을것 같은데 어떻게생각하시나요?

2024-07-25 08:32 UTC, TransparentDeveloper commented on src/component/custom/manager/base/layout/01/index.tsx
> +			</NTPulldownContent>
넵 좋습니다.

2024-07-25 15:04 UTC, closed without merging