design : manager header menu 생성 & 로그아웃 기능 구현
mobi-projects/nail-case-client pull request #187
Opened 2024-07-24 17:00 UTC by snkchan

## 🔥 Issues

sub-issues:
- [NAILCASE-368](https://nailcase.atlassian.net/browse/NAILCASE-368)
<br/>
<br/>

## 🎯 작업 내용

## [사용안하는 toolbar경로 주석처리]
- [🔥 사용안하는 경로 주석 처리](https://github.com/mobi-projects/nail-case-client/commit/564136c9ea1ecb1628eddaba4371c0e9938b5a83)

> 판매자 header에 toolbar경로중 `홈`, `일정`을 제외한 경로는 주석처리했습니다.

## [기존 컴포넌트 삭제]
- [🔥 새 폴더구조에 맞게 기존 컴포넌트 삭제](https://github.com/mobi-projects/nail-case-client/commit/3592aba234671301efda66b959046763a6a3522e)

> `<ManagerLayoutSubCatalog/>` 컴포넌트를 새로운 폴더구조에 맞게 `<HeaderMenu/>` 로 대체했습니다.

## [HeaderMenu컴포넌트]
- [🎨 header menu컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/23adac5e82c721418f497995308df92742ba4f44)
- [🎨 header menu 하위 컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/9d39e29076be70e9f9bb4b75d99b49397ccaad2e)

>  `<HeaderMenu/>` 컴포넌트는 3가지 자식 컴포넌트로 구성되어있습니다.
> - Alarm
> - ProfileImage
> - LogoutButton

## [handleLogout]
- [✨ handleLogout 함수 util로 분리](https://github.com/mobi-projects/nail-case-client/commit/a9245b879278ce9542b7bded7b901e80b9665cbd)

> 새로운 폴더구조에 맞게 로그아웃 버튼 컴포넌트와 같은 폴더에 util.ts에서 handleLogout함수 관리하도록 했습니다.

## [결과물]

<div align="center" width=100 height=100>

![bandicam-2024-07-25-01-43-26-681](https://github.com/user-attachments/assets/c1c292ec-b0e3-4528-af90-1ea2565f06b4)

</div>

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-24 17:25 UTC, keeprok approved these changes
lgtb

2024-07-24 18:52 UTC, TransparentDeveloper requested changes

2024-07-24 18:52 UTC, TransparentDeveloper commented on src/component/custom/manager/base/layout/header-menu/logout-button/util.ts
> +	}
# Request Level
  - [x] "🚧 재고해주시길.."


# Description

질문이 있습니다.

refresh-token 까지 만료된 경우, token은 cookie 에 저장된 상태로 로그아웃이 실패하곤 합니다.
위의 case 에선, response 결과와 상관없이 쿠키를 제거해야하지 않나요?

2024-07-25 04:42 UTC, snkchan commented on src/component/custom/manager/base/layout/header-menu/logout-button/util.ts
> +	}
- 좋은 질문입니다.!

우선 지금 로그아웃 실패하는 case에대해서는 확실히 문제가있습니다.

해당 내용은 [이슈](https://nailcase.atlassian.net/browse/NAILCASE-360)에서 해결하는 편이 좋을것 같습니다.

> 지금 로그아웃이 실패하는 case는 백엔드에서 로그아웃처리하는 방식을 몰랐어서 로그아웃 에러가 발생했습니다.

> 리프레쉬토큰 & 만료된 accessToken으로 `로그아웃 요청을 보내면 instance에 의해서 토큰갱신후 로그아웃 요청을 보내라`라는 동작을 기대했었는데요
> accessToken의 클라이언트 측 만료기간을  세션으로 설정해두었더니 엑세스토큰에 아무것도 보내지 않은상태로 요청이 가고있었습니다. 이에 따라서 401에러를 반환받고 재요청을 가길 기대했으나 실제로 백엔드에서 그렇게 설정이 되어있지 않더라고요. 401이아닌 403에러를 받도록 되어있엇습니다.

> response에 상관없이 프론트측에서 모든 쿠키를 삭제하는 것은 로그아웃 요청의 성공실패와 상관없이 클라이언트 측에서 기대하는 동작을 항상 성공시킬 수 있는 방법입니다.
> 저또한 그방법을 고민했었는데요 여기저기 검색해보니.... 실제로 로그아웃 기능을 그렇게 동작시키면 안된다고 하더라구요...

> 토큰이 탈취당햇을때 클라이언트는 쿠키에서 모든 토큰이 사라져서 로그아웃이 성공했구나 라고 생각하지만 실제 백엔드에서는 해당 유저가 로그아웃 상태가아닌 것으로 알고있어서 이때 탈취당한 토큰을 이용하면 보안문제가 발생할 수 있다고 합니다.

> 원인을 알았으니  [해당 이슈](https://nailcase.atlassian.net/browse/NAILCASE-360) 에서 pr을 올리도록 하겠습니다.

2024-07-25 07:03 UTC, snkchan commented on src/component/custom/manager/base/layout/header-menu/logout-button/util.ts
> +	}
[해당 pr](https://github.com/mobi-projects/nail-case-client/pull/189) 에서 오류에대한 수정 진행했습니다..!

2024-07-25 08:34 UTC, TransparentDeveloper commented on src/component/custom/manager/base/layout/header-menu/logout-button/util.ts
> +	}
넵 확인했습니다.

2024-07-25 08:34 UTC, TransparentDeveloper approved these changes

2024-07-25 15:05 UTC, merged