fetch : manager base shop home
mobi-projects/nail-case-client pull request #193
Opened 2024-07-25 20:53 UTC by keeprok

## 🔥 Issues
* issue: [NAILCASE-357](https://nailcase.atlassian.net/browse/NAILCASE-357)
* sub-issue:
    - [NAILCASE-373](https://nailcase.atlassian.net/browse/NAILCASE-373)

<br/>
<br/>

## 🎯 작업 내용

## [기존 대신 사용하고있던 faker 데이터 삭제 ]
- [🔥 shopInfo faker 삭제](https://github.com/mobi-projects/nail-case-client/commit/b3ebc8647d44d345606fed670589b33cbeef9844)
- 데이터 삭제 , type 삭제 및 사용하는곳 체크 하여 삭제 조치 하였습니다
## [banner 데이터 및 cardForm 데이터 api 요청  ]
- [⚡️ fetch info api 적용](https://github.com/mobi-projects/nail-case-client/commit/0163cfa73ee111a9e393ac7fbb8ff2e65a99b047)
- banner데이터 및 cardForm데이터 type까지 완료 했습니다 
## [shop workHour 데이터 api 요청  ]
- [⚡️ workHour api 적용](https://github.com/mobi-projects/nail-case-client/commit/4a923150e726ab800f22fceb4d1ba53278212d65)
- cardData 중 시간관련 데이터 요청입니다 
## [banner 데이터 및 cardForm 데이터 화면에 적용시킴  ]
- [🎨 Fetch data ui 적용](https://github.com/mobi-projects/nail-case-client/commit/0b27d5b16440c6962bfae2cdcc5672764ef7cd51)

<img width="1212" alt="스크린샷 2024-07-26 오전 3 48 15" src="https://github.com/user-attachments/assets/26bd370b-05ad-4d0d-8a28-b5cfaace65ca">
<img width="1231" alt="스크린샷 2024-07-26 오전 3 48 22" src="https://github.com/user-attachments/assets/44f76ac9-b7d3-4da5-91ee-3209dad917ca">

## [cardForm데이터 부분에서 문제 해결]
- [🎨 fetch 적용시 문제 해결](https://github.com/mobi-projects/nail-case-client/commit/57506c3a337fcd32cb8f752006360ff74a76aa0c)
<img width="1279" alt="스크린샷 2024-07-26 오전 3 55 03" src="https://github.com/user-attachments/assets/12d7ed28-ab45-4e07-b989-8ec8f63de12f">
- 현재 이렇게 card 를 넘어가는문제가있어 퍼블리싱에서 해결하고 자 했지만 스크롤은 어떤지 먼저 확인 받기위해 올렸습니다  

https://github.com/user-attachments/assets/4fd1f7ce-86a9-4c86-8d7c-0d034fa559f4

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-26 06:19 UTC, snkchan requested changes
- 고생하셧습니다. 
- 몇가지만 수정해주시면 될거같은데 그것보다 큰 문제가 있습니다.

<div align="center">

<img width="343" alt="image" src="https://github.com/user-attachments/assets/38fc5e34-0b21-4885-be07-52a4fbe55d3f">

> 우선 이렇게 jira이슈를 연결하면 안된다고 했엇는데 수정해주시겠어요?

</div>

- 또 다른 문제점은 pr의 내용이 너무 여러가지가 섞여있는것 같습니다.

<div align="center">

<img width="353" alt="image" src="https://github.com/user-attachments/assets/667a5baf-ed56-499c-82bb-add5588b69ea">

</div>

> api shopInfo적용 이라고만 되어있는데 범위가 너무 큰것 같아요.
> 페이지단위를 한번에 작업해서 올려서 단순 퍼블리싱이라면 페이지단위 일 수 도있을것 같은데..
> 작업해주신 내용을 보면 코드삭제, 퍼블리싱, fetching 모두 포함되어있고 거기다가 컴포넌트와 함수도 분리가 안되어있어서 코드리뷰에 조금더 혼란이 오네요..

> 그래서 작업전에 백로깅을 해보는것이 중요할것 같아요.
> 내가 앞으로 어떤 작업들을 할것인지, 어떻게 나눠서 작업을 할것인지를 미리 파악해보고 작업에 들어가는 것이 pr을 올리는사람도, pr을 리뷰하는 사람도 파악하기 편할것 같습니다.

2024-07-26 06:19 UTC, snkchan commented on .gitmessage.txt
....?

2024-07-26 06:19 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	}
- isError와 error의 차이가 무엇이죠???? early return을 4번사용하고 있는데 혹시 error와 isError둘다 해줘야하는 이유가 있나요?

2024-07-26 06:19 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	console.log(workDataList)
콘솔 삭제 부탁드립니다.

2024-07-26 06:19 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	console.log(shopData)
콘솔 삭제 부탁드립니다.

2024-07-26 06:19 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +		)
- 컴포넌트 안에서 너무 복잡한 함수가 정의되어있는거 같아요. 코드가독성에 악영향을 미치는거 같은데 저희 저번에 정한것처럼. 새로운 폴더구조 적용하기로 했었잖아요?

- utill.ts파일로 별도로 분리하는편이 좋을것 같습니다.

2024-07-26 06:19 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	})
- 마찬가지로 시작시간 끝시간을 계산해서 값만 return해주는 함수를 정의하고 별도의 util파일로 분리해서 관리한다면 컴포넌트 단에서는 로직에대해 신경안써도 될거같은데 어떻게 생각하시나요?

2024-07-26 06:21 UTC, snkchan commented on .gitmessage.txt
> +🙂 commit title
...? 이건왜?

2024-07-26 06:26 UTC, snkchan commented
- 카드에 scroll처리한 부분은 기능부터 마무리하기로한 저희 일정상 잘 처리했다고 말씀드리고 싶네요.
- error케이스에 대해서 어떻게 처리할지 고민해보는것은 좋은것 같습니다. 우선은 기능부터 마무리하자고 얘기가 된 상태이니 fetching만 잘된다면 넘어가는것이 좋을것 같아요.

2024-07-26 06:34 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	}
error 는 isError가 true일때 나오는 원인을 설명해주는 부분 아닐까요?

2024-07-26 06:34 UTC, keeprok commented on .gitmessage.txt
> +🙂 commit title
잘못 누른것같네요 삭제 하겠습니다

2024-07-26 06:35 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	})
흠 한부분에서 마무리 할려다 그렇게 된것같네요 분리 하도록 하겠습니다

2024-07-26 08:21 UTC, keeprok commented on .gitmessage.txt
> +🙂 commit title
[🔥 실수삭제](https://github.com/mobi-projects/nail-case-client/pull/193/commits/b5dfcddaa45fab08a8c38a76f307e86ee33c1ea4)

2024-07-26 08:22 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +		)
[⚡️ workWeek 함수 이동](https://github.com/mobi-projects/nail-case-client/pull/193/commits/11f2d1991f056231d61618af077e43ea50c0b0a9) 
- 분리 하였습니다

2024-07-26 08:22 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	console.log(shopData)
삭제 하여 올렸습니다

2024-07-26 08:22 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	console.log(workDataList)
삭제 하였습니다

2024-07-26 08:24 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	}
현재는 
``` ts
if (isLoading || infoIsLoading) {
		return <div>Loading...</div>
	}
	if (isError || infoIsError) {
```
이런식으로 처리했는데 퍼블리싱 과정중 화면 수정하겠습니다

2024-07-26 08:55 UTC, snkchan commented
[링크](https://codesandbox.io/p/devbox/hydration-test-s7flst?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz2e3aay0006356kuwz1oy3d%2522%252C%2522sizes%2522%253A%255B79.0170481869426%252C20.982951813057397%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz2e3aay0002356krolq7c6m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz2e3aay0004356kzg75iv5h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz2e3aay0005356kgy9i7n4m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz2e3aay0002356krolq7c6m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz2e3aax0001356kiuk3ddd3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz2e3aay0002356krolq7c6m%2522%252C%2522activeTabId%2522%253A%2522clz2e3aax0001356kiuk3ddd3%2522%257D%252C%2522clz2e3aay0005356kgy9i7n4m%2522%253A%257B%2522id%2522%253A%2522clz2e3aay0005356kgy9i7n4m%2522%252C%2522activeTabId%2522%253A%2522clz2e647a0086356knfg9mclv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TESTS%2522%252C%2522id%2522%253A%2522clz2e647a0086356knfg9mclv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clz2e3aay0004356kzg75iv5h%2522%253A%257B%2522id%2522%253A%2522clz2e3aay0004356kzg75iv5h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz2e3aay0003356kq9tgstac%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clz2e39u00007dci59vgw9ns2%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clz2e3aay0003356kq9tgstac%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

2024-07-26 09:44 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +		)
@keeprok 
- workWeek를 common/util로 이동하셧는데 혹시 workWeek가 전역적으로 사용될 함수인가요??
- 최근 결정된 새로운 폴더구조와 파일관리방식에 의하면, 만약 컴포넌트에서 사용되는 util이생긴다면 같은 폴더에서 util.ts파일을 만들고 거기서 관리하기로 얘기했엇는데 공용함수로 넣으신 이유가 있나요?

2024-07-26 12:58 UTC, snkchan commented
<img width="628" alt="image" src="https://github.com/user-attachments/assets/30c1dded-4a1f-4529-a281-3d0483b686fa">

2024-07-26 14:30 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +		)
넵 사용자 부분에서도 같은 식으로 사용한는곳이 있어 공용으로 두었습니다

2024-07-28 10:49 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-07-28 10:49 UTC, TransparentDeveloper commented on src/util/common/workHour.ts
> +	const openDays = workDataList.filter((data) => data.isOpen)
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
https://pine-pie-554.notion.site/api-0a5bf26194974e2e9ceae4a98f6a4744
전에 커시님이 적어주신 문서인데, 제가 질문한 내용 확인해보시면, 한 주의 시작을 "일요일"로 하기로 했습니다.
요일 정보가 0(일) ~ 6(토) 로 올텐데, 잘못된 출력이 있을 것 같습니다.

2024-07-28 10:49 UTC, TransparentDeveloper commented on src/util/common/workHour.ts
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
chan 님이 코멘트 남기시긴 했는데, 저도 비슷한 입장입니다.

단순히 같은 로직이 두번이상 사용하는 걸 기준으로 `util > common` 폴더를 활용하는 건 적절치 못한 것 같습니다.
이전에 그 기준을 명확히 설정하지 않았으니,, 그것(기준) 과 관련하여 제 생각을 적어보겠습니다.


riel 님이 작성한 함수는 굉장히 구체적인 비즈니스 로직입니다.
지금 하고 있는 프로젝트에서만 활용이 가능할 것 같아요.

**_"그런 함수를 이곳에 선언하면 안되냐?"_ => (❌) 그렇게 생각하지는 않습니다.**
다만, 일반성은 갖춰야 합니다.

예를들어, `WorkDay()` 라는 함수의 반환은 
`"월, 화, 금\n12:00 ~16:00"`
이런 식의 string 타입이 될 것 같아요.

굉장히 구체적인 반환형태입니다. 
제 표현상 "구체적" 이라는 것은 피그마 상에서의 **특정** 컴포넌트만을 위한 반환형태라는 것입니다.
해당 컴포넌트를 수정하거나, 삭제한다면 이 함수 또한 수정 혹은 삭제되어야 하겠죠?

반대로 일반성을 갖췄다면, 특정 컴포넌트의 수정&삭제 여부와 상관없이 기능할 수 있습니다.
예를 들어, BE 에서 요일(dayOfWeek)을 100(일)~106(토) 의 값으로 전달한다고 가정해보죠.
```tsx
const covertDayOfWeekToKorean = (dayOfWeek : number) => {
  const koreanArr = ['일','월','화','수','목','금','토']
  const index = dayOfWeek % 100
  return koreanArr[index]
}
```

위의 함수 역시 해당 프로젝트에서만 사용할 수 있겠지만,
> (다른 곳에서도 설마 요일정보를 100~106 의 값으로 주진 않을테니까요??;;)

특정 컴포넌트에 종속되지 않기 때문에 더 범용적으로 활용할 수 있어요. 

이처럼 제가 생각하는 일반성(common) 이란, 
특정 조건 & 특정 컴포넌트 만을 위한 구현이 없어야 하는 것으로 이해했습니다.
이에 대해서 riel 님도 생각을 해보시고, 의견 공유해주셨으면 좋겠습니다.


### 여담 😅
말 나온김에, 제가 이번 프로젝트를 하면서 많은 함수를 만들면서 생각한 걸 공유해보겠습니다.

(주관적으로!!) `일반성을 갖춘 함수` 만들기 가장 쉬운 방법은
입력과 반환의 타입을 최대한 원시타입으로 설정하는 것입니다.
`number`, `string`, `boolean` <- 이렇게 주로 3개 정도?

누군가가 정의한 object 타입이 입력 혹은 반환 타입에 있다면, 그 자체로 특정조건에 갖춰버리게 되죠.

`WorkDay()` 또한 `TReseGetWortHours[]` 타입을 만들어서 입력으로 줘야지만 사용할 수 있어요.
중간에 `TReseGetWortHours` 타입을 수정 또는 삭제한다면?? 해당 함수 역시 수정 또는 삭제해야 합니다.
위에서 설명했던대로 특정 타입에 종속되어 버린게 아닐까요?

2024-07-29 16:53 UTC, keeprok commented on src/util/common/workHour.ts
[⚡️ work hour 함수 변경및 분해](https://github.com/mobi-projects/nail-case-client/pull/193/commits/d80afb4e48556502b95000467646a39180b7e144)
수정은 하였는데 이런식으로 수정하는게 맞는지 모르겠네요 type의 경우 BE와 맞추는것인데 이런부분은 괜찮지않을까요?

2024-07-29 16:54 UTC, keeprok commented on src/util/common/workHour.ts
> +	const openDays = workDataList.filter((data) => data.isOpen)
수정하였습니다
[⚡️ work hour 함수 변경및 분해](https://github.com/mobi-projects/nail-case-client/pull/193/commits/d80afb4e48556502b95000467646a39180b7e144)

2024-07-29 16:55 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	})
[⚡️ 시간 총합 함수 추가](https://github.com/mobi-projects/nail-case-client/pull/193/commits/2fa8725a84c62d28fece068bde5b854a7ea80f7a) 분리후 추가하였습니다

2024-07-29 19:27 UTC, snkchan approved these changes
- 고생하셔습니다..! 
- 함수를 분리해낸다는게 쉽지 않은과정이죠... 특히 저희가 처음부터 해왔던 방식에 익숙해서 더더욱 그럴탠데 함수를 분리해내는 것을 항상생각하며 작업해보시면 금방 적응하실 수 있을겁니다.
- 함수를 분리해내는 과정에서 logic에 대해 더 확실하게 분리해서 생각해볼 수 있고 , 가독성측면에서도 팀원들과 공유하기 좋은 방법이니 앞으로도 노력해보면 좋을것 같아요

2024-07-30 08:06 UTC, TransparentDeveloper commented on src/util/common/workHour.ts
의견 전달이 제대로 되지 않은 것 같습니다.

반환의 형태가 더 단순해져야 특정 조건에서 뿐만 아니라, 여러 로직에서 확용할 수 있습니다.
해당 파일의 함수 반환 형태를 다시 확인해주세요. 

"type 의 BE 와 맞춘다" 라는 말씀은 "함수의 `입력`&`반환` 에 미리 정해놓은 타입이 들어가도 되지 않나" 를 말씀하시려는 것일까요?? 그것도 일리가 있지만, 한번 정해놓은 타입이 절대 바뀌지 않는다고 확신할 수 없지 않나요?

아직 그정도까지 고려할 수준이 아니긴 하지만, 서비스 기능이 확대되면서 기존의 타입에도 변화가 있겠죠.
특정 타입에 의존하여 작성한 함수&컴포넌트가 많아질수록 수정하기 어려워질 것 같아요.

전에도 api 관련해서 BE 팀과 대화하던 중에, number 타입 속성인 줄 알았지만 null 도 가능한 속성이라 수정과정에 애먹었지 않았나요..

2024-07-30 08:18 UTC, TransparentDeveloper commented on src/util/common/workHour.ts
추가로, 함수명 컨벤션 지켜주시기 바랍니다.

2024-07-31 08:15 UTC, closed without merging