feat : manager shop price
mobi-projects/nail-case-client pull request #196
Opened 2024-07-27 16:06 UTC by keeprok

## 🔥 Issues

* issue: [NAILCASE-381](https://nailcase.atlassian.net/browse/NAILCASE-381)
<br/>
<br/>

## 🎯 작업 내용

## 가격표 이미지 몫데이터 추가
[🤡 price image 데이터 설정](https://github.com/mobi-projects/nail-case-client/commit/e6e254206a75bd3bf83463ffb5b62f1aca5f51f0)
## 가격표 이미지 기능 작동 
[✨ price modal 기능 추가](https://github.com/mobi-projects/nail-case-client/commit/1936b5bb99d548f87a1d3185708ef4f218d258ea)
- 이미지 모달 에서 이전,다음 버튼 기능 추가하였습니다 
- 모달 close를 추가 하였습니다 

# 작업물

https://github.com/user-attachments/assets/331205e6-dfe6-4c0d-98c7-793de607748c

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

[NAILCASE-381]: https://nailcase.atlassian.net/browse/NAILCASE-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-28 14:38 UTC, snkchan reviewed
- 고생하셧습니다 .
- pr사이즈가 작아서 보기좋네요 굳굳

2024-07-28 14:38 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/priceImage.ts
> +export const PriceImage = [
- 요건 별도의 파일로 혹시 분리하신이유가 있을까요?

2024-07-28 14:38 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +							alt={currentIdx.toString()}
alt 속성인데 요긴 대체 string이들어가는 자리라고 알고있는데 idx를 보여주는것은 좀 어색한것 같은데 어떻게 생각하시나요?

2024-07-28 14:38 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +						className={`h-[120px] w-[60px] cursor-pointer ${nextDisabled ? "text-Gray20" : "text-Gray20 hover:text-Gray80"}`}
스타일의 조건문을 사용할땐 cn funtion을 사용하시는것이 좋을것 같습니다.

2024-07-28 14:38 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +						className={`h-[120px] w-[60px] cursor-pointer ${prevDisabled ? "text-Gray20" : "text-Gray20 hover:text-Gray80"}`}
cn function으로 대체하는건 어떨까요?

2024-07-29 09:02 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/priceImage.ts
> +export const PriceImage = [
몫데이터라서 그렇습니다

2024-07-29 09:02 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +							alt={currentIdx.toString()}
현재 몫데이터 사용해서 key 를 넣지않아 idx로 대체하였습니다

2024-07-29 13:31 UTC, TransparentDeveloper requested changes

2024-07-29 13:31 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
useModal() 사용하면, InfoCardPrice 의 view 에 영향을 주지않고, modal 을 열수 있습니다.
`PriceImageModal` 의 props 또한 없앨 수 있구요.!

```tsx

function InfoCardPrice() {
	const { onOpenModal } = useModal()
	
	const handleArtClick = () => {
	  onOpenModal({
	    children: <PriceImageModal/>
	  })
	}
	
	return (....)
}
```

2024-07-29 13:31 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/03/priceImage.ts
> +export const PriceImage = [
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
mocking data 분리해서 좋습니다.!
컨벤션도 맞춰주시면 더 좋을 것 같습니다.! (파일명, 상수명)

2024-07-29 18:47 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +	}
[⚡️ useModal 사용추가](https://github.com/mobi-projects/nail-case-client/pull/196/commits/fc24f0ad97ef05a05b955affdfc8950704318afe) 감사합니다 ㅠㅠ

2024-07-29 18:51 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +						className={`h-[120px] w-[60px] cursor-pointer ${prevDisabled ? "text-Gray20" : "text-Gray20 hover:text-Gray80"}`}
[⚡️ 컨벤션 리팩토링](https://github.com/mobi-projects/nail-case-client/pull/196/commits/b6f164726590edaa9a424b4e6ffefd36a2cca40e) 수정하였습니다

2024-07-29 18:51 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +						className={`h-[120px] w-[60px] cursor-pointer ${nextDisabled ? "text-Gray20" : "text-Gray20 hover:text-Gray80"}`}
밑에 답변드렸습니당

2024-07-29 18:52 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +							alt={currentIdx.toString()}
[⚡️ 컨벤션 리팩토링](https://github.com/mobi-projects/nail-case-client/pull/196/commits/b6f164726590edaa9a424b4e6ffefd36a2cca40e)  제가 잘못된답변을 드렸습니다 컨벤션 수정하면서 같이 수정하였습니다

2024-07-29 18:52 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/priceImage.ts
> +export const PriceImage = [
밑에 같이 답변드렸습니다

2024-07-29 19:30 UTC, snkchan approved these changes
- 고생하셧습니다. 
- alt에대해서 한가지 더 드릴말씀이 있는데. 
- 지금 수정해주신 것을 보니 alt에 이미지 url을 그냥 넣으셧더라구요...
- alt는 무엇이냐면 만약저희 인터넷 접속했을때 페이지 못불러올경우에 원래 이미지가 보여야 할곳에 "logo" "profile-Image"이런식으로 적힌것을 본적이 있을겁니다.
- 이미지를 못불러 왔을경우 보여줄 text를 작성해주시면 될것같은데.
- banner-image라던지 그냥 text로 넣으시면되는데 퍼블리싱하면서 수정해보죠

2024-07-30 14:39 UTC, TransparentDeveloper requested changes

2024-07-30 14:39 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/03/modal/index.tsx
> +		<NTModal size="small" isX={false}>
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
모달 컴포넌트, 이렇게 사용하는 게 아닙니다..
사용법 다시 확인해주세요. [관련 pr](https://github.com/mobi-projects/nail-case-client/pull/114)

2024-07-31 08:15 UTC, closed without merging