refactor : 서버환경, 클라이언트환경 둘다 적용가능한 axios-instance 생성
mobi-projects/nail-case-client pull request #198
Opened 2024-07-28 21:06 UTC by snkchan

## 🔥 Issues

sub-issues:
- [NAILCASE-370](https://nailcase.atlassian.net/browse/NAILCASE-370)

<br/>
<br/>

## 🎯 작업 내용

## [jwt decode]
- [➕ jwt-decode 의존성 추가](https://github.com/mobi-projects/nail-case-client/commit/0b641f12e72b906bd65b7c1293ed90799674ef2f)

> jwt-decode 라이브러리를 설치했습니다.
> accessToken 에서 만료시간 정보를 추출하는 용도로 사용합니다.

## [환경상태에 따라 cookie접근 함수 정의]

- [✨ 환경상태에 따른 accessToken반환 함수 정의](https://github.com/mobi-projects/nail-case-client/commit/2f118c4779648259df3bc696105fc117150505ab)

> 이전에 말씀드린것 처럼 `cookies-next` 의 getCookie를 하기위해서는 서버 , 클라이언트 동작방식이 다릅니다.

```tsx
// 클라이언트 일때
const accessToken = getCookie(키)

// 서버일때
const accessToken = getCookie(키,{cookies}) 
```
- cookies는 next/headers에서 import해서 사용해야하는데 cookies는 서버환경에서만 동작하기 때문에  별도의 파일로 분리했습니다.
## [refresh api요청 반환타입 수정]
- [⚡ 리프레쉬 요청 return type 명시](https://github.com/mobi-projects/nail-case-client/commit/b7d545f0594f1bc5c4dac6d8c6bf7d8a73146f34)

> 기존에 반환타입을 정의안했는데 반환타입 설정해줬습니다.

## [axios-instance refactor]

- [⚡ axios instance refactor](https://github.com/mobi-projects/nail-case-client/commit/5f2a901beff4d3670a94294f90018b4219471bbb)

> 지난 회의때 얘기했던 수정방향
> - instance를 사용할때마다 client인지 server인지 props로 전달받도록 수정하자..! 라고했었습니다.
> - api폴더 또한 새로 만들고, 함수도 다시작성하자..! 라고 정리했엇는데요.

> 실제 refactor된 내용
> - instance를 사용할때마다 props를 작성하는 것이 너무 불편한것 같아서 props사용 안하도록 만들었습니다.
> - instance가 동작할때마다 `typeof window` 를 사용해서 서버인지, 클라이언트인지 check해서 동작하도록 만들었습니다.
> - 결론 : 기존api그대로사용, instance를 사용할 때도 그냥 기존방식과 동일하게 사용.

> api 병렬 요청에 관하여.
> - jwt-decode를 활용해서 요청전에 유효한 토큰인지 검사를 진행하도록 코드가 수정되었는데요
> - 만약 유효하지 않다면 refresh요청후 갱신한 토큰으로 요청이 진행하도록 수정되었습니다.
> - 이때,,! 한가지 문제되는점이 api 병렬 요청의 경우 refresh 요청또한 동시에 실행되는데요 이러면 오류를 발생시킵니다.
> - 따라서..! ==> refresh요청이 실행중이라면 그 후의 요청은 refresh요청을 대기하도록 코드를 설정했습니다.

## [결론]
refactor된 instance를 사용할때 아무것도 신경안써도 됩니다. 기존과 똑같은 방식으로 코드를 작성해도 문제없습니다.
또한 앞으로 api요청을 병렬로 보내도 문제없습니다..!

https://github.com/user-attachments/assets/17ea0f6f-f070-40a3-85c3-1db9e4bd9cc2

> 만료 or refreshToken만 존재할때 api병렬 요청시 token갱신과정

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-29 11:38 UTC, TransparentDeveloper requested changes
고생하셨습니다.!

엄청나네요 ㅎㄷㄷ;;

혹시 아래 설정은 어떻게 하신 건가요?? 
못찾아서 여쭤봅니다.

<img width="671" alt="contents_of_marked_text" src="https://github.com/user-attachments/assets/7d855756-adc2-4de6-a4bb-127191786e23">

2024-07-29 11:38 UTC, TransparentDeveloper commented on src/config/axios/instance.utll.ts
> +	if (isExpired(token) && typeof window !== "undefined") {
# Request Level
  - [x] "🚧 재고해주시길.."

# Description

```tsx
if( typeof window !== "undefined" ) {....}
```
서버환경일 때 true 인지, 클라이언트환경일 때 true 인지 5초정도 바라봐야 이해가 되더라구요..
게다가 같은 파일에서 해당 조건식이 두 번정도 사용됩니다.

분리하고 추상화하는 편이 가독성, 유지보수성(일괄 수정?) 면에서 좋을 것 같습니다.


```tsx
// 예시코드
const isServerSide = () => typeof window === “undefined”
```

2024-07-29 11:38 UTC, TransparentDeveloper commented on src/config/axios/instance.utll.ts
> +}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
조건식(if, try-catch) 이 많이 중첩되어 있어서 이해하기가 어려운 구조입니다.

가장 쉽게 return 되는 것을 상단으로 끌어 올리면 조건이 중첩되는 걸 줄일 수 있어요.
다음과 같이 수정해보면 어떨까요?

```tsx
if (!isExpired(token)) return token as string  // 만료되지 않은 토큰이라면, 입력을 그대로 반환
if (isServerSide()) return token as string  // 서버환경이라면 입력을 그대로 반환

try {
    const { data: refreshedToken } = await postResquestNewToken()
    setAuthTokens(refreshedToken) // 새로운 토큰 설정
    return refreshedToken
} catch (error) {
    return Promise.reject(error)
}
```

2024-07-29 18:50 UTC, keeprok approved these changes
저는 추가적으로 찾지는 못햇네오 수고하셨스비다

2024-07-29 19:21 UTC, snkchan commented
@TransparentDeveloper 
좋은 의견 감사합니다..! 올리고서 만족스럽지 않았는데 역시..

## [수정한 내용]

**isServer추가**
> `const isServer = ()= > typeof window === "undefined" ` 추가했습니다.

**handleRefreshingError추가**
> 해당함수에서 세션만료 & 홈으로 redirect 기능하도록 추가했습니다.

## [추가로..]

> 같이 고민해봤던 부분에 대해서 추가적으로 알아낸 내용에대해서 공유드립니다.

**isRefresing flag vs Promise flag**

> boolean타입으로 flag를 사용하면 더 좋지않을까 같이 고민해봤었는데요 둘다 맞는 방식이라고하네요.

> 하지만 차이점이 존재하는데..!
> - Promise객체를 사용한 flag의 경우 지금 제가 작성한 코드처럼 await을 사용해서 순차적으로 코드작성이 가능합니다.
> - 반면 boolean flag의 경우 아까 Jeff님이 작성한 코드처럼 setTimeout & while문을 사용해서 동작시키는 방식이 맞다고 합니다.

> 그렇다면 아까 왜동작을 안했는가..?!
> -아까 Jeff님이 예상하신 것처럼 if()후에 else처리에대한 부분이 없어서입니다.
> - 이미 refreshing중이라면? return 무엇을해주지,,,? 라고 고민한 바로 그부분이 없어서 그랬습니다. 
> - 현재 제가 작성한 코드에서 refreshing중이면 어떻게 동작하는지 에대해 주석을 추가했으니 확인해주세요

```tsx
else {  // 현재 미리 refreshing요청이 진행중인 상황에는,,!
const { data: newTokens } = await refreshPromise
return newTokens.accessToken // 기존 요청중인 토큰 갱신을 기다린후 새로발급된 accessToken을 반환

```

## [한가지 더..!]

pr을 수정하며 이렇게 코드를 작성하는 편이 가독성이 높겠다..! 라고 생각했습니다.
```tsx
const getValideAcceessToken = ()=>{

if(리프레슁 해야할경우)
{
 handleRefreshing()
} else{ // 이미 리프레슁이 진행중일 경우는?
 handleAlreadyRefreshing() 
} error
 handleErrorRefreshing()
}
```

> 위와같이 작성하면 가독성이 좋겟다,,! 라고 생각했지만 refreshPromise 가 해당 파일에서 전역으로 사용되는 변수라서
매개변수로 전달해서 사용하면 값을 계속 동기적으로 연결시키면서 사용하기 어려운 구조였습니다....

> 그래서 요청주신부분 만 조금 수정을 했습니다. 제성합니다..

2024-07-30 08:23 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-07-30 08:23 UTC, TransparentDeveloper commented on src/config/axios/instance.utll.ts
> +	return token as string // 기존 accessToken정보 반환
(40줄) "기존 accessToken정보 반환" 되는 케이스를 먼저 분기시켜서 return 해주시겠어요?
21 ~ 37 의 조건을 하나 줄일 수 있어서 좋을 것 같습니다.

2024-07-30 14:53 UTC, snkchan commented on src/config/axios/instance.utll.ts
> +	return token as string // 기존 accessToken정보 반환
[⚡️ early return으로 수정](https://github.com/mobi-projects/nail-case-client/pull/198/commits/fcddfbde6e67eb29aff5a919ec74ef748fcee2fc)
 
 수정해버렸습니다..! 제성합니다.

2024-07-30 14:55 UTC, snkchan commented on src/config/axios/instance.utll.ts
> +	return token as string // 기존 accessToken정보 반환
```ts
if(!isExpired(token)) return tokne // 유효한 토큰은 그대로 유효한 token return

if(isNull(refreshPromise)) {
//리프레시 로직

}else{
//  이미 리프레쉬 중이라면 기다렸다가 유효한 토큰을 반환
}

```
위의 형태로 수정했습니다..! 더깔끔하네요 굳굳

2024-07-30 14:55 UTC, snkchan commented on src/config/axios/instance.utll.ts
> +	return token as string // 기존 accessToken정보 반환
```ts
if(!isExpired(token)) return tokne // 유효한 토큰은 그대로 유효한 token return

if(isNull(refreshPromise)) {
//리프레시 로직

}else{
//  이미 리프레쉬 중이라면 기다렸다가 유효한 토큰을 반환
}

```
위의 형태로 수정했습니다..! 더깔끔하네요 굳굳

2024-07-30 17:15 UTC, snkchan commented on src/config/axios/instance.utll.ts
> +	return token as string // 기존 accessToken정보 반환
@snkchan
[⚡️ early return 추가](https://github.com/mobi-projects/nail-case-client/pull/198/commits/fad578fa40aac9b72b282f900bc34d2f3d49f60d)
수정완료!!

2024-07-30 17:15 UTC, merged