feat : manager base my shop banner
mobi-projects/nail-case-client pull request #201
Opened 2024-07-29 14:45 UTC by keeprok

## 🔥 Issues

* sub-issues:
    - [NAILCASE-366](https://nailcase.atlassian.net/browse/NAILCASE-366)
<br/>
<br/>

## 🎯 작업 내용

## banner 몫데이터 추가 
[📚 banner 데이터 추가](https://github.com/mobi-projects/nail-case-client/commit/cbfa872d22aba94632f6f69cc1690ac703960ec7)

## banner 데이터 패칭
[🎨 banner 데이터 패칭](https://github.com/mobi-projects/nail-case-client/commit/ec2b429fdfe01a2e892147a206c828939b80be0b)
- banner 부분 데이터 패칭 

## banner 이미지
[✨ manager/my-shop 배너 넘김 및 이미지 추가](https://github.com/mobi-projects/nail-case-client/commit/cd222394918aca444e1b1a6534e6de046a9c560d)
- 이미지 적용 및 이미지 가 10초에 한번씩 전환되게 하였습니다

# 작업물 
https://github.com/user-attachments/assets/e6ca36ec-1736-4c98-8fd2-4dfe36f55310

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-07-29 19:36 UTC, snkchan requested changes
- 고생하셧습니다..! 
- 지금 banner넘어가는 내용은 좋은데요..! 근데 조금 더 수정해볼 여지가 있을것 같은데 내일 같의 상의해볼까요?

2024-07-29 19:36 UTC, snkchan commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							alt={Object.values(image)[0]}
alt여기서는 제대로 수정해볼까요?

2024-07-29 19:36 UTC, snkchan commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							layout="fill"
layout이라는 속성명은 더이상사용 하지 않습니다..! 
fill이라고만 적어주시면 됩니다.

2024-07-29 19:36 UTC, snkchan commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							layout="fill"
<img width="488" alt="image" src="https://github.com/user-attachments/assets/73e46124-5a38-4e61-b485-84922052dd15">

공식문서에도 boolean타입으로 올라와있죠?

2024-07-29 19:36 UTC, snkchan commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							layout="fill"
<img width="499" alt="image" src="https://github.com/user-attachments/assets/86caaa48-8315-4380-8eba-13be93f9ed45">

배너이미지의 경우 화면에서 큰이미지에 해당하니 priority속성을 추가해서 preload를 할수있게 해주는게 어떨까요????

2024-07-30 08:32 UTC, TransparentDeveloper requested changes
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
작업 내용에 대해서 의문이 있습니다.
스프린트 회의할 때, `tagList`, `overview` 는 제거하기로 않았나요?
`image-carousel` 부분도 굳이 수정할 필요가 있었나요?

전체적으로 공유되지 않은 방향으로 작업이 이뤄진 것 같은데, 답변 꼭 남겨주세요.

2024-07-30 10:40 UTC, keeprok commented
tagList, overview 이부분 이야기 할때 화장실가서 못들었습니다 ;;
이미지 가로딩안된순간을위해 image-carousel 을 다시 넣는것으로 수정하겠습니다

2024-07-30 14:17 UTC, keeprok commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							layout="fill"
저부분은 지난 부분 가져왔던것인데 수정안하고 가져왓네요 수정하겠습니다 , priority 는 넣어두었습니다

2024-07-30 14:19 UTC, keeprok commented
@TransparentDeveloper 
현재 추가적으로 
## 설정버튼들 여부
tagList, overview 는 제거 하자는 의견이 있었다는것에관해서 그렇다면 배너부분에서는 설정버튼, pensel버튼 2가지가 포함되어있는데 사진을 변경하는부분에있어서 따로 이야기 가 없었기에 일단 삭제 조치후 다음 스프린트때 사진 변경   기능 포함하면서 설정버튼을 추가 하도록 하겠습니다
## 배너부분 퍼블리싱 
배너 이미지 가 넘어가는부분에 있어서는 현재 1~5개의 이미지를 받게 하자고 했는데 어떻게 보여지게 할것인지 에 관해서는 이야기를 하지않아서 일단은 시간의 흐름에 따라 자동적으로 변동되게 하였습니다

2024-07-30 14:24 UTC, keeprok commented on src/component/custom/manager/base/my-shop/layout/01/index.tsx
> +							layout="fill"
[⚡️ image 부분 변경](https://github.com/mobi-projects/nail-case-client/pull/201/commits/e48786936594a2603fc297e5fae03d54fcd63e3a) 변경하였습니다

2024-07-31 08:15 UTC, closed without merging