feat : manager work hour
mobi-projects/nail-case-client pull request #205
Opened 2024-07-31 21:54 UTC by keeprok

## 🔥 Issues

* sub-issues:
   - [NAILCASE-406](https://nailcase.atlassian.net/browse/NAILCASE-406)
<br/>
<br/>

## 🎯 작업 내용

## formTime 추가 
[✨formTime 타입 추가](https://github.com/mobi-projects/nail-case-client/commit/d5d59ba7b3712cd9c221a86f52f6d2a0546cd161)
`{ 오전 || 오후 } "시간" "분" ` 으로 나오도록 설정 하였습니다 

## workingHour form Fetch 
[✨ WorkingTimeForm 설정](https://github.com/mobi-projects/nail-case-client/commit/f2107cc2cf224641bdeec13ab6bb0993b8a129ea)
- 화면으로 보여지는 부분이 util로 처리 해야되서 util 로 같이 넣었습니다

## 작업물
<img width="333" alt="스크린샷 2024-08-01 오전 6 53 13" src="https://github.com/user-attachments/assets/860a7693-7d17-44cb-ad27-2484d9ffccf9">
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

[NAILCASE-406]: https://nailcase.atlassian.net/browse/NAILCASE-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-01 08:51 UTC, TransparentDeveloper requested changes

2024-08-01 08:51 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/info-card/card-form/working-time-form/util.ts
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
컴포넌트 관련 함수 파일명 전에 같이 얘기했었는데..
수정부탁합니다.

2024-08-01 08:51 UTC, TransparentDeveloper commented on src/util/common/time.ts
> +}
# Request Level
  - [x] "🚧 재고해주시길.."
  
# Description
개인적으로 이것 또한 구체적인 반환이라고 생각합니다.
실제로 피그마 상에선 "21:00" , "오후 09:00" 등 시간과 관련해 다양한 출력형식이 존재합니다.

위의 함수를 허용하면, 각 출력에 대한 별도의 공용 함수 하나씩 만들어야 하지 않을까요?
각 컴포넌트 단에서, `오전/오후`,`시간`, `분` 을 조합해 사용하는 편이 저는 더 좋다고 생각합니다.

참고로 위의 함수의 출력 예 중, "오후 9:00" 가 있습니다. ("오후 09:00" 가 아닙니다. )

2024-08-01 14:28 UTC, snkchan reviewed
- 고생하셧습니다..!
- 저도 Jeff님과 동일한의견 하나 남겼습니다.
- 추가적으로 working-time-form에서 관리하는 util함수도한 조금더 좋은 방향으로 코드를 작성해볼 여지가 있지않나 라는 생각이드는데 , 당장 기능한다면 MVP를 위해서 뒤로 미뤄도될것 같아요

2024-08-01 14:28 UTC, snkchan commented on src/util/common/time.ts
> +}
- 저도 동의합니다...! text 를 return해주는 것보다는 {hour,minute,dayDivision} 형태로 return해준다면 common에 있을수 있겟지만 string을 return해주는 함수는common에는 적합하지 않다고 생각합니다.

2024-08-02 01:39 UTC, keeprok commented on src/util/common/time.ts
> +}
[🚚 파일 위치 수정및 변수수정](https://github.com/mobi-projects/nail-case-client/pull/205/commits/ff2104bcf19d489a02c3add303c376a014d480c2) 시간 만 보인다면 피그마처름 00시 가아닌 00으로 사용하는게 좋지만 현재는 분까지 표기하고 있어 가운데 있을때는 양옆이 오후 : 2글자 00분  : 2글자 이므로 공통적이게 09 로 적용하였습니다

2024-08-03 07:30 UTC, TransparentDeveloper approved these changes
넵 고생하셨습니다.
사소한 수정 요청사항 하나 남겼습니다.
그것만 고려해주시면 merge 하셔도 좋을 것 같습니다 :)

2024-08-03 07:30 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/banner/index.tsx
이건 절대경로로 수정되면 좋을 듯합니다.!

2024-08-03 14:51 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/banner/index.tsx
수정하였습니다
[🔥 파일위치 수정](https://github.com/mobi-projects/nail-case-client/pull/205/commits/5cb708cb3730f4c1a43c73cb2f908c70d158ce91)

2024-08-04 15:42 UTC, snkchan approved these changes
- LGTM..!

2024-08-04 15:43 UTC, merged