design : redesing required reservation form
mobi-projects/nail-case-client pull request #210
Opened 2024-08-03 10:05 UTC by keeprok

## 🔥 Issues

*sub-issues:
    - [NAILCASE-396](https://nailcase.atlassian.net/browse/NAILCASE-396)
<br/>
<br/>

## 🎯 작업 내용

# hours 디자인 변경
[⚡️ hours.util 추가](https://github.com/mobi-projects/nail-case-client/commit/21e7e25239bb889c6620d66e1542901b93fcc7cf)
- 시간 util  시간함수 추가 
[🎨 OpeningHours 디자인 변경](https://github.com/mobi-projects/nail-case-client/commit/13c383ccdb8a1c3e7fac1e5bab650b730f7a3ff3)
- 디자인 변경에 맞춘 시간 표기 변경
 # 작업물
<img width="1237" alt="스크린샷 2024-08-03 오후 7 02 05" src="https://github.com/user-attachments/assets/60677205-6bc1-4ee2-b0ba-bd64b05fa035">

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-08-04 16:10 UTC, snkchan requested changes
- 몇가지만 수정부탁드립니다.
- 추가로...
전체적으로 파일명, 함수명 작성하실때 form이란 단어를 많이 사용하셧는데 form 이란단어가 포함된 함수명, 컴포넌트명, 파일명을 봤을때 무슨역할을 하는지 잘모르겠습니다.
- 조금더 의미적으로 잘표현되는 이름으로 작성하면 어떨까요?

2024-08-04 16:10 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/shop-information/shop-details/opening-hours/hours-form/index.tsx
> +export function HourFrom({ title, time }: hourFromPT) {
파일명은 hours-form인데 컴포넌트명은 HourForm이라 하나로 통일해야할것 같습니다.

2024-08-04 16:10 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/shop-information/shop-details/opening-hours/hours.util.ts
> +export const unixTimeForm = (time: number) => {
함수작명이 조금 애매한거 같아요 unixTimeForm은 함수이름만 봤을때 어떤 것을 반환하는지 모르겠는데 getUnixTime or getUnixTimeToOpeningHours 이런식으로 의미가 명확했으면 좋겠습니다.

2024-08-04 16:10 UTC, snkchan commented on src/hook/use-auth-controller.ts
>  }
해당함수는 middleware설정에 의해 더이상 필요가 없을것 같은데 삭제 부탁드립니다..!

2024-08-05 15:26 UTC, keeprok commented on src/hook/use-auth-controller.ts
>  }
이부분은 구두 로 말씀드렸습니다

2024-08-05 15:27 UTC, keeprok commented
@snkchan  흠이름을 가져갈때 그런식으로 조금더 생각을 해봐야겠네요 form이라는것을 너무 가볍게 사용했던것같네요

2024-08-05 15:36 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/shop-information/shop-details/opening-hours/hours-form/index.tsx
> +export function HourFrom({ title, time }: hourFromPT) {
[🔥 파일명 수정](https://github.com/mobi-projects/nail-case-client/pull/210/commits/8b353fc27faad65d939db4fdb710176aeec7f029) 수정했습니다

2024-08-05 15:36 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/shop-information/shop-details/opening-hours/hours.util.ts
> +export const unixTimeForm = (time: number) => {
[🔥 파일명 수정](https://github.com/mobi-projects/nail-case-client/pull/210/commits/8b353fc27faad65d939db4fdb710176aeec7f029) 수정했습니다

2024-08-06 07:05 UTC, snkchan approved these changes
- LGTM/..!

2024-08-08 07:11 UTC, merged