design : customer shop banner
mobi-projects/nail-case-client pull request #212
Opened 2024-08-08 12:14 UTC by keeprok

## 🔥 Issues

* sub-issues:
   - [NAILCASE-420](https://nailcase.atlassian.net/browse/NAILCASE-420)
<br/>
<br/>

## 🎯 작업 내용

# 이전 파일 구조 삭제 및 정리 
[🔥 CustomerShopBanner 파일 삭제](https://github.com/mobi-projects/nail-case-client/commit/cc3528e47ca249ffe58deb3a4a707353c1ffa05d)
[🚚 shopBanner BuutonList파일분리](https://github.com/mobi-projects/nail-case-client/commit/a62432c92b7eb5d6c8ecd3f5adf87ef70c481f5b)
[🎨 shop Banner Title 추가](https://github.com/mobi-projects/nail-case-client/commit/93eb8ef8509657dbac5fb9e64a59e28ff85df022)
# 찜 버튼 추가
[🎨 shop Banner Wishbutton 추가](https://github.com/mobi-projects/nail-case-client/commit/48907060d65b28cb162d4ae91595be948e7f83dd)
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-08-08 13:51 UTC, TransparentDeveloper requested changes
고생하셨습니다.
해당 pr 에서 작업된 부분은 기존 소스코드 위치를 변경만 한건가요? (+ 아이콘 추가?)
작업 내용을 작성해주시면 리뷰하는 것도 수월할 것 같습니다.

추가로 pr 본문에 게시된 이미지를 확인했는데, 아이콘마다 shadow 가 다르게 적용된 것 같습니다.

<img width="74" alt="icons-shadow" src="https://github.com/user-attachments/assets/cfd7295a-47cd-443c-a800-b36d8d3bb739">

수정이 가능할까요?

2024-08-08 13:51 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/banner/banner-button-list/indext.tsx
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
파일 이름에 오타가 있네요.
`indext.tsx` -> `index.tsx` 로 수정부탁합니다.

2024-08-08 13:51 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/banner/banner-button-list/wish-button/index.tsx
> +}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
음.. 이미 추상화가 된 아이콘 컴포넌트인데, 이렇게 분리하신 이유가 있을까요??
이벤트 핸들러가 추가된 것도 아니고,, 불필요하게 나눠진 게 아닌가 싶습니다..

2024-08-08 13:51 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/banner/banner-button-list/indext.tsx
> +	}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
`useModal()` 사용해주시길 바랍니다..

2024-08-08 13:51 UTC, TransparentDeveloper commented on src/component/custom/customer/shop/banner/index.tsx
> +}
# Request Level


  - [x] "🚧 재고해주시길.."
# Description
text 만 달라지고, 나머진 거의 중복되어 쓰여졌어요.
분리를 잘해보면 더 효율적으로 작성할 수 있을 거예요.!

2024-08-09 05:04 UTC, keeprok commented on src/component/custom/customer/shop/banner/banner-button-list/wish-button/index.tsx
> +}
이부분 찜기능을 넣을때 handle이 추가될것을 생각해서 나눠놨습니다

2024-08-09 05:05 UTC, keeprok commented on src/component/custom/customer/shop/banner/banner-button-list/indext.tsx
> +	}
이미 사용하고 있는 것을 퍼블리싱을 위해  파일 변경 만한거라 다음 모달 변경 pr을 통해 바꾸겠습니다

2024-08-09 05:08 UTC, keeprok commented on src/component/custom/customer/shop/banner/index.tsx
> +}
이부분또한 다른pr에서 변경 예정이었나 다음 commit으로 올리겠습니다

2024-08-09 05:29 UTC, snkchan reviewed
- 고생하셧습니다.!

2024-08-09 05:29 UTC, snkchan commented on src/component/custom/customer/shop/banner/index.tsx
> +}
- error notfound pending 도 분리부탁드립니ㅏㄷ.!
-

2024-08-09 05:29 UTC, snkchan commented on src/component/custom/customer/shop/banner/banner-tilte/index.tsx
> +		<div className="">
빈태그 삭제부탁드립니다.!

2024-08-09 11:07 UTC, keeprok commented on src/component/custom/customer/shop/banner/banner-button-list/indext.tsx
> +	}
[⚡️ modal 형태 추가 및 nt-modal로 추가](https://github.com/mobi-projects/nail-case-client/pull/212/commits/b344f735c7968e179db3769bc1a6515aac64c149) 변경했습니다

2024-08-09 11:09 UTC, keeprok commented on src/component/custom/customer/shop/banner/banner-tilte/index.tsx
> +		<div className="">
[🔥 필요없는 코드 삭제](https://github.com/mobi-projects/nail-case-client/pull/212/commits/aa52e2cee38c9e218ea0a086c9b39ae940b43ed4)
삭제조치 하였습니다

2024-08-09 11:09 UTC, keeprok commented on src/component/custom/customer/shop/banner/index.tsx
> +}
[🚚 StatusMessage 파일분리](https://github.com/mobi-projects/nail-case-client/pull/212/commits/ed819525e642857c843c1437c8cdf34615d9f0af) 분리 하였습니다

2024-08-09 11:10 UTC, keeprok commented on src/component/custom/customer/shop/banner/banner-button-list/indext.tsx
[🔥 파일명 수정](https://github.com/mobi-projects/nail-case-client/pull/212/commits/7eda78058143d4b5673f6089af8460b1a95ab0fe) 변경하였습니다

2024-08-09 11:52 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-08-09 11:52 UTC, TransparentDeveloper commented on src/component/common/nt-modal/index.tsx
>  				small:
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
PR 내용을 적어주세요. 스토리북이라도 작성을 해주셨어야 합니다.
어떻게 출력되는지 확인이 공유가 안되니까요.

2024-08-09 12:52 UTC, keeprok commented on src/component/common/nt-modal/index.tsx
>  				small:
아 죄송합니다 추가 하도록 하겠습니다

2024-08-11 12:54 UTC, snkchan approved these changes
- 고생하셧습니다

2024-08-12 06:36 UTC, merged