feat : customer shop phone button 클릭시 모달 기능추가 및 로딩 상황 추가
mobi-projects/nail-case-client pull request #219
Opened 2024-08-13 19:27 UTC by keeprok

## 🔥 Issues

* sub-issues:
    - [NAILCASE-422](https://nailcase.atlassian.net/browse/NAILCASE-422)
<br/>
<br/>

## 🎯 작업 내용

## 로딩중 버튼클릭시
[✨ 로딩시 toast message 추가](https://github.com/mobi-projects/nail-case-client/commit/5d7e1f7307aa30fb2924f18494b340f98827e08e)
- 로딩중 toast message 전송 추가 

## 로딩 성공시 버튼 클릭시
[🎨 number 버튼 클릭시 모달 추가](https://github.com/mobi-projects/nail-case-client/commit/1212e92ce3b2b7d1ec2b0d988bd00bb8a3f4fc84)

- 로딩 성공시 모달 디자인 추가 
- 복사 버튼 클릭시 toast message
## 로딩중일때

https://github.com/user-attachments/assets/ddbc3e37-b1bc-44a7-b0d7-7c3d336472a3

## 로딩 성공시
https://github.com/user-attachments/assets/333de6eb-c1bd-451b-bc0e-f104c3cdac25

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-08-14 08:09 UTC, snkchan reviewed
- 로딩처리와 관련해서 고민해볼 것이 있습니다.

- 제가 오늘 velog에서 어떤 글을 봤는데요.. 어디서봤는지 찾아도 안보이네요.. 링크가 없어서 어떤 내용인지 요약해보자면

> 비동기 데이터 처리를 하는 과정에 모든 ui에 skelton ui를 적용해야 하냐?? 에 대한 내용이었습니다.
> loding에대한 ui를 보여주는 것은 매우중요한데 매번 보여주는 것은 오히려 UX를 저하시킬 여지가 있습니다.
>예를 들어 0.5초안에 화면에 보여지는 ui가 존재하는데 skeltion은 약 0.3~0.4초 정도만 보인다면 오히려 화면의 깜빡거림때문에 더 불편한 UX를 제공할 여지가 있다고하네요.

지금 로딩처리를 하신부분에 대해서도 위와같은 고민을 해볼 여지가 있을것 같은데요.
전화하기 버튼을 눌렀을때 사용자가 얼마나 기다린후 loding에대한 ui를 볼것인가 고민해 보는것도 좋을것같은데 꼭 필요한 toast인지 궁굼합니다.

2024-08-14 08:09 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/button-list/phone-number-button/number-modal/phone-number.util.ts
> +export const customPhoneNumber = (phoneNumber: string) => {
- 함수이름인데 함수명을 선언 하신것을 보면 변수명 처럼보인다고 생각됩니다.
ex) customerPhoneNumber = 0101111111

- 함수명이라면 동사로 시작하는것이 좋지않을까요?

2024-08-20 18:07 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/button-list/phone-number-button/number-modal/phone-number.util.ts
> +export const customPhoneNumber = (phoneNumber: string) => {
[🔥 로딩시 phone 버튼 toast 삭제](https://github.com/mobi-projects/nail-case-client/pull/219/commits/d2c727fd3b765d1911a3f6a0d061936d67d3ae41) 
- 변경 및 로딩시 삭제 조치 하였습니다 추가적으로 로딩시 화면 pr 올리겠습니다

2024-08-22 16:13 UTC, snkchan requested changes

2024-08-22 16:13 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/button-list/phone-number-button/number-modal/phone-number.util.ts
> +export const customerPhoneNumber = (phoneNumber: string) => {
- 아까 말씀드린것처럼 동사로 시작하는게 어떤 동작을 하는지 명확하지 않을가요?

getPhoneNumber 이나 createPhoneNumber처럼 작성하면 더 정확하지않을까요?
함수이름만 보고도 어떤 동작을해서 어떤 값을 반환하는 함수구나 읽을수있을 것 같은데

2024-08-29 18:34 UTC, closed without merging