design: NTTimeSwitch 작성
mobi-projects/nail-case-client pull request #22
Opened 2024-06-08 13:08 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-64](https://nailcase.atlassian.net/browse/NAILCASE-64)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 NTTimeSwitch 컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/5121d7a72eaeac024cd168ea9884749d64034d7c)
  - NTTimeSwitch 컴포넌트 생성 완료했습니다.
  - NTTimeSwitch에 text-Callout가 적용안되는 문제는 design/button(NTButton에서 cn 함수 수정) 브랜치를 merge 하면 해결되는 부분이니 확인 부탁드릴게요

- [🎨 NTTimeSwitch 스토리 작성](https://github.com/mobi-projects/nail-case-client/commit/12e825636a638c9c495b7f7c9440b33401f05e91)

    - NTTimeSwitch 컴포넌트 스토리 작성 완료했습니다.

### [스토리북 배포링크](https://66588595839cce76dee2be9d-copxpnxhfn.chromatic.com/?path=/story/component-common-nt-time-switch--active)
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-08 13:47 UTC, TransparentDeveloper approved these changes
<div align="center">

![image](https://github.com/mobi-projects/nail-case-client/assets/50646145/a814366b-f739-47aa-a00f-af3a9c8c136c)

</div>

2024-06-08 16:03 UTC, snkchan approved these changes
- 고생하셧습니다..! 빠르게 잘하셧네요!

2024-06-08 16:03 UTC, snkchan commented on src/component/common/nt-time-switch/index.tsx
> +		children?: React.ReactNode
- 앞선의견이랑 동일하게 ReactNode는 좀큰 범위아닌가싶습니다..!
- 다른분들은 어떻게 생각하시나요?

2024-06-08 16:03 UTC, snkchan commented on src/component/common/nt-time-switch/index.tsx
> +		<button
- 조금더 생각해볼 여지가 있을것 같아요..!
- figma에 moka님 의견을 확인해보니 클릭시 어떤 이벤트가 발생해야하는데 callback함수가 들어갈거같은데 사실 지금 고민하긴 좀 어렵네요... 후에 해당컴포넌트에 기능을 추가할때 작업해도될 부분같습니다.! 

- 의견을남긴이유는 앞으로의 작업에도 이런부분들을 같이 고민하면서 진행하면 좋을것 같아요~!

2024-06-08 16:23 UTC, TransparentDeveloper requested changes

2024-06-08 16:23 UTC, TransparentDeveloper commented on src/component/common/nt-time-switch/index.tsx
> +	...props
VoidFunction 타입의 콜백함수도 넘기면 좋을 거 같습니다.

2024-06-08 16:50 UTC, keeprok requested changes
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
수고하셨습니다  병장님 저희 전역까지 달려봐요

2024-06-08 16:50 UTC, keeprok commented on src/component/common/nt-time-switch/index.tsx
> +export type TimeSwitchProps = ButtonHTMLAttributes<HTMLButtonElement> &
저희 props같은경우는 propsType 은 PT를 타입이름 뒤에 붙혀서 사용한다. ex) ButtonPT 이런식으로 컨벤션있어서 수정부탁드릴게요 그리고 index의 NTTimeSwitch 의 props타입 부분이니 NTTimeSwitchPT로 하시면되지않을까요??

2024-06-09 03:17 UTC, HeesikK commented on src/component/common/nt-time-switch/index.tsx
> +		<button
생각해보니 영업시간을 설정하는 버튼은 onClick 이벤트가 필요할 거 같네요..! 

해당 문제 반영해서 다시 올렸으니 확인 부탁 드릴게요😊

- [⚡️ onClick 이벤트 핸들러 추가](https://github.com/mobi-projects/nail-case-client/commit/39bd0e37e3167642c24592d5cfbce3522baf9170)
  - voidFunc 타입의 onClick 이벤트 핸들러 추가 했습니다..!

2024-06-09 03:17 UTC, HeesikK commented on src/component/common/nt-time-switch/index.tsx
> +	...props
해당 문제 반영해서 다시 올렸으니 확인 부탁 드릴게요😊

- [⚡️ onClick 이벤트 핸들러 추가](https://github.com/mobi-projects/nail-case-client/commit/39bd0e37e3167642c24592d5cfbce3522baf9170)
  - voidFunc 타입의 onClick 이벤트 핸들러 추가 했습니다..!

2024-06-09 03:19 UTC, HeesikK commented on src/component/common/nt-time-switch/index.tsx
> +		children?: React.ReactNode
해당 부분도 NTEvent 컴포넌트와 마찬가지로 고려해보면 좋을거 같습니다..! 

추후 퍼블리싱 과정에서 타입의 범위가 넓으면 refactor 할 필요가 있을거 같네요!

2024-06-09 03:25 UTC, HeesikK commented on src/component/common/nt-time-switch/index.tsx
> +export type TimeSwitchProps = ButtonHTMLAttributes<HTMLButtonElement> &
제가 코드 컨벤션을 착각했던거 같네요..! 앞으로 주의하겠습니다👍

해당 부분 수정해서 반영했으니까 확인 부탁드릴게요!

- [🏷️ 컨벤션에 맞게 타입 수정](https://github.com/mobi-projects/nail-case-client/commit/39bd0e37e3167642c24592d5cfbce3522baf9170)
  - 코드 컨벤션에 맞게 타입 수정했습니다(TimeSwitchProps -> NTTimeSwitchPT)

2024-06-09 06:52 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2024-06-09 11:05 UTC, snkchan commented on src/component/common/nt-time-switch/index.tsx
> +		<button
@HeesikK 
- 한가지더!!
- 이부분은 지금당장 반영안하셔도되는데 추후작업할때는 이방법이 더 좋을것 같아서 리뷰남겨둘게요~
```ts
type Prpos = {
 onClick : ()=>void
}
// 위처럼 선언하는것보다
type Prpos = {
 onClick : VoidFunction
}
```
아래처럼 선언하는 편이 더깔끔하겠죠??? 지금당장 동일한코드라서 수정반영은 안하셔도 됩니다 ㅎㅎ
다음부터 VoidFunction으로 선언하는편이 더깔끔할것 같아요 Jeff님에게 배운방법입니다.

2024-06-09 15:22 UTC, keeprok approved these changes

2024-06-09 15:23 UTC, merged