design : custonmer shop aom images
mobi-projects/nail-case-client pull request #226
Opened 2024-09-03 20:41 UTC by keeprok

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

https://github.com/user-attachments/assets/aef5eb36-ed27-4114-b2c7-8fb8e46c0b5d

<div style="display: flex; gap: 10px;">
    <img width="350" alt="스크린샷 2024-09-04 오전 5 22 41" src="https://github.com/user-attachments/assets/7d76841d-9253-4ca6-ae2b-965b543036dc">
    <img width="350" alt="스크린샷 2024-09-04 오전 5 39 16" src="https://github.com/user-attachments/assets/f28bc06b-2b05-4dd3-8b37-8d4b4a38b5e0">
</div>

## [설명]
첨부된 동영상처럼 list는 스크롤시 확인할수있습니다
> - 5개 이상일경우 4개 반만 보여져서 개수 체크 안했습니다 

네트워크 에러 또는 이미지 없을경우 위 사진처럼 나오게 됩니다 
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-09-06 14:13 UTC, snkchan requested changes
- 고생하셨습니다. 디자인 나쁘지 않은것 같은데요??? 이미지 확대해서 보이는 곳에 검은 색배경을 사용하셧는데 프로젝트 전반적인 색상과 잘 어울릴지 감이잘 안오네요 

- PR본문에 올려주신 영상자체의 디자인은 좋은데 전반적인 색상과 어울릴지는 제가 못봐서 모르겠습니다.

## 수정요청

**영상확인해보니 3~7초 사이에 문제점이 확인되네요**

<div align="center">

<img width="482" alt="image" src="https://github.com/user-attachments/assets/34c2d148-f205-4791-8a52-d337ad95e257">

<img width="476" alt="image" src="https://github.com/user-attachments/assets/2e8069f0-a54b-4f7b-86fd-31e270c8e901">



</div>

이미지 원본크기에 따라서 사이즈가 달라지는데 모든 이미지 사이즈가 동일하게 보여야 하지 않을까요??

동일하게 나올 수 있도록 수정 부탁드립니다.

2024-09-06 14:13 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/image-viewer-box/index.tsx
> +				style={{ objectFit: "contain" }}
objectfit속성은 왜 사용하신건가요???

질문의 요지를 모르시겠다면 [해당 글](https://velog.io/@pixartive/%EC%99%9C-%EC%83%88%EB%A1%9C%EC%9B%8C%EC%A7%84-nextImage%EB%8A%94-%EB%8D%94%EC%9D%B4%EC%83%81-objectFit%EC%9D%84-%ED%95%84%EC%9A%94%EB%A1%9C-%ED%95%98%EC%A7%80-%EC%95%8A%EA%B2%8C-%EB%90%90%EC%9D%84%EA%B9%8C)을 한번 읽어보시죠

Image컴포넌트와 관려해서 pr마다 에러사항을 언급해 드렸었는데 이참에 한번 Image컴포넌트를 어떻게 사용해야하고 어떤속성들이 있는지 찾아보시는 편이 어떨까요?

2024-09-06 14:13 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/index.tsx
> +	console.log(shopId)
콘솔 삭제부탁드립니다.

2024-09-07 09:56 UTC, keeprok commented
# 수정사항
- border는 전체 화면부분에서 독단적으로 된것같아 삭제 조치 하였습니다
- 이미지의 크기또한 여백삭제후 사이즈 고정하였습니다

https://github.com/user-attachments/assets/3ce91474-92b9-45ad-af6b-762db9187725

2024-09-07 10:00 UTC, snkchan approved these changes
훔 ..... 세로 비율이 좀 길어서 이상한거같긴하네요.. 우선 배치는 좋은것 같으니 진행하죠 수고하셨습니다.

2024-09-08 14:08 UTC, merged