refactor : customer shop api
mobi-projects/nail-case-client pull request #230
Opened 2024-09-10 15:14 UTC by keeprok

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

## api-v2 (shopById에 맞춰서 수정하였습니다 )
[⚡️ api 맞춰 props수정](https://github.com/mobi-projects/nail-case-client/commit/537901bc20c99f975848e33ac3aa89142de7bb00)
[🎨 AOM 대기 화면 수정](https://github.com/mobi-projects/nail-case-client/commit/7de74529a73dfb94fbd75d355a4cd17c77215e34)
- AOM에 하나빼먹고 올려서 같이 올렸습니다 

## AOM 로딩화면 Customer shop 에 맞춰서 수정하였습니다 
[🎨 AOM 대기 화면 수정](https://github.com/mobi-projects/nail-case-client/commit/7de74529a73dfb94fbd75d355a4cd17c77215e34)
<img width="1276" alt="스크린샷 2024-09-11 오전 12 13 14" src="https://github.com/user-attachments/assets/0935b90a-ebfd-497e-b0e4-7979b940c243">

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-09-10 15:57 UTC, snkchan requested changes
- 고생하셧습니다.
- 전반적으로 pr내용, 제목이 어떤 작업을 했는지 잘 알 수 가없는것 같습니다.
- 리뷰 남긴부분은 수정, 의견 부탁드립니다.

2024-09-10 15:57 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
> +	console.log(data)
- 삭제 부탁드립니다.!

2024-09-10 15:57 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
>  	}
- 로딩 컴포넌트 별도로 분리하면 해당 컴포넌트의 관심사가 확실하게 분리될거 같은데 분리 부탁드립니다.

2024-09-10 15:57 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
> +	if (!error && data) {
- 해당 if문은 필요하지않은 조건문인거 같아요 삭제부탁드립니다.

2024-09-10 15:57 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
>  	} else {
else문 밑에는 더이상 필요없는 코드 같은데 삭제 부탁드립니다.!

2024-09-10 15:57 UTC, snkchan commented on src/component/custom/customer/shop/banner/index.tsx
>  				<NTContent mode="dark">0/0</NTContent>
0/0 은 고정된 텍스트인데 수정이 필요할것 같아요 계획이 있으신가요?

2024-09-10 15:57 UTC, snkchan commented on src/component/custom/customer/shop/banner/index.tsx
>  				<NTContent mode="dark">0/0</NTContent>
0/0 은 고정된 텍스트인데 수정이 필요할것 같아요 계획이 있으신가요?

2024-09-10 15:57 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/aom-skelton/index.tsx
> +			<div className="flex h-[26rem] w-[45rem] items-center justify-center rounded-3xl border-[1.5px] border-black bg-white text-Gray70" />
- 해당 skelton은 전반적인 skelton디자인과 잘 맞지않는것 같은데 어떻게 생각하시나요?
- border만 보여주는것이 더 좋은 스켈레톤이라고 판단하신 이유가 있나요?

2024-09-10 15:57 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/index.tsx
> +			<Price priceImages={shopInfoData.priceImages} />
const  {workHours, address, priceImages} = shopInfoData
이런식으로 구조분해할당 후 사용하면 더 가독성이 좋지 않을까요?
어떻게 생각하시나요

2024-09-10 15:57 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
>  				</div>
- 별도의 컴포넌트로 분리해내면 컴포넌트의 관심사가 확실하게 분리될것 같습니다.

2024-09-11 11:48 UTC, keeprok commented on src/component/custom/customer/shop/banner/index.tsx
>  				<NTContent mode="dark">0/0</NTContent>
이부분은 데이터 부분이니 같이하는게 좋을것같네요

2024-09-11 11:49 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/index.tsx
> +			<Price priceImages={shopInfoData.priceImages} />
이부분은 manager 부분인데요

2024-09-11 13:07 UTC, snkchan commented on src/app/(customer)/shop/[shopId]/page.tsx
> +	if (!error && data) {
@keeprok 
제가 리뷰드린 내용을 확인해보시면 **if문이 불필요하다** 라고 의견을 남겼는데 
shopInfo ==> data로 코드를 수정해주셨네요

수정된것으로 더 효율적인 코드가 되었나요??? 어떤 의도로 수정해주신건가요?

2024-09-12 13:56 UTC, keeprok commented on src/app/(customer)/shop/[shopId]/page.tsx
>  				</div>
[⚡️ 파일구조 변경](https://github.com/mobi-projects/nail-case-client/pull/230/commits/6d2767f098c750854fb68c025ae450c389234e88) 
- Loading포함해서 분리하였습니다

2024-09-12 13:57 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/index.tsx
> +			<Price priceImages={shopInfoData.priceImages} />
[⚡️ props 구조분해](https://github.com/mobi-projects/nail-case-client/pull/230/commits/69fb49770f5a12b6e2767dfa88eed0bc8930ab22) 
 코드가 길어지는게 불편하다고 생각했는데 많아질경우 더좋을것같네요

2024-09-12 14:03 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/aom-skelton/index.tsx
> +			<div className="flex h-[26rem] w-[45rem] items-center justify-center rounded-3xl border-[1.5px] border-black bg-white text-Gray70" />
[🎨 skelton 디자인 변경](https://github.com/mobi-projects/nail-case-client/pull/230/commits/494a8ef06be70251b4a3a45583ba27720faaa13a)
border 삭제하고 색상을 동일시하니 좋게 보이네요

2024-09-12 14:03 UTC, keeprok commented on src/component/custom/customer/shop/banner/index.tsx
>  				<NTContent mode="dark">0/0</NTContent>
[✨ customer- shop- banner 활성화](https://github.com/mobi-projects/nail-case-client/pull/230/commits/3c5227f77cea0fa1388d5a7730846ba01df46f08) 
수정하였습니다

2024-09-12 14:07 UTC, keeprok commented on src/app/(customer)/shop/[shopId]/page.tsx
>  	} else {
밑에 답변드렸습니다

2024-09-12 14:07 UTC, keeprok commented on src/app/(customer)/shop/[shopId]/page.tsx
> +	if (!error && data) {
밑에서 수정후 답변드렸습니다 제가 이해를 잘못해서 글을 작성했습니다

2024-09-12 14:07 UTC, keeprok commented on src/app/(customer)/shop/[shopId]/page.tsx
>  	}
밑에서 답변드렸습니다

2024-09-12 14:11 UTC, keeprok commented on src/app/(customer)/shop/[shopId]/page.tsx
> +	console.log(data)
삭제 하였습니다

2024-09-12 14:20 UTC, keeprok commented
# 수정사항

[🎨 scroll 디자인 수정](https://github.com/mobi-projects/nail-case-client/pull/230/commits/11a61cb788f75c6730fbd9e39ce703a21b1ba919)
<img width="584" alt="스크린샷 2024-09-12 오후 11 14 04" src="https://github.com/user-attachments/assets/dcfe2af0-3304-4820-b490-5029cc15a543">
- 스크롤 색상 변경하였습니다

[✨ shop 전화번호 복사 기능 추가](https://github.com/mobi-projects/nail-case-client/pull/230/commits/ea7a62191fc55eacf567a948daa0d4a0485fbb6e)


https://github.com/user-attachments/assets/ce4828dd-6ae0-46db-9897-294f439a0b4a

- 전화번호 modal 및 클립보드 추가했습니다

2024-09-12 15:08 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/aom-skelton/index.tsx
> +			<div className="flex h-[26rem] w-[45rem] items-center justify-center rounded-3xl bg-Gray20 text-Gray70" />
- 일반적으로 스켈레톤 디자인을 사용하는 경우 "해당 영역에 어떤 컴포넌트가 등장할 것이다".라는 의미를 전달해주기 위해 사용하죠

- 지금 작성된 css를 보니깐 anmation은 적용을 안하셧는데 의도하신걸까요??

- 제가 기존에 만들었떤 skelton ui의 경우 animate-pulse class를 사용해서 번쩍이는 효과를 줬는데요 현재 작업된 내용엔 그게 포함이 안되서 어떻게 생각하시나요?

2024-09-12 15:12 UTC, snkchan commented on src/component/custom/customer/shop/shop-error/index.tsx
> +				</NTButton>
navigateBack 함수를 확인해보니 router.back함수를 사용하셧는데 해당 함수는  이전 경로로 이동하는 함수아닌가요??

button text에는 분명히 **홈으로** 라고 적혀있는데 router.back()을 사용한다면 항상 홈으로 이동할것이다 라고 확신할 수 없을것 같은데 

경로를 직접작성해주는 편이 좋지않을까요?

2024-09-12 15:12 UTC, snkchan commented on src/component/custom/customer/shop/shop-loading/index.tsx
> +				<div className="h-6 w-6 animate-spin rounded-full border-4 border-solid border-PB100 border-t-transparent"></div>
- 혹시 해당 컴포넌트가 loading spinner인가요?? 저희 공용컴포넌트에 스피너가있는데 그걸 사용하는 편이 좋지않을가요?

2024-09-13 11:50 UTC, keeprok commented on src/component/custom/customer/shop/shop-error/index.tsx
> +				</NTButton>
홈으로-> 이전으로 변경하였습니다

2024-09-13 11:50 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/aom-skelton/index.tsx
> +			<div className="flex h-[26rem] w-[45rem] items-center justify-center rounded-3xl bg-Gray20 text-Gray70" />
[✨ animate 기능추가](https://github.com/mobi-projects/nail-case-client/pull/230/commits/deb94de109f1cd4f8649b13d96697e503ac334b2)
 애니메이션 효과때문에 기능저하가 있을거라 예상했지만 잘못생각했던것같습니다

2024-09-13 16:43 UTC, snkchan approved these changes
- 고생하셧습니다.!

2024-09-13 18:48 UTC, merged