design : NTName box 작성
mobi-projects/nail-case-client pull request #24
Opened 2024-06-08 23:18 UTC by keeprok

## 🔥 Issues

* issue:[NAILCASE-65]-(https://nailcase.atlassian.net/browse/NAILCASE-65)
<br/>
<br/>

## 🎯 작업 내용

[🎨 style.css 변경](https://github.com/mobi-projects/nail-case-client/commit/3d6601c8b415b24f17ea74f27f59854347552504)

- BGblue02   추가
- Font-bold 크기 수정'

[🎨 NTNameBox 컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/cbedfcb7d3dddbff255d7e500401898a19e724f4)

- [figma](https://www.figma.com/design/HyKUdbKWOkn6t9M4W0EE3V/Mobi?node-id=0-1&t=GAMQhth0sKzuD4Le-0) 사진과 같게 사이즈 , 폰트 스타일, 굵기 및 위치 설정했습니다  
```ts
"w-[63px] bg- h-[28px] rounded-[8px]  text-Callout text-Gray100 flex items-center justify-center font-SemiBold",
```

<img width="228" alt="스크린샷 2024-06-09 오전 8 02 40" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/08412beb-ce65-40ff-a23e-c44a6703f25f">

### 사용방법
- 위 사진을 예시로 들면 
```ts
bgColor="blue" 
bgColor="yellow"
bgColor="gray"
순입니다 
```
저희 기본색인 PB , PY로 사용을 안한이유는 blue경우 PB가 아닌 BGblue02를 사용중이라 두색 사이에서 혼동이 올수있다고 생각해  
명시적인 색으로 정의 했습니다  

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-09 06:59 UTC, TransparentDeveloper approved these changes
고생하셨습니다. :)

2024-06-09 10:43 UTC, snkchan commented
- <img width="383" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/5f602460-5b9b-4f90-88de-ee809eded265">
- 집중집중!

2024-06-09 10:48 UTC, snkchan requested changes
- 고생하셧습니다~~ 하나만 수정하시면될거 같아요 아마도 해당 css가 적용된지 확인못하신거 같은데 어서 수정부탁드립니다~

2024-06-09 10:48 UTC, snkchan commented on src/component/common/nt-name-box/index.tsx
> +	"w-[63px] bg- h-[28px] rounded-[8px]  text-Callout text-Gray100 flex items-center justify-center font-SemiBold",
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
`"w-[63px] bg- h-[28px] rounded-[8px]` bg-이부분은 잘못들어간것 같습니다.

2024-06-09 11:05 UTC, keeprok commented on src/component/common/nt-name-box/index.tsx
> +	"w-[63px] bg- h-[28px] rounded-[8px]  text-Callout text-Gray100 flex items-center justify-center font-SemiBold",
[🔥 코드삭제](https://github.com/mobi-projects/nail-case-client/pull/24/commits/b6fe95809bd54e954a82f00956614a7b370e6ecd) 
- 수정하였습니다 놓친것같습니다 주의 하겠습니다

2024-06-09 11:14 UTC, snkchan approved these changes
- 굳굳👍👍👍👍👍

2024-06-09 15:29 UTC, HeesikK approved these changes
고생하셨습니다!

2024-06-10 07:13 UTC, keeprok commented
## 수정사항 
[⚡️ variants 객체 키의 이름 변경](https://github.com/mobi-projects/nail-case-client/pull/24/commits/968471091809c91e9d767fac344f34e7aa149366) 
- 지난 회의때 말씀 드린것처럼 variants 객체 키 이름을 디자인 적으로만 구분되서 
- blue , yellow ,gray 를 저희 피그마에 명시되어있는 이름으로 변경하였습니다
- blue -> BGblue
- yellow -> PY
- gray -> Gray
- [⚡️ variants 객체 키의 이름 변경](https://github.com/mobi-projects/nail-case-client/pull/24/commits/29e8aec3a291f3b2ad1613ceda453eecf62e888e) 
- gray 가 변경이안되있어 수정하엿습니다

2024-06-10 07:14 UTC, merged