design : customer shop page
mobi-projects/nail-case-client pull request #251
Opened 2024-10-06 12:58 UTC by keeprok

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

## banner 크기 및 배치 수정
[🔥 불필요 코드 삭제](https://github.com/mobi-projects/nail-case-client/commit/1cbd62f21528056b5ceff5a173f4da7baa035b0f)
- banner 크기 디자인에 맞게 수정하였습니다 
- banner 속 content 위치 수정하였습니다
<img width="1502" alt="스크린샷 2024-10-06 오후 9 02 44" src="https://github.com/user-attachments/assets/f162c399-1baa-4bf0-b151-caa305d16318">

## cardForm 생성및 HourModal 생성
- 이전 디자인이 정보가 과하다는생각이 들어 삭제 조치 하였습니다
- 안내사항 같은 경우 api 추가 될시 첨삭하겠습니다
- cardform생성
[🎨 customerShop cardform수정](https://github.com/mobi-projects/nail-case-client/commit/868020bedbd560f28f3e5985dfc969f2bb841587)
<img width="1252" alt="스크린샷 2024-10-06 오후 9 17 12" src="https://github.com/user-attachments/assets/59dff24a-3677-4bc5-a5a0-0ff9c58a57ef">

-  contetn(text) 버튼 기능추가 
   - > 버튼 뿐만아니라 가격표와 같이 text에서도 이동할수있게 추가 하였습니다
   

[✨ content 버튼 기능 추가](https://github.com/mobi-projects/nail-case-client/commit/2ba6be10e8bddf7b3fae929ac07739b9b60afde1)

https://github.com/user-attachments/assets/d4a1fcc8-3177-4971-9512-37541d00b736

## 운영시간 정보 축소화
cardFrom에서는 오늘 운영시간과 다음날 운영시간의 정보가 제공되게 하였습니다

<img width="184" alt="스크린샷 2024-10-06 오후 9 47 17" src="https://github.com/user-attachments/assets/f0a3575c-8a35-41fd-ba84-f937940a921f">

전체적인 운영시간은 modal 을 통해 쉽게 볼수있게 정리 하였습니다

#### 수정이유
 예약 관련이기때문에 가능한 예약시간을 확인하는게 첫번째라고 생각하였습니다
가게의 전체적인 운영시간을 첫번째로 전부 공개하는것은 오히려 사용자 경험을 망치는부분이라 생각해 수정하였습니다

[🎨 openingHour modal 생성](https://github.com/mobi-projects/nail-case-client/commit/1c79f123347005f0f641aadc03676487cf63e9e3)

<img width="449" alt="스크린샷 2024-10-06 오후 9 17 49" src="https://github.com/user-attachments/assets/48e0ee3d-322f-4fd2-ae31-03a559891757">

## 이달의 아트 
- 이달의 아트를 쉽게 확인할수있는 영역을 나누기 위해 추가하였습니다
[🎨 customer tool bar 생성](https://github.com/mobi-projects/nail-case-client/commit/f419b20fe52fc34560084d315a5ce951ac3020cf)
<img width="197" alt="스크린샷 2024-10-06 오후 9 51 22" src="https://github.com/user-attachments/assets/7d732f14-79a0-45e8-a916-6452f8234777">

- 이달의 아트 보는법을 수정하였습니다
1. 이달의 아트로 전체적인 페이지를 만드는것 보다는 영역을 주는것이 조금더 경험에 낫다고 판단하였습니다
2. scroll 형식보다는 하나하나 집중해서 보는 경험이 더높다고 판단하였습니다
[🎨 customer aom 디자인 변경에따른 수정](https://github.com/mobi-projects/nail-case-client/commit/0c27f7ba49e91c3b4afaf003d10a40e7d718b088)

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-10-06 14:17 UTC, snkchan requested changes

2024-10-06 14:17 UTC, snkchan commented on src/component/common/nt-modal/index.tsx
> +				exSmall: "h-[50vh] min-w-[400px] max-w-[90dvw] p-4 aspect-[8/11]",
- 공용컴포넌트의 사이즈를 변경하셨는데 ... 혹시 다른 페이지에서 사용하는 모달중에 exSmall size를 사용하는 부분은 없는지 체크해보셨나요??

- 공용컴포넌트를 변경하실땐 신중하게 하셔야합니다.. 왜냐하면 여러곳에서 사용되고있는데 현재 필요한곳에서 해당 설정이 맞지않다고 변경할 경우 다른곳에선 문제가 될 수 있거든요 지금 그런 경우같은데 더 좋게 처리할 수 있는방법이 있을탠데 고민해보시겠어요?

- Review이기때문에 해결책도 제시해드리는게 맞는데 Riel님 스스로 고민해 보셧으면 좋겠어서 해결책은 제가 reivew에 포함하지 않겠습니다.

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/custoemr-toolbar/index.tsx
<img width="364" alt="image" src="https://github.com/user-attachments/assets/5112ba35-3199-4fbf-841f-d361ffbe4065">

> 스펠링 틀렸습니다. 수정해주세요

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/index.tsx
> +			<PriceForm priceImages={data.priceImages} />
저번에도 말씀드린것 같은데 컴포넌트 명에 form이라는 단어를 선택하신 이유가있나요???

### 제 의견은 이렇습니다.

일반적으로 저희가 개발에서 form이라는 단어는 `제출` 이라는 의미와 연관되어 있다고 생각합니다.
- 실제로도 이와관련해서 검색해보니 입력값을 받아서 제출하기 위한 용도로 form이라는 단어를 컴포넌트명에 넣는것이 적합하다고 합니다.

### 질문입니다.

저번에 말씀드린것 처럼 form이라는 단어를 유독 많이 사용하신다고 느껴지는데 
컴포넌트명에 form이라는 단어를 사용하실때 Riel님이 생각하시는 form이라는 단어의 의미는 무엇인가요??

분명 어떤 의도를 가지고 form이라는 단어를 사용하셨을탠데 제가 생각하는 form이라는 단어의 의미와는 일치하지 않는것 같습니다.

협업이기때문에 어떠한 `기준`을 가지고 컴포넌트명을 선언하는것이 맞다고 생각합니다.
Riel님이 의미하는 form이라는 단어가 일반적인 기준과 맞지않다면 단어선택을 바꾸는것이 맞지않을까요? 

단순히 컴포넌트명을 봤을때는 form이라는 단어가 포함되었기에 해당 컴포넌트는 어떤 제출이벤트가 일어날 수 있겠구나 라고 오해 할 여지가있을것 같은데

**답글 꼭 부탁드립니다. form이라는 단어를 어떤 의도로 사용하셧는지**
**혹시 form이라는 단어가 컴포넌트명에 꼭 붙어야 한다고 생각하시면 왜 그래야하는지 답글을 남겨주시겠어요?**

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/index.tsx
> +					style={{ transform: `translateX(-${focusedIdx * 33.33}%)` }}
animation을 동작시키기 위해서 코드를 작성해주신것 같은데 혹시 className만사용해서 동작시키는 방법을 못찾으셔서 style속성을 사용해서 코드를 작성해주신걸까요?

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/index.tsx
> +			</div>
기존 코드보다 굉장히 복잡해보이는데 혹시 분리를 안하신 이유가있나요? 혹은 분리예정인가요?

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/card-form/index.tsx
> +					content.map((text, idx) => (
content의 type 선언을 확인해보니 string | string[] 형태로 선언하셨는데 

```ts
{showDot && (
<NTIcon icon="dot" className="mr-[-0.5rem] text-Gray40" />)}						
<div className="whitespace-pre-line break-keep pl-2 pt-[0.375rem] text-Body01">
	 		{text}					
  </div>
</div>
```
해당 코드는 반복되는것 같습니다.

굳이 string이거나 string[] 형태로 구분지어 선언할 필요가 있었을까요??? 혹시 그런 이유가 있다면 답글에 왜 그런지 설명좀 부탁드립니다.

만약 string만올경우가 있고 stirng[] 일경우가 있어서 이렇게 코드를 작성해주신거라면 string[] 타입으로만 선언해도 모두 동작시킬 수 있지않나요?? 

- 한가지 더 저희 컨밴션에 Array<string>으로 작성하기로 되어있는데 수정부탁드립니다.

2024-10-06 14:17 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/work-hour/index.tsx
> +	const workHourSummary: string[] = []
여기도 string[]으로 타입선언 하셧는데 수정부탁드립니다.

2024-10-06 14:18 UTC, snkchan commented
<img width="161" alt="image" src="https://github.com/user-attachments/assets/e54adfbd-a5c1-4b36-8b7d-335877683ab8">

해당카드 컴포넌트에만 location이라는 영어로된 text를 사용하셨는데 이부분은 수정좀 부탁드리겠습니다.

저도 프로젝트의 초반에 임의로 영어text를 조금 사용하려 했었는데 mock님께서 한글사용하는 것으로 의도 하셨다고 하셔서 페이지 전반적으로 거의 한글로된 text를 제공하고 있습니다. 따라서 수정좀 부탁드리겠습니다.

2024-10-06 14:22 UTC, snkchan commented
<img width="156" alt="image" src="https://github.com/user-attachments/assets/5bf34144-b272-4c03-8836-0feb0b7bf073">

## 질문있습니다.

- 오늘 : 00:00 ~ 00:00
- 내일 : 00:00 ~ 00:00
 
연속된 이틀이 모두 영업중이라면 위와같이 보여질탠데

이틀중 하루가 휴무라면? 혹은 이틀모두 휴무라면 어떻게 보여지게 되나요?? 코드상에서 확인이 안되서 어떻게 처리하실 예정인가요?

2024-10-06 14:26 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/index.tsx
> +					style={{ transform: `translateX(-${focusedIdx * 33.33}%)` }}
- 동작에는 문제없긴한데 방법을 몰라서 style을 사용했다 라면 이부분은 해결하고 넘어가셔야 할 것 같습니다.

2024-10-06 14:37 UTC, snkchan commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/location/index.tsx
> +	const locationFun = (address: string) => {
- locationFun이 무슨 단어죠,,,???
**꼭 설명좀 부탁드립니다. 또한 수정도 꼭 해주세요 **
Riel님만 알아볼 수 있는단어를 사용하는 것은 팀프로젝트에서는 지양해주시면 좋겠습니다. 혹시 function의 줄임말이라면 꼭 수정해주세요 

- **위치 함수**라고 직역해 볼 수 있을것 같은데. **위치함수** 가 무슨 함수인지 단어만보고 아실 수 있나요??

2024-10-06 14:37 UTC, snkchan commented on src/constant/toolbar-list.ts
> +] as const
- LABEL_LIST_FOR_CUSTOMER_BASE_TOOLBAR 해당 배열에 "이달의 아트" 텍스트 추가하셨는데 이렇게 하시면 사용자홈에 존재하는 두개의 toolbar에 `홈` `이달의 아트` 이렇게 보이게 될탠데 

기존에 위치한 상단에 존재하는 toolbar는 없어진건가요 혹시?

2024-10-07 14:04 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/location/index.tsx
> +	const locationFun = (address: string) => {
오류사항이있어 삭제 조치 하였습니다

2024-10-07 14:08 UTC, keeprok commented on src/constant/toolbar-list.ts
> +] as const
기존 과 분리 조치 하였습니다
[🚚 파일 이름 변경](https://github.com/mobi-projects/nail-case-client/pull/251/commits/55f25d7bf39906e4fc328924738e526447f343af)

2024-10-07 14:08 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/work-hour/index.tsx
> +	const workHourSummary: string[] = []
수정조치 하였습니다
[🚚 파일 이름 변경](https://github.com/mobi-projects/nail-case-client/pull/251/commits/55f25d7bf39906e4fc328924738e526447f343af)

2024-10-07 14:08 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-details/card-form/index.tsx
> +					content.map((text, idx) => (
수정조치 하였습니다

2024-10-07 14:08 UTC, keeprok commented on src/component/common/nt-modal/index.tsx
> +				exSmall: "h-[50vh] min-w-[400px] max-w-[90dvw] p-4 aspect-[8/11]",
이부분은 이미 확인하고 해결한 문제라 넘어가겠습니다

2024-10-07 14:08 UTC, keeprok commented on src/component/custom/customer/shop/custoemr-toolbar/index.tsx
수정하였습니다

2024-10-07 14:09 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/index.tsx
> +			<PriceForm priceImages={data.priceImages} />
InfoCard 의 형태를 공통적으로 사용하기 때문에 
Form -> Card 로 변경 조치 하였습니다 
조언 주의 하겠습니다

2024-10-07 23:38 UTC, keeprok commented on src/component/custom/customer/shop/shop-content/shop-information/shop-aom/index.tsx
> +			</div>
[🚚 NavigationButton 파일 분리](https://github.com/mobi-projects/nail-case-client/pull/251/commits/c35de73f9571f2dff5c95a11a0ba636eb30d549f) 
파일 분리 하였습니다

2024-10-08 00:27 UTC, snkchan approved these changes
LGTM!

2024-10-09 09:06 UTC, merged