design : NTOption 컴포넌트 작성
mobi-projects/nail-case-client pull request #26
Opened 2024-06-09 17:48 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-74](https://nailcase.atlassian.net/browse/NAILCASE-74)
<br/>
<br/>

## 🎯 작업 내용

- [🎨 NTOption 컴포넌트 작성](https://github.com/mobi-projects/nail-case-client/commit/e883b0409c9eea87f73373e3c600d01d723af746)

# 🎁NTOption 요구사항
<img width="392" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/5de4dd16-be11-4f65-98c0-8e8c2dddd1e8"> <br/>
## 👇Case : default
<img width="396" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/49e7963b-51b1-44d4-a3c5-fb123108ec48"><br/>
## 👇Case : pressed
<img width="372" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/53b87140-8dc5-4387-961f-b73b1dd284e4"><br/>
## 👇Case : disabled
<img width="373" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/b38017a3-85d0-47cf-a22e-4fc409563131"><br/>
# 🛠사용방법
```ts
 function Paraent() {return (<NTOption optionArr={["이달의 시술", "타샵제거 필요", "자샵제거 필요"]} 	size="large"/>
```
- 호출 컴포넌트에서 배열형태의 string을 전달해서 사용하도록 설정했습니다.
- 클릭여부에따라 색상이변해야해서 내부에서 상태를 관리했습니다.
# 의견부탁드립니다.
## disabled에 관해
### 지금상태는?
```tsx
<NTOption  disabled/> //
```
- 위와같은 방법으로 전달하면 내부의 모든 option버튼이 disabled상태로 변하는데 개별 컨드롤이가능하도록 수정해야하는지 잘 모르겠습니다. 설계가아직 어떻게된건지 ..... 모르겠어서 우선 임의로 작업했으니 의견부탁드립니다.
## clickCallback 에 관해
### 지금상태는?
- 현재는 `Array<string>`을 전달받으면 전달받은 text를 기반으로 option컴포넌트가 생성됩니다.
- 고민되는 부분은 클릭체크된 옵션들이 무엇인지 부모컴포넌트에서 알아야하기때문에 clickCallback을 준비해두었는데 혹시 구조가 별로인지 의견부탁드릴게요~
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-10 07:59 UTC, keeprok approved these changes
코드 리뷰를 하다가  cva("", { 빈칸으로 납두면 삭제 하면안되나하고 찾아보니 여러가지를 알게되어 좋은 리뷰 시간이엿습니다 수고하셧습니다 😆

2024-06-10 07:59 UTC, keeprok commented on src/component/common/nt-option/index.tsx
> +	const [isClicked, setIsClicked] = useState(false)
아 이 컴포넌트는 내부에서 상태를 관리 하네요 개인적인 의견이지만 저희 가 Doc 를 안쓰기로 해서 pr에 설명을 적기로 했는데
다른 공용컴포넌트의 경우 "use client" 를 안쓰는곳이 많아서 설명에 적혀있었으면 좋았을것같다는 의견입니다

2024-06-10 09:59 UTC, HeesikK approved these changes
>> 위와같은 방법으로 전달하면 내부의 모든 option버튼이 disabled상태로 변하는데 개별 컨드롤이가능하도록 수정해야하는지 잘 모르겠습니다. 설계가아직 어떻게된건지 ..... 모르겠어서 우선 임의로 작업했으니 의견부탁드립니다.

정확히는 설계가 완전히 되어야 알 거 같지만 옵션이면 개별적으로 컨트롤이 가능해야 될 거 같아용..! 이 부분은 추후에 모카님한테 의견 여쭤보고 수정하면 좋지 않을까요?

퍼블리싱 단계에서는 이대로 진행해도 괜찮지 않을까 생각이 듭니당🫠

2024-06-10 13:53 UTC, TransparentDeveloper requested changes
고생하셨습니다 :)

### "disabled" 에 대해서,,
- disabled 설정 시, 해당 컴포넌트 전체가 동작 불능이 되도록 설계되는 게 맞아보입니다.!

2024-06-10 13:53 UTC, TransparentDeveloper commented on src/component/common/nt-option/index.tsx
> +					size={size}
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
clickCallback 의 타입이 `VoidFunction` 인데, 현재 선택된 값을 알기 위해선, 
`(string) => void` 로 되어야하지 않을까요?

아래와 같이 사용하기 위해서요.!

```tsx
export default function () {
  const [selectedOption, setSelectedOption] = useState<string|null>()
  const onClickOption = (option:string) => {
     setSelectedOption(option)
  }
  return (
      ...
      <NTOption clickCallback={onClickOption}>
      ...
  )

}
```

2024-06-10 13:53 UTC, TransparentDeveloper commented on src/component/common/nt-option/index.tsx
> +	const [isClicked, setIsClicked] = useState(false)
# Request Level

  - [x] "🚧 재고해주시길.."


# Description


저도 내부에서 상태관리할 필요가 없다고 생각합니다.

각 NTOptionSingle 에, 선택이 되었는지만 확인할 수 있는 boolean 형 prop 만 넘겨주면 되지 않을까요?

2024-06-10 13:55 UTC, TransparentDeveloper requested changes
### "disabled" 에 대해,,

disabled 설정 시, 해당 컴포넌트 전체가 동작 불능이 되도록 설계되는 게 맞아보입니다.!

2024-06-10 19:12 UTC, snkchan commented
# 🎉확인해주세요!!
- [⚡️ useOption() 생성](https://github.com/mobi-projects/nail-case-client/pull/26/commits/31df6c8b04c275d53d59527887cb05ec2c25675f)
- [⚡️ 외부에서 상태를받아 사용하도록 refactor](https://github.com/mobi-projects/nail-case-client/pull/26/commits/4b79175c8da6968f4d727530f159d6e0f87b423c)
## 🤔이전에는?
```tsx
// NTOptionSinge 컴포넌트에서
const [isClicked, setIsClicked] = useState(false)
	return (
		<button onClick={() => {setIsClicked((prev) => !prev)} /> 
// 내부에서 click여부를 판단하는 상태가 존재했습니다. 하지만 이는 불필요한 상태라서 외부에서 하나의 상태를 받도록수정했습니다.			
```
## 😎수정후에는?
### Step1 **(useOption)**
```ts
export const useOption = (initialOptionList: Array<string>) => {
	const optionArr = initialOptionList // hook 생성시 옵션목록 초기화

	const [checkedOption, setCheckedOption] = useState<Array<string>>([]) 
// 외부에서 어떤옵션을 체크했는지 파악하기 위한 상태 추가

	const onClickOption = (option: string) => {
		setCheckedOption((prevList) => {  
			return prevList.includes(option) // 옵션을 클릭했는데 option이 기존 체크된 옵션에 존재하는지?
				? prevList.filter((item) => item !== option) // 기존배열에 포함이라면 배열에서 제거
				: [...prevList, option] // 기존배열에 없다면 option을 추가
		})
	}
	return { onClickOption, checkedOption, optionArr }
}
```
### Step2 **(호출 컴포넌트에서)**
```tsx
export default function Paraent() {
	const { checkedOption, onClickOption, optionArr } = useOption(["목록","초기","옵션","추가"]) 
	// hook을 호출하면서 동시에 option을 초기화
	
	return (
		<main>
			<div className="m-20 flex gap-2">
				<NTOption {...{ checkedOption, optionArr, onClickOption }} /> // 간단하게 hook의 return값을 전달
			</div>
		</main>
	)
}
```

### Step3 **(NTOption 에서 어떻게 동작하나요?)**
```tsx
		<div >
			{optionArr.map((option, idx) => (
				<NTOptionSingle
					isClicked={checkedOption.includes(option)} // 선택목록에 option이 있다면 클릭된상태 아니라면 !isClicked
					onClickOption={() => {
						if (onClickOption) onClickOption(option)
					}}
				>
					{option}
				</NTOptionSingle>
			))}
		</div>
```

2024-06-10 19:14 UTC, merged

2024-06-11 02:26 UTC, TransparentDeveloper reviewed
확인했습니다.

훨씬 더 직관적으로 변했네요.!