config : global.css 작업
mobi-projects/nail-case-client pull request #3
Opened 2024-05-30 08:16 UTC by keeprok

## 🔥 Issues

* issue : [NAILCASE-38](https://nailcase.atlassian.net/browse/NAILCASE-38)

<br/>
<br/>

## 🎯 작업 내용

[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78)
- 현재 저의 [figma](https://www.figma.com/design/HyKUdbKWOkn6t9M4W0EE3V/Mobi?node-id=144-1313&t=0AzwTbwBt6tz70E1-0) 에서 정의 된 디자인 의 네임에 따라 color및 font의 토큰을 설정및 정의 했습니다 또한 BGblue02,03의 경우 생길예정이다라고 디자이너분께 전달받앗으나 주석의 경우 최대한 만들지 않기로 해 추가 될경우 style추가로 넣겠습니다

[✨ barrel file 설정](https://github.com/mobi-projects/nail-case-client/pull/3/commits/20e647e0393716ba412527ff38ca519a23f46784)
- [tailwind본문](https://tailwindcss.com/docs/font-size) 에서 알수있듯이 폰트를 하나의 커스텀으로 정의 할수있는 방법이 있어 토큰 정의 후 config에 사용했습니다
- fontWeight의 경우 추가적으로 변경할거라는 것이 피그마에 작성되어 따로 추가해뒀습니다 

[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6)
- 글로벌의 경우 아직 픽스된게 많지않아 h1~h4를 폰트의 각 1번을 넣어뒀고 
- button의 경우 단독 색인 BGblue를 넣고 크기의 경우 가장많이 사용하는h-[54px] w-[118px] 사이즈, 사이즈에 사용한는 rounded-[12px] 또한  넣었습니다 
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

[NAILCASE-38]: https://nailcase.atlassian.net/browse/NAILCASE-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-30 08:53 UTC, snkchan commented
- <img width="227" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/97c648e2-9b18-4985-bdf8-81b79c90318f">
-`Config/global.css 작업` 라고 PR제목적어주셧는데 어제 회의때 얘기했던 것처럼 pr 제목 컨밴션 맞춰서 수정부탁드립니다.

2024-05-30 09:31 UTC, snkchan requested changes
- 고생하셧습니다. 하나씩 차근차근 수정해봅시다~~

2024-05-30 09:31 UTC, snkchan commented on src/libs/tailwind-css/global.css
- global.css작업이 제대로 안된것 같습니다.
- h1,h2,,,...h태그의 경우 기본적으로 font-size가 어떻게 된다라는 것을 정의하지않으면 모두 똑같은 font-size가적용되는데 지금 작업에서 이런부분을 작성해주셔야하는데 그 외의 것들이 작업되있는것 같아요.
- [global.css](https://velog.io/@e_juhee/Global-CSS)에대해 검색해보시면 어떤 작업을 하는 것이다라는 내용이 있는데 global.css의 역할을 정확하게 아셔야할것 같습니다.
> Global CSS는 default값이다.
다른 스타일을 적용하고 싶으면 원래 하던대로 스타일을 지정하면 된다.
💡 why?
css(cascading style sheet): 가장 최상위에서 스타일을 적용하면 자식이 덮어씌워지게 된다.
자식에 스타일을 지정하면 자식에서는 그 스타일이 우선시 된다.
- global.css에서는 전체 html태그에서 default값들을 설정해주는 파일이라서 특정 html태그가 공통적으로 가지는 style들만 정의해주시면 될것 같아요.
-  그 외 저희가 실제로 사용할 컴포넌트들은 `component > common` 에서 해당 컴포넌트를 정의할때 직접 style을 적거나 props로 받는경우 tailwindcss의 cn() 을 사용해서 어떤 값들이 올 수 있다라는 경우의수에 맞는 스타일을 적용하는 방법으로 작성될 것 같습니다.

2024-05-30 09:31 UTC, snkchan commented on src/libs/tailwind-css/global.css
> +		border: none;
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
@apply뒤쪽으로 정의된 utilclass를 사용해서 스타일을 추가해주셔야될 것 같아요.
- `@apply bg-BGblue01 text-pb100;` 이부분은 utilclass를 사용하고 그아래 css를 적는것보다 
```ts
ex)
button {
		@apply bg-BGblue01 text-pb100 border-none rounded-[12px] px-[12px] py-[24px];
```
이런형식으로 적을 수 있지않을까요?

2024-05-30 09:31 UTC, snkchan commented on src/libs/tailwind-css/global.css
> +		border: solid;
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
-`global.css`파일에 직접 
```ts
.btnBlue {
		@apply bg-pb100 text-white;
	}
	.btnGray {
		@apply bg-gray10 text-gray50;
	}
	.btnWhite {
		@apply bg-white text-gray50 border-gray30;
		border: solid;
```
형식으로 클래스명을 사용해서 스타일을 정의해주셧는데 이부분은 사용안하는 편이 좋을것 같아요.
- tailwindcss를 사용하기때문에 utilcalss를 사용하고있습니다. 따라서 직접 클래스명에 스타일을 부여하는 편은 지양하고 `tailwind.config.ts`에 직접 추가한 스타일토큰을 사용해서 스타일 주시는 편이 좋을것같습니다.

2024-05-30 09:31 UTC, snkchan commented on tailwind.config.ts
> +				...COLORS.BGblue,
- 더 좋은 방법이 있을것 같습니다..! 방금 얘기한것처럼 수정해주시면 좋을것 같아요.

2024-05-30 09:31 UTC, snkchan commented on tailwind.config.ts
> +				],
- 이부분은 전체적으로 수정이 필요할것같아요.
- `global.css`는 전체적인 html에 스타일을 적용해주는 파일입니다.
- `tailwind.config.ts` 라는 파일은 파일명 그대로 tailwind의 config(= 설정 === 토큰등록) 을하는 파일이라고 이해해주시면 좋을것 같아요.
- 따라서 fontSize라는 키값아래에서는 fontSize만 등록해주셔야하는데 style을 적용시켜주셧죠 지금작업에서는??? 
- fontSize, fontWeight,등등 해당 키값에맞는 토큰을 등록한후 _(여기서 `토큰`이라는 의미는 utilclassName 을 등록 한다는 의미입니다)_
  - utilclass란 저희가 tailwind에서 사용해왔던 이미정의된 이름입니다. flex,items-center와같이 특정css를 주기위해 이름을 붙혀서 사용하죠 이와 마찬가지로 여기서 css명을등록한다고 이해해주세요~
- 정리하자면 config에서 토큰을 등록한후 등록한 토큰을가지고 global.css파일에서 토큰을 이용해서 style을 적용하고, 또한 저희가앞으로 작업할 html요소들에 등록된 토큰을 이용해서 css를 적용해주기위해서 config파일을 작업한다.!! 라고 이해해주시면 좋을것 같아요 이게 사용목적입니다.

2024-05-30 09:31 UTC, snkchan commented on tailwind.config.ts
- design팀에서 fontWeight에대해서 따로 blod,sm와같이 굵기와 관련된 이름을 따로 정해주지않았다면 fontWeigh는 설정안해주셔도 될수도있습니다. 기본적으로 tailwind에서 text-bold와 같이 정의된 굵기들이있기때문에 이부분은 figma확인후 작업해주시면될것 같아요.

2024-05-30 09:39 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-05-30 09:39 UTC, TransparentDeveloper commented on src/libs/tailwind-css/styles.ts
> +	},
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 속성이름의 형식,, 일관성이 없어요..ㅜㅜ
- 하나로 통일하는게 어떨까요?
- 디자이너님께서 그렇게 이름을 그렇게 명명하셨다면, 통일해달라고 요청해서 같이 맞춰가는 편이 좋을 것 같습니다:)

2024-05-30 09:39 UTC, TransparentDeveloper commented on src/libs/tailwind-css/global.css
> +	}
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


# Description
- 클래스명으로 버튼의 스타일을 구분지어주신 것 같은데, 이건 global.css 에서 작성할 내용이 아닌것 같습니다.
- global.css 는 말 그대로 프로젝트 전반에 사용될 일반적인 스타일을 정의해야합니다..
- 지금 작성된 부분은 버튼에 대한 굉장히 구체적인 스타일 내용을 포함하고 있어요,,  
- 추가로 잘못 사용될 여지도 있죠. 👇 처럼 사용해도 오류 없이 그냥 출력되어 버리지 않을까요?
```ts
<p className="btnGray">난 버튼 아닌뎅? 🤪</p>
```

2024-05-30 09:39 UTC, TransparentDeveloper commented on src/libs/tailwind-css/global.css
> +	}
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"


# Description
- 버튼과 마찬가지로 너무 구체적인 설정이에요.
- 이렇게 사용될 경우, 프로젝트에서 사용될 모든 `p` 태그는 위 설정의 영향을 받을 거예요.
- 미리 그렇게 정했다면 모를까, 디자이너님이 따로 명시한 내용도 없고 FE 팀끼리로 얘기 나온 적 없는 설정이에요.. 수정 부탁합니다.

2024-05-30 09:39 UTC, TransparentDeveloper commented on src/app/layout.tsx
>  import type { Metadata } from "next"
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"


# Description
- `libs` 폴더는 왜 등장했을까요??
- 최근 회의 때, src 바로 아래 사용할 폴더에 대한 내용을 정리했던걸로 알고 있습니다. 다시 확인 부탁드립니다.
- barrel-file 도 사용하자고 했었습니다.!

2024-05-30 09:45 UTC, snkchan commented on src/libs/tailwind-css/styles.ts
> +	},
- 좋은방법인거같습니다. 디자이너와의 협업이 처음이라 이런부분은 요청해서 해결하는게 좋을것 같네요🎉👌

2024-05-30 10:59 UTC, keeprok commented on src/libs/tailwind-css/global.css
> +	}
삭제 조치 하겠습니다 global에 관해 잘못이해한거같습니다

2024-05-31 02:21 UTC, HeesikK requested changes
고생하셨습니다!

2024-05-31 02:21 UTC, HeesikK commented on src/libs/tailwind-css/styles.ts
> +	py50: "#F8FCA9",
# Request Level


  - [x] "🚧 재고해주시길.."


# Description

- pb와 py도 좋지만 처음 봤을때 어떤 색상인지 정확하게 파악하기 어려울거 같은데 더 직관적인 이름을 사용하면 좋을거 같습니다. 
- css명이 조금 길지만 이 부분은 줄이지않고 디자이너 분이 적은대로 primaryBlue, primaryYellow 이렇게 사용하는게 어떨까요?
![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/929b9b18-71b7-4356-8ba9-12ff12eb7f73)

2024-05-31 02:21 UTC, HeesikK commented on src/libs/tailwind-css/styles.ts
> +	itle02: {
- 해당 부분 오타 수정 부탁 드릴게요! 
itle02 → Title02

2024-05-31 02:21 UTC, HeesikK commented on src/libs/tailwind-css/styles.ts
> +	headline02: {
- 해당 부분 오타 수정 부탁 드릴게요! 
headline02 → Headline02

2024-05-31 07:00 UTC, keeprok commented on src/libs/tailwind-css/styles.ts
> +	headline02: {
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78) 오타 수정했습니다!!

2024-05-31 07:01 UTC, keeprok commented on src/libs/tailwind-css/styles.ts
> +	itle02: {
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78) 오타 수정했습니다

2024-05-31 07:02 UTC, keeprok commented on src/libs/tailwind-css/styles.ts
> +	py50: "#F8FCA9",
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78) 이부분은 PB,PY부분은 첫부분을 제외하고 그다음부분부터는 요약한 형태로 생성되있어서  정의 했습니다

2024-05-31 07:04 UTC, keeprok commented on src/app/layout.tsx
>  import type { Metadata } from "next"
[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6) 이부분은 파일 name 컨벤션에 맞춰 수정했고 global.css부분같은 경우 export 가없어서 따로 배럴파일을 할려면 * from "./"이렇게 전체 포함을 해야되서 포함하지 않았습니다

2024-05-31 07:05 UTC, keeprok commented on src/libs/tailwind-css/global.css
> +	}
[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6) 삭제 조치 하였습니다

2024-05-31 07:06 UTC, keeprok commented on src/libs/tailwind-css/global.css
> +	}
[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6) 삭제 조치 하였고 현재 피그마에서 정의 된사이즈중 하나의 크기에 맞춰 수정하엿습니다

2024-05-31 07:08 UTC, keeprok commented on src/libs/tailwind-css/styles.ts
> +	},
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78) 이경우 White- Black까지 하나의 계열로 정의 하시고 PY-PB는 단축이라고 하셔서 피그마정의 맞게 수정하였습니다 또한 font의 경우 tailwind의 config정의 에 나온부분의형식을 사용햇습니다 
[✨ barrel file 설정](https://github.com/mobi-projects/nail-case-client/pull/3/commits/20e647e0393716ba412527ff38ca519a23f46784) 이부분에 스타일 토큰 넣은 형식 포함 시켰습니다

2024-05-31 07:12 UTC, keeprok commented on src/libs/tailwind-css/global.css
> +		border: none;
[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6) 수정하엿습니다 또한현재 p 의 경우 픽스 되지않아 삭제 했습니다

2024-05-31 07:14 UTC, keeprok commented on src/libs/tailwind-css/global.css
> +		border: solid;
[🔧 global.css정의](https://github.com/mobi-projects/nail-case-client/pull/3/commits/d830e914c5bd9b17ca3b80c1f7dac69a8ebebbf6) 클래스로 된부분은 삭제 조치 하였고 기본 button만 정의 했습니다

2024-05-31 07:15 UTC, keeprok commented on src/libs/tailwind-css/global.css
감사합니다 제가 잘못이해한부분을 정확히 봐주셔서 감사합니다 앞으로 공부방법에 다시 생각해야겠네요

2024-05-31 07:17 UTC, keeprok commented on tailwind.config.ts
> +				...COLORS.BGblue,
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78)스타일토큰을 재정의 후
[✨ barrel file 설정](https://github.com/mobi-projects/nail-case-client/pull/3/commits/20e647e0393716ba412527ff38ca519a23f46784) 한번에 넣는 방식으로 했습니다

2024-05-31 07:20 UTC, keeprok commented on tailwind.config.ts
> +				],
[🍱 스타일 토큰 생성](https://github.com/mobi-projects/nail-case-client/pull/3/commits/60829106d60363d72070b9f8f5d06849a6254e78) 
- 이부분은 토큰에서 정의 후 config에  tailwind본문에 맞는 형식에 맞게 넣엇습니다

2024-05-31 07:28 UTC, snkchan commented on src/config/tailwind/global.css
> +		@apply grid justify-items-start;
- input태그인데 grid를 사용할 필요가 있을까요??? 왜 주신거죠?

2024-05-31 07:39 UTC, keeprok commented on src/config/tailwind/global.css
> +		@apply grid justify-items-start;
[🔥 �global에 맞지않는 코드 삭제](https://github.com/mobi-projects/nail-case-client/pull/3/commits/c0d16e0a27e83f90ff6f381c23edfea2137beff0) 삭제 조치 했습니다

2024-05-31 09:23 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍👍

2024-05-31 09:23 UTC, TransparentDeveloper commented on tailwind.config.ts
> +			},
# Request Level

  - [x] "🚧 재고해주시길.."


# Description
- 전에 Chan 님이 의견 주셨던 것과 같은 입장입니다.
- `fontSize` 속성에 대한 값을 부여하는데, fontStyle 이란 객체 안에는 `fontSize`, `fontWeight`, `lineHeight` 속성 또한 포함되어있어요. 
- 그 때문에, fontStyle 객체의 형식도 단순함을 잃었어요;;

```tsx
Caption02: [
		"12px",
		{
			fontWeight: 300,
			lineHeight: "16px",
		},
	],
```

- 저는 지금까지 `taiilwind.config.ts` 파일에선, font-weight, font-size, border-ruidus, color 등등 프로젝트에서 사용할 css 값의 범위를 지정하는 용도로 활용했어요.
  - _(쉽게 말해서 프로젝트에서 파란색을 쓴다고 하면, 파란색으로 활용할 색상코드 1,2,3,.. 이런식으로만 활용했어요.)_
- 지금 riel 님은 그 이상의 것을 이 파일에서 해결하시려는 것 같아요. 
- 프로젝트에서 사용될 fontsize, fontweight , line-height 이런 것만 지정해주면 이 파일에서 할일이 끝나지 않을까요?
- 그 설정 값을 조합하는 건, 이 파일 바깥에서 이뤄지는 게 적절하지 않을까 생각합니다.!

2024-05-31 09:30 UTC, TransparentDeveloper requested changes

2024-05-31 09:30 UTC, TransparentDeveloper commented on src/config/tailwind/global.css
> +	}
# Request Level
  - [x] "🚧 재고해주시길.."


# Description
- 전에 말씀드렸다시피, 일반적이지 않고 구체적인 설정입니다.
- 구체적인 설정은 global.css 에 두는 건 적절치 못합니다.
  - 위의 설정대로라면, 우리 프로젝트 내에서 사용되는 (button 태그를 기반으로한) 모든 컴포넌트는 기본 높이(54px), 너비(118px), 배경색상(파란색 계열) 을 갖도록 되어버립니다.
- 현재 그렇진 않지만, 나중에 다른 스타일의 버튼 공용 컴포넌트를 3개 (ex: icon-button, text-button, link-button 등등) 를 만들자는 얘기가 나오면 이런 구체적인 설정이 거슬리지 않을까요?

2024-05-31 09:45 UTC, snkchan commented on tailwind.config.ts
> +			},
- 이부분은 사용하는 편이 좋지않을까요???
- 이전까지는 저희가 디자인팀이없었기때문에 직접 텍스트의 사이즈를 임의로 설정해서 사용해왔습니다.
```tsx
<div className = "text-sm"/>
<p className = "text-lg "/>
<p className = "text-[12rem] "/>
```
과 같은 형식으로 말이죠. 이렇게 작업한 이유는 정확한 figma디자인이 없었기때문입니다.
-moka님께서 작업해주신 figam에가서 확인해보면 다음과 같이 설정되있는걸 확인할수 있습니다.
-<img width="824" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/c5abb199-cd1d-494e-ab94-e24a79161a17">
- <img width="535" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/3c2e6d0c-dd48-49f2-8081-18b503574c9e">
- 이렇게 모든 text에대해서 양식에 정해진 이름을 사용해서 text를 사용한걸 확인했습니다.
- -----
### 만약지금 Riel님이 작업해주신부분이 없다면 저희가 작업할때 fontSize설정을 이렇게해야합니다.
_(figma에서 moka님이 설정해주신 font양식입니다.)_
- <img width="466" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/6041ce65-aae5-43ea-bfbd-f61d0bb06d11">
```tsx
LargeTitle 의 styled을 가지는 text를 작성한다면 ??

<h1 className = "font-semiBold text-[28px] line-height-[38px]"/> 
config에 utilclassName을 등록해둔다면???
<h1 className = "font-largetitle"/> 
```
이렇게 사용하는 편이 더 효과적이지 않을까요???

2024-05-31 11:35 UTC, TransparentDeveloper commented on tailwind.config.ts
> +			},
```ts
<h1 className = "font-largetitle"/> 
```
이처럼 사용하는 것에는 완전 동의&공감합니다.!
하지만, 어떤 효과를 만들어내는 것에 있어 최소한의 의도는 지켜져야 한다고 생각해요.

tailwind.config.ts 는 프로젝트에서 전역에서 사용할  **설정값** 을 지정해야하지 않을까요?
fontSize, color, border-radius,.... 이런 값을 말이죠.
(이전 프로젝트에서도 우린 항상 그렇게 해왔었어요.)

그런데 이번건 조금 달라보여서 의견 남겼습니다.
지금은 값을 지정한게 아니라, tailwind.config.ts 에서 **조합** 해버렸어요. 
정확히는 애초에 조합이 된 객체를 만들어 부여했죠.

제가 신경이 쓰이는 건 크게 두가지입니다.

- ①. `fontSize` 속성 값으로 (`fontSize`, `fontWeight`, `lineHeight`) 조합을 넣는게 적절할지?

- ②. 나중에 순수히 fontSize 속성만 필요한 공용컴포넌트를 설계해야할 때, 그 때 조합을 분리해야하는 게 아닌지?
  - <img width="261" alt="스크린샷 2024-05-31 오후 8 11 34" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/61536938-6d61-44b2-bf90-f6396acc38ed">
  - 👆 이렇게 설정이 되어버린 이상, 이젠 저흰 `fontSize` 와 관련하여 피그마에 명시된 값을 사용할 수 없어요.
  - tailwind-css 에서 기본적으로 제공하는 걸 사용하던지, (`fontSize`, `fontWeight`, `lineHeight`) 다른 조합을 만들어내야합니다.

`fontSize`, `fontWeight`, `lineHeight` 에 대해선 사용할 값의 목록이 나와있으니, 
 각각 등록해 둔다면, 설정 의도에 부합하고 이후 디자인 할때 확장성 있게 사용할 수 있을 겁니다.

----

구체적으로 저는 아래와 같이 이 문제를 해결할 것 같아요.
일단 tailwind.config.ts 에서는 값만 등록합니다.
```ts
const config: Config = {
	...
	theme: {
		extend: {
			colors: {....},
			fontSize: {....}, // 👈 폰트 크기 값 목록
			fontWeight: {....},  // 👈 폰트 굵기 값 목록
			lineHeight: {....},  // 👈 줄간격  값 목록
              
		},
	},
	plugins: [],
}
export default config
```

이후 조합을 해야하니,, 두가지 방법이 떠올라요.
1. 전에 말씀드렸던 것처럼 공용컴포넌트로 분기시킬 수 있고,,
2. 커스텀 클래스를 선언할 수도 있죠.


### 1 방법 대로 하면,

#### 컴포넌트 선언
```tsx
const typographyVariants = cva('whitespace-pre-line text-wrap', {
	variants: {
		type: {
			LargeTitle: '.....',
			Title01: '.....',
			Title02: '.....',
			Title03:  '.....',
			Headline01:  '.....',
			Headline02:  '.....',
			Body01:  '.....',
			Body02: '.....',
			Callout: '.....',
			Caption01:  '.....',
			Caption02: '.....',
		},
	},
	defaultVariants: {
		type: 'Body01',
	},
})

export const Typography = forwardRef<HTMLParagraphElement, TypographyProps>(
	({className, type, ...props}, ref) => {
		return (
			<p
				className={cn(typographyVariants({type}), className)}
				ref={ref}
				{...props}
			/>
		)
	},
)
Typography.displayName = 'Typography'
```
#### 컴포넌트 사용
```
<Typography type="LargeTitle">큰 글자</Typography>
```

### 2 방법 대로 하면,
#### @layer utilities 블록 생성
```ts
@layer utilities {
	.LargeTitle {
		@apply text-... font-... leading-...;
	}
	.Title01 {
		@apply text-... font-... leading-...;
	}
	.Title02 {
		@apply text-... font-... leading-...;
	}
	.Title03 {
		@apply text-... font-... leading-...;
	}
	.Headline01 {
		@apply text-... font-... leading-...;
	}
	.Headline02 {
		@apply text-... font-... leading-...;
	}
	.Button {
		@apply text-... font-... leading-...;
	}
	.Body01 {
		@apply text-... font-... leading-...;
	}
	.Body02 {
		@apply text-... font-... leading-...;
	}
	.Callout {
		@apply text-... font-... leading-...;
	}
	.Caption01 {
		@apply text-... font-... leading-...;
	}
	.Caption02 {
		@apply text-... font-... leading-...;
	}
}

```

#### 사용
```tsx
<h1 className = "LargeTitle">큰 글자</h1> 
```


글이 너무 길어져서 죄송하지만, 제가 드리고 싶은 말씀은 이렇습니다.

각각의 속성을 조합해서 
```tsx
<h1 className = "LargeTitle">큰 글자</h1> 
```
👆 이런 형식으로 사용할 수 있게 만드는 방법은 얼마든지 더 있을 겁니다.

다만 tailwind.config.ts 파일에서 조합된 값을 부여하는 건, 제가 위에 적었던 내용을 봐주시고, 재고해주실 것을 부탁드립니다.!

2024-05-31 12:23 UTC, snkchan commented on tailwind.config.ts
> +			},
- Jeff님 의견 잘 읽었습니다. 제가 설득을 해보겠습니다. 한번 읽어보시죠 ㅎㅎ
## P : tailwind.config.ts 는 프로젝트에서 전역에서 사용할 설정값 을 지정해야하지 않을까요?
## Answer
- `우선 전역에서 사용할 설정값`이라는 의미를 저는 이렇게 생각합니다.
> 프로젝트에서 사용할 tailwindcss의 설정을 custom할수있는 파일
- 저는 `tailwind.config.ts`파일의 역할을 이렇게 이해했습니다.
- -------
## P : ①. fontSize 속성 값으로 (fontSize, fontWeight, lineHeight) 조합을 넣는게 적절할지?
## Answer
- 저또한 그렇게 생각하고 [공식문서](https://tailwindcss.com/docs/font-size#customizing-your-theme)를 확인해봤습니다. 저기서 확인해보시면 이렇게 사용하고 있더라고요.
- <img width="604" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/467fb4ff-ff48-41c2-a5df-2397b6f75822">
- 공식문서에서 확인할 수 있듯이 tailwindcss는 이런식의 사용방법을 지원해줍니다.
- 이사용방법이 문제가 되지않을것이라 판단한 이유는 다음과 같습니다.
- <img width="499" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/5de7b29e-3b47-4108-9ae9-902fd0717197">
- 공식문서에서 보시면 이미저희가 자주사용해 왔던 
`text-sm, tsxt-lg ....`와같은 utilclass또한 내부적으로 위와같은 설정이 포함되어있기때문입니다.
- `default`로 설정되어있는 설정이 맘에들지 않는다면 설정을 변경할 수 있고 또한 위와같은 설정방법을 사용해서 cutom className도 사용할 수 있다라고 이해했습니다.
- 따라서 지금Riel님 작업에서 설정한 방식은 tailwindcss의 의도에 적절한 방식이라고 생각합니다.



- -------
## P : ②. 나중에 순수히 fontSize 속성만 필요한 공용컴포넌트를 설계해야할 때, 그 때 조합을 분리해야하는 게 아닌지?
## Answer
- 물론 지금 제안해주신 방식처럼 다른 방식으로 동일한 효과를 낼 수 있습니다.
- 저희가 fontSize를 현재 Riel님이 정의해주신대로 사용한다해도 fontSize만사용하고싶다면  기존에 있던 utilClass를 사용하면 문제가없는것 아닐까요?
```tsx
<h1 className= "font-sm"/>
<h1 className= "font-[1px]"/>
<h1 className= "font-[10rem]"/>
```
- 만약 moka님께서 추가적으로 `12px = "AA" 18px="BB`와 같은 이름을 부여하신다면 이렇게 설정해서 해결 가능하다고 생각합니다.
```tsx
fontSize: {
   ...fontStyle, // Riel님께서 작업한 설정입니다.
   ...fontMoka, // 이렇게따로 추가해서 사용가능하지않을까요?
},
```
## 제 의견은 이렇습니다.
```ts
// 📍global.css

@layer utilities {
	.LargeTitle {
		@apply text-... font-... leading-...;
	} 
.......
```
- 이런방법을 제안해주셧는데 이방법은 tailwind라이브러리의 목적과 부합하지않는다고 생각합니다.
> tailwind는 클래스명으로 css를 관리하지 않고 빠르게 utilClass로 css를 작업할 수 있게 도와주는 라이브러리라고 이해하고있습니다.
> 따라서 클래스명을 직접이용해서 해결하는 방식은 tailwind의 의도와는 맞지않다고 생각합니다.

- 또 다른 방법으로는 컴포넌트를 직접생성할때 Jeff님의 의견대로
`fontSize, fontWeight`등의 토큰들을 직접 컴포넌트에서 조합해서 스타일을 입히는 방식이 있겟죠?? 물론 이방법외에도 같은효과를 내는 여러방법이 있을것입니다.
### config에서 설정하면 관리의 편의성이 더 좋지않을까요?
- 위에서 본것처럼 여러방법이 있을거지만 config라는 하나의 설정파일에서 이것들을 관리한다면 관리point가 줄어들고 팀원들끼리 공유할 내용이 줄어들어서 더 효과적이지 않을까 생각합니다.
## 결론
- 여기까지가 저의 의견이었는데 그럼에도 이방법이 좋지않다고 생각하신다면 저희가 기존에 사용하던방식으로 작업하는걸로 하겠습니다.
- config설정말고 컴포넌트나 global.css에서도 충분히 같은 효과를 낼 수 있기때문에 큰 문제는 되지않을것 같습니다. 한번 생각해보시고 의견남겨주세요~

2024-05-31 12:52 UTC, keeprok commented on src/config/tailwind/global.css
> +	}
- 어 제가 이해 한 바로는 기본 적으로 자주 사용하는 base를 global.css에 넣은 다음 추가적으로 공용 컴포넌트에 서 
버튼의  글자 색,크기 , 배경색 , round 같은경우를 변경하고자하면서 새로운값을 넣으면 공용컴포넌트에서 넣은 값들이 즉각 적용이 되는것으로 알고있는데 크게 무리 가 없지 않을까요
 - 전에 말했던사항은 p 태그에관해 상의 된게없다 엿는데 button같은경우는 현재  피그마를 보고 자주사용하는 값을 사용한것이라 사용이 편하지않을까요? 라고 생각이듭니다

2024-05-31 13:19 UTC, keeprok commented on tailwind.config.ts
> +			},
- 설정 값에 과 조합 에 관해 문제가 있어서 새로운 방법을 말씀해 주셧다고 생각을 합니다 
- 하지만 저의 생각은 조금 다릅니다  신경쓰이는 부분 2가지 에 관해서 답장을 하자면 
1. font size 로 조합을 만들어서 특정 값을 만드는것은 본문에 서  사용하는것으로서 저는 그부분만 보자면 괜찮다고 생각합니다 
2. font size 만 사용이 힘들다고 하신부분에 관해서와 조합 예시를 들어주기전  보여주셨던 코드를  보고 생각이든점은
- 현재 디자인부분에서 default 로 만들고 옆에 굵기를 따로 지정해주신 부분입니다 만약 그렇게 설정을 하고 그안에서 크기 ,굵기, 간격을 조합해서 쓰셧다면  저도 따로 각자 보내고 안에서 만드는 방식으로썻을것같습니다 
- 하지만 현재 피그마에는 defatult값이 고정되있기에 변경될수있는 생각은 걱정을 덜어도 되지않나라는 게 저의 의견입니다 
- 변경되더라도 토큰에서 쉽게 변경가능할꺼같고요 (미리 조합한것에 관한 생각입니다)
- 그리고 굵기만 변경예시를 들어주었기에 굵기만 따로 다시한번 

```ts
export const fontWeight = {
	Light: 300,
	Regular: 400,
	SemiBold: 600,
	Bold: 800,
} as const

```
선언후 tsconfig에 넣었습니다 저는 이렇게 default 값이 정해져잇을때 사용하는것이 스타일 토큰의 장점이라 생각해서 토큰으로 만들고 하는게 좋다고 생각합니다 
- 추가적으로 size나 간격은 특정 이름을 만드시지않고 값만 넣었기에 지금것이 적합하다 생각했습니다

2024-05-31 13:50 UTC, TransparentDeveloper commented on tailwind.config.ts
> +			},
저도 tailwind 에 대한 이해가 부족해서, 잘못된 주장이 있었던 것 같습니다.

fontSize 에 여러 속성을 조합해서 입력해도 되는 거군요.! 그렇다면 해당 부분에 대해서는 두 분 의견에 따를 수밖에 없네요 ㅋㅋㅋ 승복하겠습니다.

그것과는 더 토론해보고 싶은 내용이 있긴하지만("그래도 설정파일에서 조합하는 것은 추후에 추가될 디자인 확장하는데에 제한이 생기는게 아닌지? 등등등?"), 
두 분 글 써주신거 보고 신경쓰이는 부분이 많이 덜어진 거 같습니다.

진행 하시져~ 👍

2024-05-31 13:50 UTC, TransparentDeveloper approved these changes

2024-05-31 13:52 UTC, TransparentDeveloper requested changes
하나 더!

2024-05-31 13:52 UTC, TransparentDeveloper commented on src/app/layout.tsx
>  import { Inter } from "next/font/google"
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description


절대경로 & barrel-file 사용해서, import 부탁합니다.

2024-05-31 14:48 UTC, TransparentDeveloper approved these changes

2024-06-01 01:05 UTC, snkchan approved these changes
고생하셧습니다. 다음PR에는 컨밴션실수는 최대한 줄여서 올려보는걸 목표로해봐요~~

2024-06-01 01:28 UTC, HeesikK approved these changes

2024-06-01 08:18 UTC, merged