design : header
mobi-projects/nail-case-client pull request #36
Opened 2024-06-12 02:51 UTC by keeprok

## 🔥 Issues

* issue: [NAILCASE](https://nailcase.atlassian.net/browse/NAILCASE-90)

<br/>
<br/>

## 🎯 작업 내용

- [🔥 global 변경된부분 수정](https://github.com/mobi-projects/nail-case-client/commit/3d355f820ae1e5e513d95a3dd3852146d113b977)
-  회의 에 나온  추가 사항입니다 이전 layout with 설정때 했던부분이 삭제 되어 수정하였습니다 

- [🎨 Header 퍼블리싱 설정](https://github.com/mobi-projects/nail-case-client/commit/0389df56a19f6f0e71e3537463b662e22ccfd795)

- 위치조정 하였습니다 (추가적으로 가장오른쪽부분은 profie부분은 배경만 넣었습니다
- layout에서 직접 1200px을 주는것이 아닌 header 내부적으로 주었습니다 
- [피그마](https://www.figma.com/design/HyKUdbKWOkn6t9M4W0EE3V/Mobi?node-id=111-4&t=jVCzhthcBn77tPhF-0)에서 확인할수있듯이 경계선은 1200px이아닌 full 로 설정되있습니다 
- 예시 사진입니다 
<img width="1321" alt="스크린샷 2024-06-12 오전 11 07 58" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/b1213df3-6c65-4f7b-995b-f4dd8dcdc06a">
 
- [🎨 NTLogo 작업](https://github.com/mobi-projects/nail-case-client/commit/6390e7a4ba698552f23247541dae27cfb7f46405)
- 추가적으로 위사진에서 newTips는 아이콘으로 svg파일로 첨부하였습니다 

- [🔥 pulldown 삭제](https://github.com/mobi-projects/nail-case-client/commit/861604968706750e4618df3e459296354e982657)
- 현재 공용NTPullDown은 맞지않아 삭제 조치 하였습니다 
-  pr추가 merge 될시 수정 commit올리겟습니다 
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-12 04:30 UTC, TransparentDeveloper approved these changes
고생 많으셨습니다.!! :)

2024-06-12 04:37 UTC, TransparentDeveloper approved these changes

2024-06-12 04:37 UTC, TransparentDeveloper commented on src/component/custom/app/header/index.tsx
> +								<NTIcon className="text-Gray90" icon="bellLight"></NTIcon>
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
줄일 수 있습니다. 
수정 부탁드립니다.!

```tsx
<NTIcon className="text-Gray90" icon="bellLight"/>
```

2024-06-12 04:37 UTC, TransparentDeveloper commented on src/component/custom/app/header/index.tsx
> +						</div>
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
```tsx
<div>
<NTSearchfield .../>
</div>
```

div 로 감싸져야하는 이유가 있을까요?
불필요할 경우,, 지워주시면 감사하겠습니다.!

2024-06-12 04:37 UTC, TransparentDeveloper commented on src/app/layout.tsx
> +						<Header></Header>
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
마찬가지로 간결하게 적을 수 있습니다.!

```tsx
<Header/>
```

2024-06-12 04:37 UTC, TransparentDeveloper commented on src/component/common/nt-logo/index.tsx
> +// src/component/common/Logo.tsx
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
실수로 포함된 주석인 것 같습니다. 🙂

2024-06-12 04:43 UTC, TransparentDeveloper requested changes

2024-06-12 04:43 UTC, TransparentDeveloper commented on src/component/custom/app/header/index.tsx
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
"app" 페이지인가요? "home" 아닌가요?

2024-06-12 06:10 UTC, snkchan requested changes
- 고생하셧습니다..!! 수정사항 반영부탁드립니다..!

2024-06-12 06:10 UTC, snkchan commented on src/app/layout.tsx
> +						<Header></Header>
동의합니다.!

2024-06-12 06:10 UTC, snkchan commented on src/component/common/nt-logo/index.tsx
> +// src/component/common/Logo.tsx
동2...!

2024-06-12 06:10 UTC, snkchan commented on src/component/common/nt-logo/index.tsx
> +	return <Image src={logoSrc} alt="Logo" />
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
- nextjs에서 Image컴포넌트 사용하는 방법을 프로젝트전에 진행했었는데 해당내용을 학습하셧는지 모르겠네요 아신다면 그냥 적용만해도 문제없고 모르신다면 찾아보시면 좋겠습니다.
- nextjs에서 Image컴포넌트최적화를 위해서 정적인이미지 & local이미지를 사용할때 props를 사용해서 최적화가 가능합니다.
### width & height
- 넓이 높이를 명시하면 nextjs에서 이미지를 로드할때 최적화를 도와줍니다.
### placeholder = blur
- CLS향상을 위해 사용할수있는 옵션인데 loacl이미지의 경우 위의 속성만 추가해줘도 사용가능합니다.

2024-06-12 06:10 UTC, snkchan commented on src/component/custom/app/header/index.tsx
> +//지워질예정
- 주석좀...

2024-06-12 06:10 UTC, snkchan commented on src/component/custom/app/header/index.tsx
> +					</div>
- 여기도 div태그가 2개인데 한개면되는거아닐까요?

2024-06-12 12:01 UTC, keeprok commented on src/component/custom/app/header/index.tsx
이부분의 경우 여쭈어보긴했는데 app 이아닌 home 이 맞을것같네요

2024-06-13 12:15 UTC, snkchan requested changes
- 하나더 추가부탁드립니다

2024-06-13 12:15 UTC, snkchan commented on src/component/common/nt-logo/index.tsx
> +	return <Image src={logoSrc} alt="Logo" width={134} height={38} />
<img width="539" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/367c3e6a-0918-4f14-a368-6704f8e6d206">
이붑부분도 적용부탁드립니다

2024-06-14 15:13 UTC, keeprok commented on src/component/custom/app/header/index.tsx
> +					</div>
[🔥 주석삭제](https://github.com/mobi-projects/nail-case-client/pull/36/commits/f6fed16d9302c93b15942efc4e68c2dfd9c3b2a3) 삭제 조치 하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/common/nt-logo/index.tsx
> +	return <Image src={logoSrc} alt="Logo" />
with 에 관해서라면 사이즈 가 이미 디자이너분께 받은거라 픽스가되있어서 한번더 사이즈 줄필요없다고 판단했는데 최적화를 위해 한번해두겠습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/custom/app/header/index.tsx
> +//지워질예정
밑에서 답변하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/custom/app/header/index.tsx
[🔥 주석삭제](https://github.com/mobi-projects/nail-case-client/pull/36/commits/f6fed16d9302c93b15942efc4e68c2dfd9c3b2a3) 파일구조 변경하면서 </div> 삭제 하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/custom/app/header/index.tsx
> +						</div>
이전에 포함하고있던것을 삭제 하면서 올라간거같습니다 삭제 하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/custom/app/header/index.tsx
> +								<NTIcon className="text-Gray90" icon="bellLight"></NTIcon>
[🔥 주석삭제](https://github.com/mobi-projects/nail-case-client/pull/36/commits/f6fed16d9302c93b15942efc4e68c2dfd9c3b2a3)  
- 앞으로  </NTIcon>  이렇게 children 없는부분은 삭제 하도록 하겠습니다

2024-06-14 15:13 UTC, keeprok commented on src/app/layout.tsx
> +						<Header></Header>
위에서 답변하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/common/nt-logo/index.tsx
> +// src/component/common/Logo.tsx
위에서 답변하였습니다

2024-06-14 15:13 UTC, keeprok commented on src/component/common/nt-logo/index.tsx
> +	return <Image src={logoSrc} alt="Logo" width={134} height={38} />
svg는 url도 포함되어야 한다고 합니다 따로 넣지는 않겠습니다

2024-06-14 15:22 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-06-14 15:42 UTC, HeesikK approved these changes
고생하셨습니다.

2024-06-14 20:51 UTC, snkchan approved these changes
- 수고하셧습니다,!

2024-06-14 20:51 UTC, merged