design : tabBar 작성
mobi-projects/nail-case-client pull request #37
Opened 2024-06-12 03:01 UTC by keeprok

## 🔥 Issues

* issue: [NAILCASE-91](https://nailcase.atlassian.net/browse/NAILCASE-91)

<br/>
<br/>

## 🎯 작업 내용

[🎨 TabBar 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/23b4d201d12b3992e78f34fcb54a3105cbbc2759)
 - Toolbar 형식에서 postion top 부분 사용했습니다 
 - custom 특정상 한곳에서만 사용 할거라 생각해 arr 넣었습니다 
- 현재 header pr 완료시 header 안에 추가하도록 하겠습니다
- 경계선의 경우 header 부분에 추가하기위해 삭제 조치 하였습니다 
<img width="1240" alt="스크린샷 2024-06-12 오전 11 28 42" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/fb251d9c-3b66-40c4-82b2-82acc10cdf00">

<br/>

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-12 03:03 UTC, keeprok commented
추가적으로 	<div className="mt-2">이부분은 header merge완료시 수정조치하면서 삭제 하겠습니다  header에서 이미 적용 하였습니다

2024-06-12 04:53 UTC, TransparentDeveloper requested changes
여러 페이지에 걸쳐 사용되는 것이니, `app` 폴더를 만들어 toobar 컴포넌트를 관리하셨다는 말씀이,, 잘 공감이 되지 않네요.

여러 페이지에서 재사용되는 컴포넌트라면 공용컴포넌트죠.
`custom` 폴더는 디자이너와 상관없이, **코드 가독성을 높힐 목적** 으로 분리한 코드 조각을 관리합니다.

`Tabbar()` 에 적혀있는 코드가 `ToolBar()` 의 내용이어야 하지 않나 생각이 되네요.
작업 단위를 다시 정해서 ToolBar 를 먼저 수정하는 방향으로 진행하는 게 어떨까요?

2024-06-12 06:12 UTC, snkchan commented
> 여러 페이지에 걸쳐 사용되는 것이니, `app` 폴더를 만들어 toobar 컴포넌트를 관리하셨다는 말씀이,, 잘 공감이 되지 않네요.
> 
> 여러 페이지에서 재사용되는 컴포넌트라면 공용컴포넌트죠. `custom` 폴더는 디자이너와 상관없이, **코드 가독성을 높힐 목적** 으로 분리한 ui 조각을 관리합니다.
> 
> `Tabbar()` 에 적혀있는 코드가 `ToolBar()` 의 내용이어야 하지 않나 생각이 되네요. 작업 방향을 다시 정해서, ToolBar 를 먼저 수정하는 게 어떨까요?

- 헉 제가 task분배할때 잘못 전달한거같네요. Jeff님 의견이 맞는것 같습니다.

2024-06-12 11:55 UTC, keeprok commented
흠 사실 아침에 pr을 올릴때 header 부분에서 같이 쉽게 관리 할수있는것같은데  판단을 조금더 명확히 했어도 됬을것같네요 이번 내용을 차라리 header 부분에서 같이 올리도록 하겠습니다

2024-06-14 13:50 UTC, keeprok commented
# 수정사항 
- postion : top 으로 되어잇는 tobBar는 home의 header에서 고정적으로만 사용되어 arr을 미리 사용했습니다 
- 추후에 header와 tabBar가 다른 이벤트가 일어날수도 있다고 판단해 layout에서 header안에 넣지 않고 분리했습니다

2024-06-15 04:34 UTC, closed without merging