design : reservationCard 작성
mobi-projects/nail-case-client pull request #39
Opened 2024-06-13 06:37 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-92](https://nailcase.atlassian.net/browse/NAILCASE-92)

    

<br/>
<br/>

## 🎯 작업 내용
- [⚡️ NTButton 코드 수정](https://github.com/mobi-projects/nail-case-client/commit/9837ab6ecf716b10319557cfc1153144564ea7d0)
  - 기존에 NTButton의 경우 width와 height 값이 고정되어 있어서 button의 크기가 작거나 button안에 텍스트가 커지면 아이콘이 작아지는 문제가 발생했습니다.
  - 이를 해결하기 위해 기존 button의 width와 height 값을 제거하고 `w-fit h-fit` 속성을 추가했습니다.
  
- [⚡️ NTOption 코드 수정](https://github.com/mobi-projects/nail-case-client/commit/6948410e69d7d7f70599233ea41594d096d91efd)
  - NTOption 코드에 `itemsPerRow` 를 props로 추가했습니다. 
  - `itemsPerRow`는 한 행에 들어갈 수 있는 NTOption의 갯수를 지정할 수 있는 props입니다.
  - 예약대기 컴포넌트의 경우 `itemsPerRow` 속성을 2로 제한하여 Option을 아래와 같이 렌더했습니다.
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/b928e327-f140-4116-b70c-6da04e888002)

- [🎨 ReservationPendingCard 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/9be5d8335bb661d2de7af6dac53be644cdf68d2a)
 
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/9e74fd43-8744-4e51-91d4-6e1ddc607233)

  - ReservationPendingCard 컴포넌트는 useReservationArr 커스텀 훅을 사용하여 예약 관련된 정보를 가져와 `	const filteredData =
		reservationArr?.filter((item) => item.status === "WAITING") || []` status 값이 "WAITING"인 값을 출력하도록 작업했습니다.
  - Option은 아직 폼에서 전달받을 수 있는 정보가 없어서 임의로 figma에 있는 `["이달의 아트", "연장 필요", "타샵 제거 있음",]` 값을 출력하도록 작업했습니다.
  -   ```{filteredData.length > 0 ? `1/${filteredData.length}` : "0/0"}``` 부분은 모카님께 어떤 방법으로 렌더링을 시킬지 figma에 질문 추가해놓은 상태여서 우선 이렇게 추가해놨습니다.
  - 예약 시간의 경우 아직 시간을 변환해주는 함수가 정의가 되어있지 않아 아래와 같이 시간을 formatting하는 함수를 작성해서 추가했습니다. 이 부분은 추후에 시간을 변환해주는 함수가 추가되면 제거 하겠습니다.
  
  ```javascript	const getFormattedDate = (startTime: TNTTime) => {
		const days = ["일", "월", "화", "수", "목", "금", "토"]
		const date = new Date(
			startTime.year,
			startTime.month - 1,
			startTime.day,
			startTime.hour,
			startTime.minute,
		)
		const dayName = days[date.getDay()]
		const hour = date.getHours()
		const minute = date.getMinutes()
		const period = hour >= 12 ? "오후" : "오전"
		const formattedHour = hour > 12 ? hour - 12 : hour
		const formattedMinute = minute === 0 ? "" : `${minute}분`

		return `${startTime.month}월 ${startTime.day}일 (${dayName}) ${period} ${formattedHour}시 ${formattedMinute}`
	}``` 

- [🎨 ReservationConfirmedCard 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/5c5d183d284b1ce3e8028a49ee3deee72acb256c)
  
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/685a1d2b-56b3-4395-9bee-0a6b984dae90)
  - 예약확정 컴포넌트는 마찬가지로 useReservationArr 훅을 사용하되 ```	const filteredData =
		reservationArr?.filter((item) => item.status === "APPROVAL") || []``` status가 "APPROVAL" 인 값만 필터링해서 출력하도록 작업했습니다.

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-13 10:41 UTC, TransparentDeveloper requested changes
고생하셨습니다 :)

2024-06-13 10:41 UTC, TransparentDeveloper commented on src/component/custom/reservation/reservation-pending.tsx
> +	}
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
- TNTTime 을 왜 사용하는지 공유가 잘 안된것 같네요..
- 이 함수가 정말 필요한지, 다시 고민해보시길..

2024-06-13 10:41 UTC, TransparentDeveloper commented on src/component/custom/reservation/reservation-confirmed.tsx
> +					/>
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- 이미지 너비와 높이를 설정한 것은 좋습니다.
- Image 컴포넌트에 `width`, `height` 속성을 이용하는 게 어떨까요?

2024-06-13 11:26 UTC, keeprok reviewed
수고하셨습니다

2024-06-13 11:26 UTC, keeprok commented on .github/PULL_REQUEST_TEMPLATE.md
>            - 이 commit 에서는 이러이러한 작업을 했습니다.
이부분은 되돌리기 해서 안올리는게 더 좋아 보이네요

2024-06-13 11:26 UTC, keeprok commented on src/component/common/atom/nt-button/index.tsx
> +				medium: `rounded-[12px] px-[18px] py-[12px] text-Headline01`,
`` 쓰신 이유가 있을까요?

2024-06-13 13:07 UTC, snkchan commented on src/component/custom/reservation/reservation-confirmed.tsx
> +					/>
- (해당링크)[https://github.com/mobi-projects/nail-case-client/pull/36]
- <img width="636" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/13c032e5-8307-4c23-8f10-847439455b5e">

- nextJs에서 Image컴포넌트를 사용할때 최적화에대한 내용을 언급했습니다. 모르시는부분이라면 검색해보셔도 좋을것 같아요!

- 추가적으로 pr을확인할때 팀원들은 코드에대해 어떻게생각하나 꼭 읽어보셧으면 좋겠습니다. 개인마다 코드를 작성하는 방식, 생각이 모두 다르기때문에 어떤의견을 가지고있나 참고해보시면 배워갈것도 많고 정보공유도 되는과정이기때문입니다.!

2024-06-13 13:07 UTC, snkchan commented on src/component/common/atom/nt-button/index.tsx
> +				medium: `rounded-[12px] px-[18px] py-[12px] text-Headline01`,
- 날카로운데,,?!

2024-06-14 02:18 UTC, snkchan requested changes
- 고생하셧습니다.! 몇가지만 수정부탁드릴게요~!

2024-06-14 02:18 UTC, snkchan commented on src/component/common/nt-option/index.tsx
> +								console.log(option)
- 오오오잉? 콘솔은 삭제부탁드립니다!

2024-06-14 02:18 UTC, snkchan commented on public/asset/enabled.png
- 이부분은 준비가 안되서 죄성합니다.. icon으로 추가해서 사용하는것이 좋을것 같아요
- [링크](https://icon-sets.iconify.design/?query=up+right) 타고들어가시면 사이트나오는데
- <img width="238" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/68a3dbfe-b4fc-4a3d-b4c9-2a872e096cc9">
- 해당아이콘 추가해서 작업해주시는편이 좋을것 같아요
- 이미지파일을 보내는것보다 icon을 추가하는편이 서버에서 보낼 resource가줄어들것 같습니다.

2024-06-14 02:18 UTC, snkchan commented on package-lock.json
- lock.json은 수정된내용이있나요?

2024-06-15 04:51 UTC, snkchan approved these changes
- 고생하셧습니다!

2024-06-15 07:11 UTC, snkchan reviewed
- 고생하셧습니다!

2024-06-15 07:12 UTC, keeprok approved these changes
수고 하셨습니당

2024-06-15 07:12 UTC, TransparentDeveloper approved these changes
LGTM

2024-06-15 07:17 UTC, merged