design : banner-carousel 컴포넌트 작성
mobi-projects/nail-case-client pull request #40
Opened 2024-06-14 07:38 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-100001](https://nailcase.atlassian.net/browse/NAILCASE-104)

<br/>
<br/>

## 🎯 작업 내용

# NextJs 외부Image경로 추가설정
- [🔧 외부 image경로설정 추가](https://github.com/mobi-projects/nail-case-client/commit/18ab6db62cca08c65259446bdfa4a1a5813cb840)
- NextJs에서는 Local이미지가 아닌 외부이미지의 경우 경로를 별도로 추가해줘야 load할 수 있습니다.
```ts
const nextConfig = {
	images: { 
		remotePatterns: [
			{
				protocol: "https",
				hostname: "loremflickr.com", 
				port: "",
				pathname: "/**",
			},
		],
	},
}
```
- 위와같은 형태로 경로가 여러개라면 배열의 원소에 하나씩 경로를 추가하면 image load성공

# banner-carousel 컴포넌트
## CheckPoint 1
## CheckPoint 1
- [🎨 banner-carousel 컴포넌트 생성](https://github.com/mobi-projects/nail-case-client/commit/87f2ef9cc9c874573212e25e5163eba303a9b268)
- [✨ useBanner hook 생성](https://github.com/mobi-projects/nail-case-client/commit/01d869273d58448f1c7c594b83092ad259e26bb8)

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] Issue 번호 설정 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-14 10:40 UTC, TransparentDeveloper requested changes
고생하셨습니다.!

2024-06-14 10:40 UTC, TransparentDeveloper commented on src/component/common/nt-banner-carousel/index.tsx
> +	const { shopInfo } = useShopInfo()
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 공용 컴포넌트라면 출력할 데이터를 외부에서 받도록 구현하는 편이 좋을 것 같습니다.

2024-06-14 10:40 UTC, TransparentDeveloper commented on src/component/common/nt-banner-carousel/index.tsx
> +}
# Request Level
  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 컨벤션 문서에 따라자면, `useCarousel` 의 함수 선언식이 달라져야하지 않을까 합니다.
- 컴포넌트 선언 외에는 화살표 함수로 작성해야합니다.

2024-06-14 10:45 UTC, snkchan commented
헉.....제가 이런실수를하다니 집가서얼른수정하것습니다


2024년 6월 14일 (금) 오후 7:40, yunshin ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> 고생하셨습니다.!
> ------------------------------
>
> In src/component/common/nt-banner-carousel/index.tsx
> <https://github.com/mobi-projects/nail-case-client/pull/40#discussion_r1639625701>
> :
>
> > +
> +type CarouselContextProps = {
> +	carouselRef: ReturnType<typeof useEmblaCarousel>[0]
> +	api: ReturnType<typeof useEmblaCarousel>[1]
> +	scrollPrev: () => void
> +	scrollNext: () => void
> +	canScrollPrev: boolean
> +	canScrollNext: boolean
> +	carouselIdx: number
> +} & CarouselProps
> +
> +export default function BannerCarousel({
> +	handleCarousel,
> +	children,
> +}: BannerCarouselPT) {
> +	const { shopInfo } = useShopInfo()
>
> Request Level
>
>    - "🚨 꼭 수정해주세요.!"
>
> Description
>
>    - 공용 컴포넌트라면 출력할 데이터를 외부에서 받도록 구현하는 편이 좋을 것 같습니다.
>
> ------------------------------
>
> In src/component/common/nt-banner-carousel/index.tsx
> <https://github.com/mobi-projects/nail-case-client/pull/40#discussion_r1639629816>
> :
>
> > +const CarouselContext = createContext<CarouselContextProps | null>(null)
> +
> +function useCarousel() {
> +	const context = useContext(CarouselContext)
> +
> +	if (!context) {
> +		throw new Error("useCarousel must be used within a <Carousel />")
> +	}
> +
> +	return context
> +}
>
> Request Level
>
>    - "🚨 꼭 수정해주세요.!"
>
> Description
>
>    - 컨벤션 문서에 따라자면, useCarousel 의 함수 선언식이 달라져야하지 않을까 합니다.
>    - 컴포넌트 선언 외에는 화살표 함수로 작성해야합니다.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mobi-projects/nail-case-client/pull/40#pullrequestreview-2118060063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCRBJQGXTT4DYJ24U6BAEMDZHLCBVAVCNFSM6AAAAABJJ2EZ76VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMJYGA3DAMBWGM>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-06-14 20:40 UTC, snkchan commented on src/component/common/nt-banner-carousel/index.tsx
> +	const { shopInfo } = useShopInfo()
- 저번회의에 내부에서 호출하기로 한거아니었나요?!

2024-06-15 05:15 UTC, TransparentDeveloper approved these changes

2024-06-15 05:15 UTC, HeesikK approved these changes
고생하셨습니다.

2024-06-15 05:25 UTC, merged