design : HomePageLayout 완료
mobi-projects/nail-case-client pull request #54
Opened 2024-06-17 09:22 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-113](https://nailcase.atlassian.net/browse/NAILCASE-113)
sub-issues:
  - [NAILCASE-117](https://nailcase.atlassian.net/browse/NAILCASE-117)
<br/>
<br/>

## 🎯 작업 내용

<img width="575" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/6fbc5c7a-448e-4794-8147-334f41a0c3ec">

- [🚚 home page 폴더구조에 맞게 layout파일 이동](https://github.com/mobi-projects/nail-case-client/commit/73c105657fc577beaea4d561cbf31073dc412d4a)
  - `scr> component > custom > home > layout > index.tsx` 에서 layout에들어갈 Banner관리하도록 했습니다.  
- [🎨 figma에 추가된 icon추가](https://github.com/mobi-projects/nail-case-client/commit/e25b65878561829675e157c1e7a8eaa7a089257b)
<img width="40" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/2e1e2858-37a7-42e4-aed6-b27069d7faa4">
<img width="50" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/45917487-e6ed-478a-944e-07319d4bb83b"><br/>
- 3가지 아이콘이 새로추가되서 NTIcon에 추가했습니다.

# 아직완료안된 부분 Check!

- [🎨 home page layout 작업](https://github.com/mobi-projects/nail-case-client/commit/80596194685d9ef0bd338e518197c02ff630d13e)
  - <img width="1270" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/66059c17-a863-4171-81a6-9c12dd1f3197">
- <img width="716" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/a21116c3-73dc-4779-87e4-e8e7fd16c3b6">
- 아래쪽이 figma요구사항인데 **빨간줄** 부분을 보시면 해당 data는 아직 준비되지않았습니다.
- moka님이 나중에 작업하신부분이라 해당부분은 데이터준비되면 추가하도록 하겠습니다.!

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-17 11:42 UTC, TransparentDeveloper requested changes
음.. 제가 봤을 때, Customer 페이지 최상위 layout 에 banner 를 두면 안될 것 같습니다.

아래 이미지는 shop 의 상세 페이지인 것 같아요.
가장 상단 좌측에 '뒤로가기' 아이콘도 있잖아요.

<div align="center">

![image](https://github.com/mobi-projects/nail-case-client/assets/50646145/510340f7-8ecb-4b44-9983-deff0cacc737)

</div>

해당 페이지 이전엔 shop 목록을 확인할 수 있는 페이지가 있을 것 같아요. 그곳이 진짜 Customer 의 'Home' 일 듯합니다.. 

아직 Customer 쪽 layout 을 만지면 안될 것 같아요. 
피그마 디자인이 완성된 게, Manager 쪽 보다 부족하기 떄문입니다.

2024-06-18 02:16 UTC, snkchan commented
@TransparentDeveloper 
- [🚚 설계에 맞게 폴더구조 변경](https://github.com/mobi-projects/nail-case-client/pull/54/commits/777666e07df765fc12241c500b2a00c9cad0390d)
- 맞습니다..! home폴더가 메인페이지이고 거기서 어떤 클릭이동을 해야 shop-detail페이지가 나오는게 맞는 구조같네요..?
- 아직 피그마 설계가없어서 임시로 제가 다음과같이 설정해두었습니다.
- /home 경로에서 보여지는 화면입니다. 해당 부분은 임시라서 나중에 home작업자가 수정하는걸로 하는게어떨까요?
- <img width="1276" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/7e8b9427-ca3b-45dc-8f4c-da8eb0b88284">
- <img width="165" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/16395106-471e-4f3d-9365-b1ea4d60277d">
- `home > [shop-detail]` 로 경로를 설정해두었는데... home > shop-detail > [shop-detail]이게 더 좋을까요?? 의견부탁드립니다.

2024-06-18 03:45 UTC, keeprok commented
저는 개인적으로 현재 경로로 설정되있는게 낫다고 판단합니다 home > shop-detail > [shop-detail] 이렇게 되있다면 처음 home에 들갔을때 shop-detail 부분이 저희는 지금 인원이 적기때문에 [shop-detail] 이러한 형식이라고 알고있지만 인원이 많다고 판단하고 여러가지를 한다고판단햇을때 clinet - manager 부분으로 나뉘어있어 clinet쪽으로 들어가면쉽게 구별될것같습니다

2024-06-18 03:58 UTC, keeprok requested changes
수고하셨습니당@@

2024-06-18 03:58 UTC, keeprok commented on src/app/home/[shop-detail]/page.tsx
> +					/>
이부분이 전달이 조금 안된것같습니다 (앞으로 PR전달을 조금더 생각해봐야겠네요) position 의 경우 
- bottom 
   -  bottomTextSize : [small , large]
- top
   -  topStyle  : [default , light]
 이 각자 필수로 넣어야 피그마의 (순서대로) 글씨 체 , (border,글씨 )색상이 다루어집니다 top의 경우 색상이 기 때문에 구분이 되지만 bottom의 경우 기본 글씨 체 가 들어갔을것같네요

2024-06-18 04:09 UTC, HeesikK requested changes
고생하셨습니다..!

2024-06-18 04:13 UTC, HeesikK commented on src/app/home/[shop-detail]/page.tsx
> +	} = useOption(["손톱 보수 필요", "A/S 필요", "상처 있음", "교정 필요"])
제가 작업하는 my-shop/home 페이지에서도 비슷한 문제가 있는거 같아서 말씀드립니당..! 

전달하는 함수가 달라서 useOption 훅을 여러번 호출하는 상황이 발생하는거 같은데 가독성이 떨어지고 비효율적이라고 생각해서 이 부분은 다른 함수를 추가로 만들어서 관리해도 좋지 않을까요..?

2024-06-18 04:14 UTC, snkchan commented on src/app/home/[shop-detail]/page.tsx
> +	} = useOption(["손톱 보수 필요", "A/S 필요", "상처 있음", "교정 필요"])
- 이부분을 useOption()함수를 수정해서 적용해야할것 같습니다.

2024-06-18 09:26 UTC, TransparentDeveloper commented
> @TransparentDeveloper
> 
> * [🚚 설계에 맞게 폴더구조 변경](https://github.com/mobi-projects/nail-case-client/pull/54/commits/777666e07df765fc12241c500b2a00c9cad0390d)
> * 맞습니다..! home폴더가 메인페이지이고 거기서 어떤 클릭이동을 해야 shop-detail페이지가 나오는게 맞는 구조같네요..?
> * 아직 피그마 설계가없어서 임시로 제가 다음과같이 설정해두었습니다.
> * /home 경로에서 보여지는 화면입니다. 해당 부분은 임시라서 나중에 home작업자가 수정하는걸로 하는게어떨까요?
> * <img alt="image" width="1276" src="https://private-user-images.githubusercontent.com/144839872/340511522-7e8b9427-ca3b-45dc-8f4c-da8eb0b88284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDI1MDgsIm5iZiI6MTcxODcwMjIwOCwicGF0aCI6Ii8xNDQ4Mzk4NzIvMzQwNTExNTIyLTdlOGI5NDI3LWNhM2ItNDVkYy04ZjRjLWRhOGViMGI4ODI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwOTE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjdlODBhYTk4NmZmNWYxYzY1MmE5Njk0ZDZiNzBlNGMyNWNjMTBiZGU4NTk2Mzg0ZmI1NGVkZWUzNmQyNjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ed3TYLzS7cAYsNd58ehwT-y2GfJ-ZHFMSYl-7aJDMBg">
> * <img alt="image" width="165" src="https://private-user-images.githubusercontent.com/144839872/340511737-16395106-471e-4f3d-9365-b1ea4d60277d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDI1MDgsIm5iZiI6MTcxODcwMjIwOCwicGF0aCI6Ii8xNDQ4Mzk4NzIvMzQwNTExNzM3LTE2Mzk1MTA2LTQ3MWUtNGYzZC05MzY1LWIxZWE0ZDYwMjc3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwOTE2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjU3MTdkZDQwZTU5YmUyZmIxZGMxMzYzNzEzYTFhMTEyODU3ODVhMDMwNjk0N2M0NGY5OThjYWMyY2U2MDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qBbfOoeV1xj8bvRBnFq-lDEhAxZKknZuI8SSODYgsTQ">
> * `home > [shop-detail]` 로 경로를 설정해두었는데... home > shop-detail > [shop-detail]이게 더 좋을까요?? 의견부탁드립니다.

`shop-detail` 이라하면 어떤 정보를 props 로 넘어갈 지가 모호합니다.

제 직관적으로는 숍 정보와 관련된 객체 데이터가 넘어갈 것 같네요.
그러면 home 에서 출력되는 모든 숍 목록에 대해 상세 데이터를 일시에 패칭받아야 합니다.
(이게 pre-fetching??)

지금까지 했던 경험 상, 보통은 매장 고유번호(id) 를 넘기고 상세 페이지에서 id 를 사용해 매장 데이터를 받죠.

2024-06-19 02:56 UTC, closed without merging