design: manager/base/my-shop/home/03 퍼블리싱 완료
mobi-projects/nail-case-client pull request #57
Opened 2024-06-17 17:01 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-131](https://nailcase.atlassian.net/browse/NAILCASE-131)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 manager-base-my-shop-home-03 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/3fa3c8123213774f7be61e7fffaedd249cca64bb)

  - manager/base/my-shop/home/03 퍼블리싱 완료했습니다.
  - 2/3번째 섹션에는 mock 데이터 사용하여 퍼블리싱 하였습니다.
  - 1/4번째 섹션에 해당하는 mock 데이터가 없어 추가되면 수정하겠습니다
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/2e9039d5-0aec-46c3-937c-36399412eeaf)
  - 반복되는 card의 헤더 부분은 **CardHeader**로 만들어 분리해서 작업했습니다.

- 작업 결과물
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/855c1200-6e53-45ef-a359-c5f86bf3f8d0)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-18 01:50 UTC, snkchan reviewed
- `mananger/base/myshop-home-03` 아래에 들어가는 컴포넌트들은 
home-03-01~~0x 형태로 넣기로했엇는데 Jeff님이 그렇게 작성해주신 이유는 03폴더에서 export될 컴포넌트는 하나만 export하며 그아래 부속품으로 존재하는 컴포넌트들은 03-01 03-02... 와같이 영역을 구분하기위해서 임의로 설정해주신 이름이라고 이해했습니다.
- 따라서 해당페이지를 작업하는 작업자는 03-01에맞는 이름으로 수정해서 작업하자고 이해했는데 그렇게하는 것이 맞을것 같습니다. 
- ex) function03_01  ===> function InfoCardWorkingTime 과같은 형태로 해당 컴포넌트의 목적에맞는 이름으로 수정하는것이 맞지않을까요?

2024-06-18 01:50 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +						<span className="mr-2 h-[6px] w-[6px] text-Gray60">•</span> 주차가능
- `<span className="mr-2 h-[6px] w-[6px] text-Gray60">•</span> 주차가능` 여기에  • 이부분은 figma상과 일치하지않아서 제가 NTIcon에 추가해둔게 있을겁니다.
- <img width="208" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/c33d8dd2-3639-49a1-a6e2-116e35407948">
- 해당 아이콘으로 대체하시면 됩니다.

2024-06-18 02:37 UTC, snkchan commented
- <img width="611" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/0f1bfa89-6507-426c-8bc2-e2fc5b031013">
design : 작업내용~~ //컨밴션
design: 작업내용~~ // Levi님 pr제목입니다. 띄어쓰기!

2024-06-18 04:11 UTC, keeprok reviewed
데이터를 넣는부분이 어려울것같네요 ㅠㅠ

2024-06-18 04:11 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +				<div className="list-disc">
list-disc는 같이 들어가면 안되나요? 또한 필요할까요??

2024-06-18 09:43 UTC, TransparentDeveloper requested changes
고생하셨습니다.

실제 페이지에 적용해서 커밋올려주시면, vercel 로 확인할 수 있어요.
부탁드립니다 :)

2024-06-18 09:43 UTC, TransparentDeveloper commented on package-lock.json
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 따로 라이브러리 설치한 게 없으면, commit 되어선 안될 파일입니다.
- 로컬 환경 설정이 달라서 계속 변경점 잡힐 것 같은데, 앞으로는 pr 에 올라오지 않도록 주의해주세요.

2024-06-22 08:45 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2024-06-22 08:45 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
>  	return (
# Request Level
  - [x] "🚧 재고해주시길.."

# Description
- 이거 export 되는 이름 변경하기로 했던 것 같습니다. 수정 부탁드립니다.

2024-06-24 12:59 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/03/index.tsx
> +						<span className="mr-2 h-[6px] w-[6px] text-Gray60">•</span> 주차가능
수정 완료했습니다..!

2024-06-24 13:01 UTC, snkchan approved these changes
- LGTM

2024-06-24 13:07 UTC, merged