design: manager/base/my-shop/home/05 완료
mobi-projects/nail-case-client pull request #58
Opened 2024-06-18 01:33 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-133](https://nailcase.atlassian.net/browse/NAILCASE-133)

<br/>
<br/>

## 🎯 작업 내용 

- [🎨 manager-base-my-shop-home-05 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/a31d79c1d3a6bf53bf7a9fb3ea524029e9b8a028)

  - manager/base/my-shop/home/05 퍼블리싱 완료했습니다.
  - usePostArr을 사용하여 mock 데이터 적용 완료했습니다.
 
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/f7211677-9bf5-4e14-a913-bbe4324bc83a)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-18 01:56 UTC, snkchan requested changes
- 고생하셧습니다!

2024-06-18 01:56 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +	console.log(postArr)
- ?!?!?!?!?? 오잉?!

2024-06-18 01:56 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +type postPT = {
type명의 첫글자는 대문자입니다..!

2024-06-18 01:56 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +				style={{ height: "204px" }}
style속성은 어째서 사용하신거죠?!

2024-06-18 01:56 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +function Manager_Base_MyShop_Home_05_01({ post }: postPT) {
해당 컴포넌트의를 생성하실때 post?. 으로작성되있는데 ?를 붙이지 않아도 될것 같습니다.

2024-06-18 02:37 UTC, snkchan commented
- <img width="611" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/0f1bfa89-6507-426c-8bc2-e2fc5b031013">
design : 작업내용~~ //컨밴션
design: 작업내용~~ // Levi님 pr제목입니다. 띄어쓰기!

2024-06-18 04:32 UTC, keeprok reviewed
수고하셧습둥

2024-06-18 04:32 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +					{post?.title}
?가 있을필요가 있을까요 제목 없이 등재 가 안될것같은데

2024-06-18 04:32 UTC, keeprok commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +						{post?.content}
? 내용 또한 포함일것같습니다

2024-06-18 09:52 UTC, TransparentDeveloper requested changes
home 에 적용해주세요 :)

2024-06-18 09:52 UTC, TransparentDeveloper commented on package-lock.json
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 불필요한 변경점이 포함되어 있습니다.
- 커밋 되돌리고, `package-lock.json` 빼고 add & commit & push force 해주세요.

<br/>

[👇 커밋 되돌리기]
```git
git reset --soft {"a31d79c1d3a6bf53bf7a9fb3ea524029e9b8a028 이전 commit"}
```

2024-06-19 02:00 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +	console.log(postArr)
콘솔 삭제했습니다..!ㅎㅎ

2024-06-19 02:00 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +type postPT = {
넵 확인하고 수정 완료 했습니다!

2024-06-19 02:01 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +				style={{ height: "204px" }}
style 속성을 사용하지 않으면 Image 컴포넌트에 height 속성이 적용되지 않아서 추가했습니다😥

2024-06-19 02:02 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +function Manager_Base_MyShop_Home_05_01({ post }: postPT) {
해당 부분 확인하고 수정 완료했습니다.

2024-06-19 02:02 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +					{post?.title}
해당 부분 확인하고 수정 완료했습니다.

2024-06-19 02:02 UTC, HeesikK commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +						{post?.content}
해당 부분 확인하고 수정 완료했습니다.

2024-06-19 02:03 UTC, HeesikK commented on package-lock.json
커밋 되돌리고 다시 push 완료했습니다..! 앞으로는 올릴 때 주의하겠습니다..!ㅎㅎ

2024-06-19 02:59 UTC, snkchan approved these changes
고생하셨습니다..!
하나더 있습니다. review반영사항에 대해서 커밋을남기신후 댓글에 어떤커밋인지 링크도 연결 부탁드립니다.! 어떤커밋에서 요청사항이 반영됐는지 확인하기가어렵습니다 링크가없다면...

2024-06-21 12:30 UTC, keeprok approved these changes
수고 하셨습니다

2024-06-22 08:46 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2024-06-22 08:46 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/home/05/index.tsx
> +				style={{ height: "204px" }}
어떤 문제가 있는지 잘 모르겠네요. 
조금 더 자세히 알려주실래요?

2024-06-22 09:22 UTC, merged