add : storybook 의존성 추가 및 chromatic 자동배포
mobi-projects/nail-case-client pull request #6
Opened 2024-06-02 02:55 UTC by HeesikK

## 🔥 Issues
- issue: [NAILCASE-28](https://nailcase.atlassian.net/browse/NAILCASE-28)

<br/>
<br/>

## 🎯 작업 내용

- [➕ : storybook install](https://github.com/mobi-projects/nail-case-client/commit/66a56c2b6cabd01eb449fc6fabb2574d8432acbe)
  - 프로젝트에 스토리북을 적용 및 배포하기 위해 관련 패키지를 설치했습니다.
- [🔧 : chromatic 배포 workflow 추가](https://github.com/mobi-projects/nail-case-client/commit/7b2a7fb75f53ac8f48d9bcd1f320d9e7305b727f)
  - yml 파일을 통해 "Chromatic Deployment"라는 GitHub Actions workflow를 정의했습니다.
  - 이 workflow는 코드가 push될 때마다 Chromatic을 사용하여 스토리북 테스트 및 배포를 자동화하는 데 사용됩니다.
 
아래 사진처럼 저장소에 push 이벤트가 발생할 때마다 실행되고 배포된 스토리북을 확인할 수 있습니다.
![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/fa6dffb4-635f-4074-94c3-f2c74ba5fa47)

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-02 03:31 UTC, TransparentDeveloper requested changes
고생하셨습니다.!!

2024-06-02 03:31 UTC, TransparentDeveloper commented on src/stories/Button.stories.ts
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- `src` 폴더 아래, 새로 생성된 파일은 story-book install 하면서 기본으로 생성된 것 같은데, 제거해주시겠어요??

2024-06-02 03:31 UTC, TransparentDeveloper commented on src/stories/assets/accessibility.png
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- assets 폴더 아래 생성된 이미지파일도 필요한 것인가요??
- 불필요한 파일이라면,, 앞으로는 커밋이력에 남지 않도록 부탁드립니다 :)

2024-06-02 03:31 UTC, TransparentDeveloper commented on src/stories/button.css
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


# Description
- .css 파일도 삭제바랍니다.
- 그리고 우리는 스타일 라이브러리로 tailwind-css 사용하잖아요?
- 스토리북에도 적용하려면 플러그인 따로 설정해줘야하는 걸로 알고 있는데,, 그것도 이번 pr 에 반영해 주실 수 있을까요?

2024-06-02 08:11 UTC, snkchan commented
- `아래 사진처럼 저장소에 push 이벤트가 발생할 때마다 실행되고 배포된 스토리북을 확인할 수 있습니다.` 라고 남겨주셨는데
chromatic홈페이지에서 저희가작업한 stroybook component를 확인할 수 있는건가요? 질문입니다 ㅎㅎ

2024-06-02 18:02 UTC, keeprok approved these changes
수고 하셨습니다  디자이너와 실제로 하는 기분이 들게하는 pr이네요

2024-06-03 02:46 UTC, HeesikK commented on src/stories/button.css
-  [🔧 storybook tailwindCSS 적용](https://github.com/mobi-projects/nail-case-client/commit/2a80325079c71d875bd0442a667b11381c8d3cc4) storybook에 tailwindCSS 적용 완료했습니다.

![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/41189c46-5f7a-4639-880a-aa6574ae4e99)
- 적용 완료 후 사용되지 않는 파일은 삭제 완료했습니다.

2024-06-03 02:47 UTC, HeesikK commented on src/stories/assets/accessibility.png
넵..! 앞으로 주의하겠습니다.

2024-06-03 08:16 UTC, snkchan approved these changes
- 고생하셧습니다~~

2024-06-03 12:51 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-06-03 12:51 UTC, merged