design: manager/home/04
mobi-projects/nail-case-client pull request #61
Opened 2024-06-18 07:01 UTC by keeprok

## 🔥 Issues

*issue : [NAILCASE-125](https://nailcase.atlassian.net/browse/NAILCASE-125)

<br/>
<br/>

## 🎯 작업 내용

- [⚡️ card 리펙토링](https://github.com/mobi-projects/nail-case-client/commit/7cca7e8d55ab021deeca3d95d814c6e57a103d73)
- const -> funtion으로 변경했습니다 
- post-card image추가했습니다 
<img width="833" alt="스크린샷 2024-06-18 오후 3 52 46" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/c0ab4faf-6201-4e1a-91d8-20286a8422ee">

- [🚚 card 폴더위치 및 이름 수정](https://github.com/mobi-projects/nail-case-client/commit/6b05ca3678c66ca8136340c74ab69ff7f7956a06)
- `component/custom/post` 
- `component/custom/manager/base/home / 04/01,02` 로 변경해서 index로 수정했습니다   //card부분 관리 위치 
- Notice -> Main , Post -> Sub 이름변경

- [🚚 CCI에 맞게 파일구조 변경](https://github.com/mobi-projects/nail-case-client/commit/b3af8d764c083b790c279d6691deaf07fd9c013b)
- `app/(manager)/manager/base/(home)` 에서 04부분
- `component/custom/manager/base/home/04` 로 위치 변경

- [🎨 manager home 04 퍼블리싱](https://github.com/mobi-projects/nail-case-client/commit/8661613ab5bdd3dcee7ef7052fb55a08c3a00b9f)
-title부분과 추가되지않았던 버튼 04부분에 추가하였습니다 
<img width="1197" alt="스크린샷 2024-06-18 오후 3 59 51" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/1e44f21e-1859-4af2-a1cc-3f5c007c30b2">

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-18 07:32 UTC, snkchan commented
- <img width="261" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/dfa14d4d-e9f0-4abc-b99e-584cd970bd7b">
- 피그마에 나와있는 디자인과 일치하지않습니다..!
- px, 구분선 , 공지글일경우(맨앞 카드) `Notice`문구 또한 포함이안되있습니다.

2024-06-18 12:23 UTC, keeprok commented
# 수정사항 
-[🎉 fontWeight 토큰 추가](https://github.com/mobi-projects/nail-case-client/pull/61/commits/989131c3e20a5f81e5da49de59412c66405f6c81)
- fontWeight - medium 추가했습니다

-[🎨 manager home MainCard 퍼블리싱](https://github.com/mobi-projects/nail-case-client/pull/61/commits/8f361e9520adb13aa767542e74825025c0b08972)
- 위에서 작성해주신 notice 부분은 이전css적인부분에서 피그마와 맞지않는 부분이 많아 수정 조치 하였습니다 

<img width="364" alt="스크린샷 2024-06-18 오후 9 14 41" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/37154c2a-96c2-4419-94ce-568738bc6e08">

-[🎨 manager home SubCard 퍼블리싱](https://github.com/mobi-projects/nail-case-client/pull/61/commits/d65fd17a7fa657dbc3c931d8f574d866e6997ed1)
- 글씨굵기와 위치 피그마에 맞게 다시 한번수정하였습니다 
<img width="546" alt="스크린샷 2024-06-18 오후 9 14 46" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/6b066afb-a3f7-4bb2-b552-09d0618423cd">

-[🎨 manager home MainCard 작업완료](https://github.com/mobi-projects/nail-case-client/pull/61/commits/c075b4c6d414bbf2fc02b12fe9468432259b3229)
- Main 부분 스크롤 시 사이즈가 줄어드는 이슈가있어  사이즈 고정을 주었습니다 
- 동일한것을 확인할수있습니다 
<img width="1084" alt="스크린샷 2024-06-18 오후 9 22 04" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/76a649a7-00bf-4260-8e31-b467b14618fd">
<img width="1087" alt="스크린샷 2024-06-18 오후 9 23 12" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/9f756f7f-4c58-4a0e-869a-e1fcf1f59e09">

2024-06-19 03:36 UTC, snkchan requested changes
- 하나더 수정해주셔야할것 같습니다..!
- <img width="799" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/a33d0c2b-2f9d-4149-836b-5186b17adc6a">
- 지금 **빨간선** 보시면 피그마에선 card와 스크롤사이에 여백이있는데 위에 이미지에서 보여지는커처럼 아래스크롤과 바로붙어있는데 제가 window라서 이렇게보이는건가요?

2024-06-19 03:36 UTC, snkchan commented on src/component/custom/manager/base/home/04/04-01/index.tsx
> +			<hr className="w-full border border-Gray20"></hr>
- ![Uploading image.png…]()
- border-Gray10 색상입니다..!

2024-06-19 06:24 UTC, closed without merging