design : manager/base/my-shop/home/04-02 완료
mobi-projects/nail-case-client pull request #63
Opened 2024-06-19 02:33 UTC by HeesikK

## 🔥 Issues

- issue: [NAILCASE-132](https://nailcase.atlassian.net/browse/NAILCASE-132)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 manager-base-my-shop-home-04-02 퍼블리싱 완료](https://github.com/mobi-projects/nail-case-client/commit/2d9c140a38444b3d65bbcccac25bb80fe50fc1f3)
  - manager/base/my-shop/home/04-02 퍼블리싱 완료 했습니다.
  - 디자인은 배포된 vercel을 통해 확인할 수 있습니다.

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-19 03:50 UTC, snkchan requested changes
- <img width="464" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/b24ded5d-814c-4bf2-8901-be1415830c4f">
- slider에 disabled적용해주셔야 할것같습니다. 혼자만 색이보입니다.

2024-06-19 08:48 UTC, HeesikK commented
> * <img alt="image" width="464" src="https://private-user-images.githubusercontent.com/144839872/340905931-b24ded5d-814c-4bf2-8901-be1415830c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcwNjksIm5iZiI6MTcxODc4Njc2OSwicGF0aCI6Ii8xNDQ4Mzk4NzIvMzQwOTA1OTMxLWIyNGRlZDVkLTgxNGMtNGJmMi04OTAxLWJlMTQxNTgzMGM0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwODQ2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGY2ZGFhYzZhMWQ2ZmUyZTg5ZjZlNTdlMDQ2OGM4ZWI5MmMwNDhhYjE0NmY5OGViYmRhMDE2NTIwZTJmZmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xy12cdQH-HoBeUFj60KqXOqs3hiSkGZiVPQIUrWEtWw">
> * slider에 disabled적용해주셔야 할것같습니다. 혼자만 색이보입니다.

- [🎨 manager-base-my-shop-home-04-02 퍼블리싱 완료 ](https://github.com/mobi-projects/nail-case-client/commit/2d9c140a38444b3d65bbcccac25bb80fe50fc1f3) 해당

> * <img alt="image" width="464" src="https://private-user-images.githubusercontent.com/144839872/340905931-b24ded5d-814c-4bf2-8901-be1415830c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcxODQsIm5iZiI6MTcxODc4Njg4NCwicGF0aCI6Ii8xNDQ4Mzk4NzIvMzQwOTA1OTMxLWIyNGRlZDVkLTgxNGMtNGJmMi04OTAxLWJlMTQxNTgzMGM0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwODQ4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjNiZTg3ZmU0YWUwNTYzZTRmMTc4OGY4NWRiYTFlOTdlMDJkZjk5ZTJiYjc2Mjk2ZTQ3ZTRiYjllODkyMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7QHiu6-Vs28iWdrXto-BtPm3lqwkUjsfp8eQywlkEfA">
> * slider에 disabled적용해주셔야 할것같습니다. 혼자만 색이보입니다.

- [🎨 manager-base-my-shop-home-04-02 Slider disabled 적용](https://github.com/mobi-projects/nail-case-client/commit/d0cd94c0fe555c569af920d2f47b3c3050ad8c89) 해당 부분 disabled 추가하여 디자인 적용했습니다..!

2024-06-19 08:58 UTC, snkchan approved these changes
- 따봉..! 확인했습니다.👍

2024-06-19 13:10 UTC, keeprok requested changes
- drop shadow가 경계선에도 다들어가있는것같아요 ;;
<img width="811" alt="스크린샷 2024-06-19 오후 10 10 01" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/1cd0b12b-c973-4326-b437-7299636d6f69">

2024-06-21 02:43 UTC, HeesikK commented
> * drop shadow가 경계선에도 다들어가있는것같아요 ;;
> 
> <img alt="스크린샷 2024-06-19 오후 10 10 01" width="811" src="https://private-user-images.githubusercontent.com/140785214/341086727-1cd0b12b-c973-4326-b437-7299636d6f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzgwMjUsIm5iZiI6MTcxODkzNzcyNSwicGF0aCI6Ii8xNDA3ODUyMTQvMzQxMDg2NzI3LTFjZDBiMTJiLWM5NzMtNDMyNi1iNDM3LTcyOTk2MzZkNmY2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwMjQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmQwNWUyZjlhNDQzZmM2NWM3M2Y4YTQ4NDEyZGQ3YWUwMjE1OTIyNDQzNmM1NzFkMGE2MjllOTI0YWVhMTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UjWA4IxODYYh8FwFMmyqp9d-HQp6HWsObv4hp3RnxRU">

- 확인해보니 drop shadow 적용은 안되어 있는거 같습니다. border 굵기 문제인거 같아 수정완료 했으니 확인부탁드릴게용

2024-06-22 08:51 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"
# Description
- 고생하셨습니다 :)

2024-06-22 09:46 UTC, snkchan approved these changes
- LGTM.!

2024-06-22 09:46 UTC, snkchan commented on src/component/custom/manager/base/my-shop/home/04/index.tsx
> +
- type선언은 파일의 상단에 위치시켜서 한번에 보이도록 앞으로 코드를작성해주시면 좋을것 같아요
```tsx
ex ) comp.tsx
type APT = {}
type BPT  = {}
export default function Comp = {
   <A/>
   <B/>
}
function A (){
}
function B (){
}

```
의 형식으로 관리하는편이좋을것 같습니다.!

2024-06-23 05:25 UTC, keeprok approved these changes

2024-06-23 05:35 UTC, merged