design : event detail
mobi-projects/nail-case-client pull request #75
Opened 2024-06-20 15:38 UTC by keeprok

## 🔥 Issues

* issue : [NAILCASE-165](https://nailcase.atlassian.net/browse/NAILCASE-165)
<br/>
<br/>

## 🎯 작업 내용

- [🎨 EventDetail 생성](https://github.com/mobi-projects/nail-case-client/commit/ac219db0cfbed158d387d5e9a2fc5f4692774c8c)
- variant : plus 상태 add : true(default)
- <img width="309" alt="스크린샷 2024-06-21 오전 12 00 26" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/c7bbaeb8-ec91-4be0-bf4d-f3702e4475cd">
- variant : PB add : false
- <img width="293" alt="스크린샷 2024-06-21 오전 12 00 50" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/b662253d-a7f4-4ffe-8850-e1724a920af3">
- variant : PY add. : false isClicked : true
- <img width="320" alt="스크린샷 2024-06-21 오전 12 35 41" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/01ae1277-ec45-4c28-bb85-fb810d4fd6fb">

-  [⚡️ 사용방법 변경](https://github.com/mobi-projects/nail-case-client/commit/f6b5fe6097271c2208e56b08874b463bc834f3a0)
- [✨ isClicked 기능추가](https://github.com/mobi-projects/nail-case-client/commit/e407572b9e801f3d77e7df68238a0acbabdc64dd)
- 위 2가지는 위 방식에 적혀있습니다  생략하겠습니다
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-20 19:59 UTC, TransparentDeveloper requested changes
고생하셨습니다.!!

2024-06-20 19:59 UTC, TransparentDeveloper commented on src/component/common/nt-event-deatli/index.tsx
> +}: NTEventDetailPT) {
# Request Level
  - [x] "🚧 재고해주시길.."


# Description
`NTEvnetDetailPT` 타입 관련해서 제안 및 질문 남깁니다 :)

### ⓵
일단, `variant` 는 cva() 객체로 전달될 값이니까 조금 더 우아하게(?) 작성하면 좋을 것 같은데요.? 
`VariantProps<typeof EventDetailVariants>` 이렇게? _(NTButton 참고)_

수정하면, 나중에 디자이너가 `variant` 목록을 변경할 경우(?) 도 대비하고 좋을 것 같습니다.

### ⓶
`add` 는 의미가 너무 불명확한 것 같습니다.. 수정 부탁합니다.

### ⓷
`isClicked` 이건 어떻게 사용해야하죠?
사용 예시를 적어주시겠어요?

### ⓸
`...props` 가 넘어올까요?? 저는 안될 거 같긴한데,,
확인 한번 부탁드립니다.
```tsx
<NTEventDetail onClick={()=>{console.log("click!!")}} />
```

2024-06-21 11:08 UTC, snkchan requested changes
- 고생하셧습니다.. ! 몇가지 수정해야할것 같고. 컴포넌트설계면에서 불확실한부분들이 존재하는것 같습니다.
## 1. add
add를 props로전달받도록 설정되어있는데 그렇다면 add는 외부에서 상태를 주입받아야하는것인가요?? 어떻게 일정을 추가할지에대한 설계가부족한것같은데 혹시 riel님이 생각하는 add는 어떻게 동작하는것인가요?
## 2.isClicked
isClicked또한 지금 설계가어떻게된것인지 모르겠습니다. 하나의 isClicked를 전달받는다면 전체 NTEventDetail중 1개만 focus될것인데 이게 저희가원하는 설계인가요?

2024-06-21 11:08 UTC, snkchan commented on src/component/common/nt-event-deatli/index.tsx
> +	" w-fit min-w-[263px] pl-[21px] rounded-[12px] flex justify-start items-center py-[14px]",
- <img width="317" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/817a1896-5143-4cdd-b276-00ab88d0a356">
- w-fit 이아니라 w-full을 해야하는거 아닐까요??? 디자이너의 시술시간에 맞춰서 길이가변경되려면 부모테그의 크기를 따라가도록 설정되어야 할것 같은데? 어떻게 생각하시나요?

2024-06-21 11:08 UTC, snkchan commented on src/component/common/nt-event-deatli/index.tsx
> +					></NTIcon>
또 태그를 열었습니다...

2024-06-21 12:37 UTC, keeprok commented on src/component/common/nt-event-deatli/index.tsx
> +					></NTIcon>
아... 놓쳤습니다

2024-06-23 14:31 UTC, keeprok commented on src/component/common/nt-event-deatli/index.tsx
> +}: NTEventDetailPT) {
수정사항이 많아서 추가적인 #수정사항으로 올리겠습니다

2024-06-23 14:31 UTC, keeprok commented on src/component/common/nt-event-deatli/index.tsx
> +					></NTIcon>
수정하였습니다

2024-06-23 14:32 UTC, keeprok commented on src/component/common/nt-event-deatli/index.tsx
> +	" w-fit min-w-[263px] pl-[21px] rounded-[12px] flex justify-start items-center py-[14px]",
#수정사항으로 올리겠습니다

2024-06-23 16:54 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"

# Description
코드가 훨씬 간결해졌네요 👍 
고생하셨어요.!

2024-06-24 07:53 UTC, keeprok commented
# 수정사항 

<div><img width="489" alt="스크린샷 2024-06-24 오후 4 49 20" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/e1e93ed7-1a90-483c-8dc6-a9470e861eb3"></div>

- 위 부분은 추가 하지않았습니다 코드로는 
```tsx
<span className="text-Callout font-Light text-Gray100">
						새로운 일정 추가하기
					</span>
					<NTIcon
						icon="addRoundLight"
						className="flex h-[22px] w-[22px] items-center"
					/>
```
```tsx
Plus: "border-[1.5px] border-dashed",
```
위 코드 2개는 현재 피그마에서 공용 컴포넌트 에서만 있고 실질적으로 사용하는 부분이 없기때문에 
사용방법을 알수가 없어 따로 추가하진않았습니다 추후에 일정추가하는 부분이 생긴다면 추가 해주시길바라겠습니다

2024-06-24 11:39 UTC, snkchan approved these changes
- LGTM.!

2024-06-24 11:39 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-24 11:42 UTC, merged