design : manager/base/schedule/this-month
mobi-projects/nail-case-client pull request #77
Opened 2024-06-20 18:59 UTC by snkchan

## 🔥 Issues

* issue: [NAILCASE-161](https://nailcase.atlassian.net/browse/NAILCASE-161)
sub-issues:
  - [NAILCASE-171](https://nailcase.atlassian.net/browse/NAILCASE-171)
<br/>
<br/>

## 🎯 작업 내용

- [🎨 월별스케줄 퍼블리싱](https://github.com/mobi-projects/nail-case-client/commit/fa7787586e8d59795962069a429b3e4364fb3d23)
# manager/base/schedule/this-month는 월별스케줄의 달력입니다.
- <img width="475" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/a02762bd-a2f0-4be5-b164-aaf15f339bea">
## 참고사항
배경색이 BGblue-01이적용안된상태라서 테두리가없는것처럼 보이지만 **사실존재합니다. 다음 사진은 참고용입니다.**
- <img width="567" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/fc36d8e2-2f13-42fd-8740-42abf0712157">
# 🎁 [Vecel에서 확인하기](https://nail-case-client-dgfom4z8o-newtips.vercel.app/manager/base/schedule)(Click me)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-20 19:30 UTC, TransparentDeveloper requested changes
# Request Level
  - [x] "🚧 재고해주시길.."

# Description

고생하셨습니다. 👏 역시 대단하십니다.!
한 가지만 확인해주시면 감사하겠습니다. 🫡

------

<div align="center">
<img width="1469" alt="스크린샷 2024-06-21 오전 4 23 50" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/aafac3db-6584-4a77-abb0-f0af4370790a">
</div>

피그마 디자인 상에선 그림자 효과가 있는데, vercel 에서 확인해보니 적용이 안된 것 같아서요. 
효과 추가할 수 있을까요??

2024-06-21 12:42 UTC, keeprok approved these changes
LGTBBB>..

2024-06-22 11:03 UTC, snkchan commented
@TransparentDeveloper 
- [🎨 drop shadow 적용](https://github.com/mobi-projects/nail-case-client/pull/77/commits/c8986bd522082f97afc628828d0e08274f4e16ec)
- figma요구사항에 맞게 drop-shadow를 다음과같이 적용했습니다.
### 요구사항
- <img width="339" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/f4bcb6a8-1049-488e-8f66-1be83a043a0d">
### 적용
- <img width="659" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/ab05209b-d616-426d-bc06-01112c514a65"><br/>
  - X, Y 오프셋: 2.99px
  - 블러 반경: 14.34px
  - 색상과 불투명도: rgba(224, 224, 224, 0.6) (E0E0E0 색상에 60% 불투명도)
 ## 결과물(배경색은 pr에는 포함X )
 - <img width="518" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/2a04aa47-b863-4276-97fd-85eb18555997">

2024-06-22 11:06 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"

# Description
고생하셨습니다.!

2024-06-22 11:07 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-22 11:13 UTC, merged