design : manager/base/my/shop/review/01-02
mobi-projects/nail-case-client pull request #81
Opened 2024-06-22 09:09 UTC by keeprok

## 🔥 Issues

*issue:[NAILCASE-139](https://nailcase.atlassian.net/browse/NAILCASE-139)
sub-issues:
- [NAILCASE-175](https://nailcase.atlassian.net/browse/NAILCASE-175)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 manager/base/my-shop/Review/01-02-01](https://github.com/mobi-projects/nail-case-client/commit/46b02a6a878deb3ec98912f324809a7bef9ada13)
- <img width="549" alt="스크린샷 2024-06-22 오후 1 18 17" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/e091fae8-a593-4809-bd5e-06948b69f400">

- [🎨 manager/base/my-shop/Review/01-02-02](https://github.com/mobi-projects/nail-case-client/commit/4220fd9d2f285ade4864e7b4209121f8caf20ca5)

<img width="601" alt="스크린샷 2024-06-22 오후 1 18 21" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/03060dae-aa34-406c-b85a-84e4637f3963">

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-22 09:09 UTC, keeprok commented
# 수정사항 
- [🎨 starFull 아이콘 변경](https://github.com/mobi-projects/nail-case-client/commit/9839fbe27db429fc0132788f568b14c65eec29ce)
- 별 모양 figma 에 맞는 모양 으로 수정 위 사진과 다름
<img width="32" alt="스크린샷 2024-06-22 오후 6 07 49" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/e7d8453b-8741-43ff-95b0-f64997b360d1">

2024-06-22 10:22 UTC, snkchan commented
- 그래서 review/01-02가 어디까지작업을 하신걸까요???? 저희 pr올릴때 해당부분이 어디를 작업한거다 이미지를 첨부하기로했엇는데

2024-06-22 10:26 UTC, snkchan requested changes
- 한가지 요청사항이 있습니다!

2024-06-22 10:26 UTC, snkchan commented on src/component/custom/manager/base/my-shop/review/01/index.tsx
> +	]
- 위에있던것과 마찬가지로 해당부분은 figma요구사항에 맞게 보여지기위한 임시코드인거 같은데 다음부터는 pr내용에는 포함안되는 편이좋을것 같습니다..! 우선은그냥 패스하도록하죵?

2024-06-22 10:26 UTC, snkchan commented on src/component/custom/manager/base/my-shop/review/01/index.tsx
> +				style={{ width: `${widthPercentage}%` }}
-? style속성을 사용하신이유가 무엇인가요???? cn function으로도 충분히 처리할수있을것 같은데

2024-06-22 12:31 UTC, keeprok commented on src/component/custom/manager/base/my-shop/review/01/index.tsx
> +	]
아 vercel에서 확인되도록 넣엇습니다

2024-06-23 04:22 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"

# Description
 고생하셨습니다.
 
그래프에서 낮은 점수는 출력되는 모양이 조금 이상하네요.
아래 그램에서, `1`&`2` 점  확대해서보시면 영역을 벗어나 있습니다.
 
<img width="369" alt="스크린샷 2024-06-23 오후 1 20 06" src="https://github.com/mobi-projects/nail-case-client/assets/50646145/f127e0e1-e67f-4a30-982a-5b92a73e3fe7">

2024-06-23 04:57 UTC, keeprok commented on src/component/custom/manager/base/my-shop/review/01/index.tsx
> +				style={{ width: `${widthPercentage}%` }}
cn 으로 처리하면동적으로 처리하는게불가능하다고 해. 
  if (widthPercentage <= 0) return 'w-0';
  if (widthPercentage <= 10) return 'w-1/10';
  if (widthPercentage <= 20) return 'w-2/10';
  if (widthPercentage <= 30) return 'w-3/10';
  if (widthPercentage <= 40) return 'w-4/10';
  if (widthPercentage <= 50) return 'w-5/10';
  if (widthPercentage <= 60) return 'w-6/10';
  if (widthPercentage <= 70) return 'w-7/10';
  if (widthPercentage <= 80) return 'w-8/10';
  if (widthPercentage <= 90) return 'w-9/10'; 이런식으로. 미리 만들어두거나 또는 
classNames를 설치하여서 사용을해야되는데 어느 방안이 좋을지 이야기 해봐야겠습니다

2024-06-23 05:02 UTC, keeprok commented
@TransparentDeveloper 
<img width="84" alt="스크린샷 2024-06-23 오후 2 00 54" src="https://github.com/mobi-projects/nail-case-client/assets/140785214/14257fe3-1fdf-4d2b-8f0b-26370546de75">
놀랍게도 위사진은 피그마 로서 비슷합니다 조금더 왼쪽으로는 가는것은 수정사항에 같이 반영해서 넣겠습니다

2024-06-23 06:46 UTC, snkchan commented on src/component/custom/manager/base/my-shop/review/01/index.tsx
> +				style={{ width: `${widthPercentage}%` }}
```tsx
className = {cn("기본적으로 적용될 css", `w-[${widthPercentage}]`)} 
```
이렇게 적용할수도있고 방법이 있을것같은데

2024-06-23 06:58 UTC, snkchan approved these changes
- LGTM..!

2024-06-23 07:22 UTC, merged