design : manager/base/schedule/today
mobi-projects/nail-case-client pull request #84
Opened 2024-06-22 11:53 UTC by HeesikK

## 🔥 Issues

* issue: [NAILCASE-163](https://nailcase.atlassian.net/browse/NAILCASE-163)
sub-issues:
  - [NAILCASE-174](https://nailcase.atlassian.net/browse/NAILCASE-174)
<br/>
<br/>

## 🎯 작업 내용

- [🎨 오늘스케줄 퍼블리싱](https://github.com/mobi-projects/nail-case-client/commit/f079b07b9a1fbad75c644516e28e1825c7ce84bb)
  ## 오늘 스케줄 퍼블리싱 완료했습니다.
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/5fc6ee06-9365-41fa-aec6-330666043c5c)

  ## 참고사항
  ### pr을 올리는 현재 시각이 오후 8시 47분이여서 ui가 위 사진처럼 `시술중` 버튼이 없습니다.
  ### 아래 사진은 오후 7시쯤 캡쳐한 사진입니다. 해당 시간에 스케줄이 있으므로 `시술중` 버튼이 있습니다.
  ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/30024385-5697-49af-8f94-081f9b7e8b71)
 
  ## 해결필요❗
  ### 아래 사진을 보면 스케줄이 다 끝난 시점에 ui입니다.
  ### 시술중일때는 `시술중` 버튼이 있고 다음 예약일 때는 `변경하기` 및 `채팅하기` 버튼이 있습니다.
  ### 종료된 예약(시술이 완료된) 예약에 대해서는 어떤 ui가 적용되면 좋을까요? 
    ![image](https://github.com/mobi-projects/nail-case-client/assets/127207625/5fc6ee06-9365-41fa-aec6-330666043c5c)

# 🎁 [Vecel에서 확인하기](https://nail-case-client-obfd350rt-newtips.vercel.app/manager/base/schedule/today)(Click me)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-22 11:57 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-06-22 13:31 UTC, snkchan requested changes
- 수정요청사항이있습니다.!

2024-06-22 13:31 UTC, snkchan commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +			style={{ height: `${height}px` }}
- style태그를 사용하신이유가뭐죠????? 
- 혹시 className에 변수를 적용하면 실행이안되는것이 문제였나요?
- cn function을 사용하시면 변수에맞게 css를 적용하실수있습니다.

2024-06-22 13:31 UTC, snkchan commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +			style={{ height: `${boxHeight}px` }}
- 이부분도 마찬가지로cn function으로 적용하셔야할듯합니다.

2024-06-22 13:32 UTC, snkchan commented
- pr에서 의견을 요청한부분은 설계상 문제이니깐 회의때해결을 해볼까요?

2024-06-22 14:03 UTC, snkchan requested changes
- 하나더 부탁드립니다.

2024-06-22 14:06 UTC, snkchan requested changes
수정 부탁드립니다.

2024-06-22 14:06 UTC, snkchan commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +		<div className="flex h-fit w-full flex-col rounded-[26px] border">
- 피그마요구사항에서 확인하시면 테두리에 drop shadow를 적용했습니다.
- [이전에 제가올린 pr](https://github.com/mobi-projects/nail-case-client/pull/77)에서 확인해보시면 drop shadow를 피그마요구사항에 맞게 적용하는 방법이 나와있으니 혹시 모르신다면 해당부분 확인해서 적용해주십쇼!
- <img width="771" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/d211c4ef-1f09-469b-ab7c-58aa0483b49e">

2024-06-23 04:29 UTC, keeprok commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +		<div className="flex h-fit w-full flex-col rounded-[26px] border">
이부분 제가 놓쳤던것같은데 저렇게 사용안하시고 제가 config를 통해 stle토큰으로 만들었습니다 shadow-costomGray이고 챈님이 올려주신 사진으로는 회색 60%로 사용중인데 그부분을 통해 shadow-costomGray60으로 하시면 됩니다

2024-06-23 04:31 UTC, keeprok reviewed
수고하셨습니다

2024-06-23 04:31 UTC, keeprok commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +}
type안에 부분 특히 DayScheduleTimePT= DayScheduleButtonPT 동일한것같은데 재사용가능하게 하는것이 좋지않을까요?

2024-06-23 04:52 UTC, HeesikK commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +			style={{ height: `${height}px` }}
- [⚡ ️style -> className 으로 변경 ](https://github.com/mobi-projects/nail-case-client/commit/a96a178a57825999e4626923547c9495ee4c340e) 

className으로 수정 완료했습니다.

2024-06-23 04:52 UTC, HeesikK commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +			style={{ height: `${boxHeight}px` }}
적용 완료했습니다..!

2024-06-23 04:58 UTC, HeesikK commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +		<div className="flex h-fit w-full flex-col rounded-[26px] border">
- [🎨 drop shadow 적용](https://github.com/mobi-projects/nail-case-client/commit/e7b81ddc43b018b94092a6f38c1ca4317f12a300)

해당 부분 확인하고 수정 완료했습니다..!

2024-06-23 05:02 UTC, HeesikK commented on src/component/custom/manager/base/schedule/today/01/index.tsx
> +}
- [⚡️ 중복되는 타입 제거](https://github.com/mobi-projects/nail-case-client/commit/29724ce3b74079a58fc812c7bd4fb3496d36f6b1) 

중복되는 타입 제거하고 하나로 합쳐서 적용했습니다...!

2024-06-23 07:03 UTC, snkchan approved these changes
- LGTM..!

2024-06-23 10:16 UTC, keeprok approved these changes
확인했습니당

2024-06-23 11:17 UTC, merged