design : manager/base/my-shop/layout/modal/01
mobi-projects/nail-case-client pull request #89
Opened 2024-06-22 14:25 UTC by TransparentDeveloper

## 🔥 Issues

* issue: [NAILCASE-140](https://nailcase.atlassian.net/browse/NAILCASE-140)
- sub-issues:
  - [NAILCASE-176](https://nailcase.atlassian.net/browse/NAILCASE-176)

<br/>
<br/>

## 🎯 작업 내용

- [🎨 소개글 수정 모달 퍼블리싱](https://github.com/mobi-projects/nail-case-client/commit/43a4cc8222c22c279987e5d73c309cc2ac7b1bf1)
- [✨ "저장하기" 버튼 클릭 시, 모달닫기](https://github.com/mobi-projects/nail-case-client/commit/a484db880d35f56b79f0fc70e62a46ecfb6085a1)

### 💫 Publishing 대상

<div align="center">

<img src="https://github.com/mobi-projects/nail-case-client/assets/50646145/019f425b-1c7b-4e4a-b78a-610145a65f6f" alt="introduction edit modal image" width=300/>

</div>

### 📺 시연영상

<div align="center">

https://github.com/mobi-projects/nail-case-client/assets/50646145/eaa3715d-d48e-4c85-95b9-32fd0548c513

</div>

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-23 05:06 UTC, keeprok approved these changes
영상이 긴이유 가 있엇군요 ㅎㅎ

2024-06-23 06:43 UTC, snkchan requested changes
- 고생하셧습니다..!

2024-06-23 06:43 UTC, snkchan commented on src/component/custom/manager/base/my-shop/layout/modal/01/index.tsx
> +					<p key={idx} className="text-Title02 text-Gray90">
<div align="center">
<img width="440" alt="image" src="https://github.com/mobi-projects/nail-case-client/assets/144839872/a3490868-0034-4e20-8771-4c9613d4f11b">
</div>
text-Title02는 font-size가 24px이라서 요구사항과 맞지않습니다. 아마 굵기도 다른거같은데 수정부탁드립니다.!

2024-06-23 17:44 UTC, TransparentDeveloper commented on src/component/custom/manager/base/my-shop/layout/modal/01/index.tsx
> +					<p key={idx} className="text-Title02 text-Gray90">
- [🎨 font-size, font-weight 수정](https://github.com/mobi-projects/nail-case-client/pull/89/commits/6d962675a39bb5fbfec14966738c0bb086aabea7)
  - 수정 완료했습니다.
  - 👇 결과 화면 입니다.

2024-06-23 17:44 UTC, snkchan approved these changes
- LGTM..! 고생하셧습니다!

2024-06-24 03:15 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-24 08:31 UTC, merged