design : manager/base/home/01
mobi-projects/nail-case-client pull request #98
Opened 2024-06-25 06:06 UTC by keeprok

## 🔥 Issues

* issue:[NAILCASE-137](https://nailcase.atlassian.net/browse/NAILCASE-137)
* sub-issues:
     - [NAILCASE-166](https://nailcase.atlassian.net/browse/NAILCASE-166)

<br/>
<br/>

## 🎯 작업 내용

[🎨 manager/base/01](https://github.com/mobi-projects/nail-case-client/commit/1ba43fa0212de445f806e322fe046a472944cba8)
- 01-01,01-02 생성 했습니다 
# Home/01-01 작업 WatingCard , Home/01-02 작업 ConfirmedCard 완료
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/d967e659-70e4-4dd3-8393-4a09d20c200d)
- 피그마 입니다 
## Home/01-01-01  작업 WatingTotalCard 완료
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/0ceb7a67-53d7-405f-a28c-2978688724bf)
## Home/01-01-02	작업	WatingDetailCard  완료
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/6872f704-7a66-4990-a62c-da4c4423a0f7)
## Home/01-02-01 , Home/01-02-02작업 ConfirmedCardHeader , TotalConfirmed  완료
 
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/956b0f53-3df9-4cc9-be8e-eacb3460260e)

<br/>

# 작업물 
![image](https://github.com/mobi-projects/nail-case-client/assets/140785214/10e0c9e9-f989-41f1-93b4-f9172e039aab)
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-06-25 16:54 UTC, snkchan requested changes
결과물을보니 피그마와 아이콘이달라서 이부분은 수정해야할것 같습니다.
- [여기](https://github.com/mobi-projects/nail-case-client/pull/39)들어가셔서 댓글확인하시면 어떤 아이콘인지 나와있습니다.!

2024-06-25 21:38 UTC, TransparentDeveloper approved these changes
# Request Level
  - [x] "✅ LGTM"


# Description
고생하셨습니다.

2024-06-26 15:37 UTC, snkchan requested changes
늦게 리뷰남겨서 죄송한데 스펠링좀 고쳐주십셔..
wating ===> waiting으로 오타 수정좀요

2024-06-27 01:08 UTC, HeesikK approved these changes
고생하셨습니다..!

2024-06-27 09:36 UTC, snkchan approved these changes
- LGTM.!

2024-06-27 10:00 UTC, merged